<?php die( 'These aren\'t the droids you\'re looking for.' );
// 
// Extract of translatable strings from lib/pro/.
// 
_x( 'Webpage Title Tag', 'option label', 'wpsso' );
_x( 'Use Filtered Content', 'option label', 'wpsso' );
_x( '(recommended - see help text)', 'option comment', 'wpsso' );
_x( 'Use Filtered Excerpt', 'option label', 'wpsso' );
_x( '(recommended - only if using shortcodes in excerpts)', 'option comment', 'wpsso' );
_x( 'Enable Excerpt for Pages', 'option label', 'wpsso' );
_x( 'Enable Tags for Pages', 'option label', 'wpsso' );
_x( 'Add Person Role for New Users', 'option label', 'wpsso' );
_x( 'Inherit Featured Image', 'option label', 'wpsso' );
_x( '(recommended)', 'option comment', 'wpsso' );
_x( 'Inherit Custom Images', 'option label', 'wpsso' );
_x( '(recommended)', 'option comment', 'wpsso' );
_x( 'Image Dimension Checks', 'option label', 'wpsso' );
_x( '(recommended)', 'option comment', 'wpsso' );
_x( 'Prevent Thumbnail Conflicts', 'option label', 'wpsso' );
_x( '(recommended)', 'option comment', 'wpsso' );
_x( 'Upscale Media Library Images', 'option label', 'wpsso' );
_x( 'Maximum Image Upscale Percent', 'option label', 'wpsso' );
_x( 'Plugin and Theme Integration', 'metabox title', 'wpsso' );
_x( 'Speakable CSS Selectors', 'option label', 'wpsso' );
_x( 'Check for Duplicate Meta Tags', 'option label', 'wpsso' );
_x( 'Include VAT in Product Prices', 'option label', 'wpsso' );
_x( 'Import All in One SEO Pack Metadata', 'option label', 'wpsso' );
_x( 'Import Rank Math SEO Metadata', 'option label', 'wpsso' );
_x( 'Import The SEO Framework Metadata', 'option label', 'wpsso' );
_x( 'Import WP Meta SEO Metadata', 'option label', 'wpsso' );
_x( 'Import Yoast SEO Metadata', 'option label', 'wpsso' );
_x( 'Import Yoast SEO Block Attrs', 'option label', 'wpsso' );
_x( 'Title Tag Site Suffix', 'option label', 'wpsso' );
_x( 'Title Tag Tagline Suffix', 'option label', 'wpsso' );
_x( 'Content Image Alt Prefix', 'option label', 'wpsso' );
_x( 'WP Caption Text Prefix', 'option label', 'wpsso' );
_x( 'Comment Title', 'option label', 'wpsso' );
_x( 'Reply Comment Title', 'option label', 'wpsso' );
_x( 'Review Comment Title', 'option label', 'wpsso' );
_x( 'Product Variation Title', 'option label', 'wpsso' );
_x( '404 Page Title', 'option label', 'wpsso' );
_x( '404 Page Description', 'option label', 'wpsso' );
_x( 'No Title Text', 'option label', 'wpsso' );
_x( 'No Description Text', 'option label', 'wpsso' );
_x( 'Archive Pages', 'metabox title', 'wpsso' );
_x( 'Term Archive Title', 'option label', 'wpsso' );
_x( 'Term Archive Description', 'option label', 'wpsso' );
_x( 'Author Archive Title', 'option label', 'wpsso' );
_x( 'Author Archive Description', 'option label', 'wpsso' );
_x( 'Search Results Title', 'option label', 'wpsso' );
_x( 'Search Results Description', 'option label', 'wpsso' );
_x( 'Year Archive Title', 'option label', 'wpsso' );
_x( 'Year Archive Description', 'option label', 'wpsso' );
_x( 'Month Archive Title', 'option label', 'wpsso' );
_x( 'Month Archive Description', 'option label', 'wpsso' );
_x( 'Day Archive Title', 'option label', 'wpsso' );
_x( 'Day Archive Description', 'option label', 'wpsso' );
_x( 'Post Type Archive Pages', 'metabox title', 'wpsso' );
_x( '%s Archive Page', 'metabox title', 'wpsso' );
_x( 'Archive Page Title', 'option label', 'wpsso' );
_x( 'Archive Page Description', 'option label', 'wpsso' );
_x( 'Open Graph (Facebook and oEmbed)', 'option label', 'wpsso' );
_x( 'Pinterest Pin It', 'option label', 'wpsso' );
_x( 'Schema 1:1 (Google Rich Results)', 'option label', 'wpsso' );
_x( 'Schema 4:3 (Google Rich Results)', 'option label', 'wpsso' );
_x( 'Schema 16:9 (Google Rich Results)', 'option label', 'wpsso' );
_x( 'Schema Thumbnail', 'option label', 'wpsso' );
_x( 'Twitter Summary Card', 'option label', 'wpsso' );
_x( 'Twitter Summary Card Large Image', 'option label', 'wpsso' );
_x( 'Options to Show by Default', 'option label', 'wpsso' );
_x( 'Validators', 'toolbar menu title', 'wpsso' );
_x( 'Show %s Toolbar Menu', 'option label', 'wpsso' );
_x( 'Show %s Menu Items', 'option label', 'wpsso' );
_x( 'Show %s Metabox', 'option label', 'wpsso' );
_x( 'WP List Table Columns', 'option label', 'wpsso' );
_x( 'Open Graph Type Select Format', 'option label', 'wpsso' );
_x( 'Schema Type Select Format', 'option label', 'wpsso' );
_x( 'Gravatar is Default Author Image', 'option label', 'wpsso' );
_x( 'Gravatar Image Size', 'option label', 'wpsso' );
_x( 'Check for Embedded Media', 'option label', 'wpsso' );
_x( 'URL Shortening Service', 'option label', 'wpsso' );
_x( 'Minimum URL Length to Shorten', 'option label', 'wpsso' );
_x( 'characters', 'option comment', 'wpsso' );
_x( 'Use Short URL for WP Shortlink', 'option label', 'wpsso' );
_x( 'Add "%s" HTML Tag', 'option label', 'wpsso' );
_x( 'Bitly (URL Shortener)', 'metabox title', 'wpsso' );
_x( 'Bitly Generic Access Token', 'option label', 'wpsso' );
_x( 'Bitly Short Domain (Optional)', 'option label', 'wpsso' );
_x( 'Bitly Group Name (Optional)', 'option label', 'wpsso' );
_x( 'DLMY.App (URL Shortener)', 'metabox title', 'wpsso' );
_x( 'DLMY.App API Key', 'option label', 'wpsso' );
_x( 'Ow.ly (URL Shortener)', 'metabox title', 'wpsso' );
_x( 'Ow.ly API Key', 'option label', 'wpsso' );
_x( 'YOURLS (URL Shortener)', 'metabox title', 'wpsso' );
_x( 'YOURLS API URL', 'option label', 'wpsso' );
_x( 'YOURLS Username', 'option label', 'wpsso' );
_x( 'YOURLS Password', 'option label', 'wpsso' );
_x( 'YOURLS Token', 'option label', 'wpsso' );
_x( 'Ratings and Reviews Service', 'option label', 'wpsso' );
_x( 'Maximum Number of Reviews', 'option label', 'wpsso' );
_x( 'Maximum Age of Reviews', 'option label', 'wpsso' );
_x( 'months', 'option comment', 'wpsso' );
_x( 'Get Reviews for Post Types', 'option label', 'wpsso' );
_x( 'Shopper Approved (Ratings and Reviews)', 'metabox title', 'wpsso' );
_x( 'Shopper Approved Site ID', 'option label', 'wpsso' );
_x( 'Shopper Approved API Token', 'option label', 'wpsso' );
_x( 'Stamped.io (Ratings and Reviews)', 'metabox title', 'wpsso' );
_x( 'Stamped.io Store Hash', 'option label', 'wpsso' );
_x( 'Stamped.io API Key Public', 'option label', 'wpsso' );
_x( 'Type for Page Homepage', 'option label', 'wpsso' );
_x( 'Type for Posts Homepage', 'option label', 'wpsso' );
_x( 'Type for User Profiles', 'option label', 'wpsso' );
_x( 'Type for Search Results', 'option label', 'wpsso' );
_x( 'Type for Archive Page', 'option label', 'wpsso' );
_x( 'for %s', 'option comment', 'wpsso' );
_x( 'Type by Post Type', 'option label', 'wpsso' );
_x( 'for %s', 'option comment', 'wpsso' );
_x( 'Type by Post Type Archive', 'option label', 'wpsso' );
_x( 'for %s', 'option comment', 'wpsso' );
_x( 'Type by Taxonomy', 'option label', 'wpsso' );
_x( 'Type for Page Homepage', 'option label', 'wpsso' );
_x( 'Type for Posts Homepage', 'option label', 'wpsso' );
_x( 'Type for User Profiles', 'option label', 'wpsso' );
_x( 'Type for Search Results', 'option label', 'wpsso' );
_x( 'Type for Archive Page', 'option label', 'wpsso' );
_x( 'for %s', 'option comment', 'wpsso' );
_x( 'Type by Post Type', 'option label', 'wpsso' );
_x( 'for %s', 'option comment', 'wpsso' );
_x( 'Type by Post Type Archive', 'option label', 'wpsso' );
_x( 'for %s', 'option comment', 'wpsso' );
_x( 'Type by Taxonomy', 'option label', 'wpsso' );
_x( 'Default Article Section', 'option label', 'wpsso' );
_x( 'Default Book Format', 'option label', 'wpsso' );
_x( 'Default Family Friendly', 'option label', 'wpsso' );
_x( 'Default Publisher Organization', 'option label', 'wpsso' );
_x( 'Default Publisher Person', 'option label', 'wpsso' );
_x( 'Default Service Provider Org.', 'option label', 'wpsso' );
_x( 'Default Service Provider Person', 'option label', 'wpsso' );
_x( 'Default Event Attendance', 'option label', 'wpsso' );
_x( 'Default Event Venue', 'option label', 'wpsso' );
_x( 'Default Event Organizer Org.', 'option label', 'wpsso' );
_x( 'Default Event Organizer Person', 'option label', 'wpsso' );
_x( 'Default Event Performer Org.', 'option label', 'wpsso' );
_x( 'Default Event Performer Person', 'option label', 'wpsso' );
_x( 'Default Job Hiring Organization', 'option label', 'wpsso' );
_x( 'Default Job Location', 'option label', 'wpsso' );
_x( 'Default Job Location Type', 'option label', 'wpsso' );
_x( 'Default Place Schema Type', 'option label', 'wpsso' );
_x( 'Default Place Country', 'option label', 'wpsso' );
_x( 'Default Place Timezone', 'option label', 'wpsso' );
_x( 'Default Product Return Policy', 'option label', 'wpsso' );
_x( 'Default Product Google Category', 'option label', 'wpsso' );
_x( 'Default Product Price Type', 'option label', 'wpsso' );
_x( 'Default Product Condition', 'option label', 'wpsso' );
_x( 'Default Product Energy Rating Range', 'option label', 'wpsso' );
_x( 'to', 'option comment', 'wpsso' );
_x( 'Default Product Target Gender', 'option label', 'wpsso' );
_x( 'Default Product Size Group', 'option label', 'wpsso' );
_x( 'Default Product Size System', 'option label', 'wpsso' );
_x( 'Default Product Age Group', 'option label', 'wpsso' );
_x( 'Default Product Adult Type', 'option label', 'wpsso' );
_x( 'Default Subject Schema Type', 'option label', 'wpsso' );
_x( 'Show', 'column title', 'wpsso' );
_x( 'Contact Field ID', 'column title', 'wpsso' );
_x( 'Contact Field Label', 'column title', 'wpsso' );
_x( 'Show', 'column title', 'wpsso' );
_x( 'Contact Field ID', 'column title', 'wpsso' );
_x( 'Contact Field Label', 'column title', 'wpsso' );
_x( 'Show', 'column title', 'wpsso' );
__( 'An SEO plugin has been detected - some basic SEO meta tags have been unchecked and disabled automatically.', 'wpsso' );
_x( 'Inherit Featured Image', 'option label', 'wpsso' );
_x( '(recommended)', 'option comment', 'wpsso' );
_x( 'Inherit Custom Images', 'option label', 'wpsso' );
_x( '(recommended)', 'option comment', 'wpsso' );
_x( 'Image Dimension Checks', 'option label', 'wpsso' );
_x( '(recommended)', 'option comment', 'wpsso' );
_x( 'Prevent Thumbnail Conflicts', 'option label', 'wpsso' );
_x( '(recommended)', 'option comment', 'wpsso' );
_x( 'Upscale Media Library Images', 'option label', 'wpsso' );
_x( 'Gravatar is Default Author Image', 'option label', 'wpsso' );
_x( 'Maximum Videos to Include', 'option label', 'wpsso' );
_x( 'Include Video Preview Images', 'option label', 'wpsso' );
_x( 'Force Autoplay when Possible', 'option label', 'wpsso' );
_x( 'Check for Embedded Media', 'option label', 'wpsso' );
_x( 'Priority Video Information', 'metabox title', 'wpsso' );
_x( 'Video Embed HTML', 'option label', 'wpsso' );
_x( 'or a Video URL', 'option label', 'wpsso' );
_x( 'Video Information from Video API', 'metabox title', 'wpsso' );
_x( 'Video Name', 'option label', 'wpsso' );
_x( 'Video Description', 'option label', 'wpsso' );
_x( 'Video Stream URL', 'option label', 'wpsso' );
_x( 'Video Dimensions', 'option label', 'wpsso' );
_x( 'Schema Book Information', 'metabox title', 'wpsso' );
_x( 'Book Author Type', 'option label', 'wpsso' );
_x( 'Book Author Name', 'option label', 'wpsso' );
_x( 'Book Author URL', 'option label', 'wpsso' );
_x( 'Book Published Date', 'option label', 'wpsso' );
_x( 'Book Created Date', 'option label', 'wpsso' );
_x( 'Book Edition', 'option label', 'wpsso' );
_x( 'Book Format', 'option label', 'wpsso' );
_x( 'Number of Pages', 'option label', 'wpsso' );
_x( 'Book ISBN', 'option label', 'wpsso' );
_x( 'Schema Audiobook Information', 'metabox title', 'wpsso' );
_x( 'Audiobook Duration', 'option label', 'wpsso' );
_x( 'Schema Movie Information', 'metabox title', 'wpsso' );
_x( 'Movie Cast Names', 'option label', 'wpsso' );
_x( 'Movie Director Names', 'option label', 'wpsso' );
_x( 'Production Company', 'option label', 'wpsso' );
_x( 'Movie Release Date', 'option label', 'wpsso' );
_x( 'Movie Runtime', 'option label', 'wpsso' );
_x( 'Schema Review Information', 'metabox title', 'wpsso' );
_x( 'Review Rating', 'option label', 'wpsso' );
_x( 'from', 'option comment', 'wpsso' );
_x( 'to', 'option comment', 'wpsso' );
_x( 'Rating Value Name', 'option label', 'wpsso' );
_x( 'Review Subject Information', 'metabox title', 'wpsso' );
_x( 'Subject Name', 'option label', 'wpsso' );
_x( 'Subject Description', 'option label', 'wpsso' );
_x( 'Subject Image ID', 'option label', 'wpsso' );
_x( 'or an Image URL', 'option label', 'wpsso' );
_x( 'Subject Webpage URL', 'option label', 'wpsso' );
_x( 'Subject Same-As URLs', 'option label', 'wpsso' );
_x( 'Subject Schema Type', 'option label', 'wpsso' );
_x( 'Subject Author Type', 'option label', 'wpsso' );
_x( 'Subject Author Name', 'option label', 'wpsso' );
_x( 'Subject Author URL', 'option label', 'wpsso' );
_x( 'Subject Published Date', 'option label', 'wpsso' );
_x( 'Subject Created Date', 'option label', 'wpsso' );
_x( 'Subject Book ISBN', 'option label', 'wpsso' );
_x( 'Movie Cast Names', 'option label', 'wpsso' );
_x( 'Movie Director Names', 'option label', 'wpsso' );
_x( 'Operating System', 'option label', 'wpsso' );
_x( 'Application Category', 'option label', 'wpsso' );
_x( 'Software App Offers', 'option label', 'wpsso' );
_x( 'Software App Offer Name', 'option label', 'wpsso' );
_x( 'Software App Offer Price', 'option label', 'wpsso' );
_x( 'Software App Offer Currency', 'option label', 'wpsso' );
_x( 'Software App Offer Availability', 'option label', 'wpsso' );
_x( 'Subject Street Address', 'option label', 'wpsso' );
_x( 'Subject P.O. Box Number', 'option label', 'wpsso' );
_x( 'Subject City / Locality', 'option label', 'wpsso' );
_x( 'Subject State / Province', 'option label', 'wpsso' );
_x( 'Subject Zip / Postal Code', 'option label', 'wpsso' );
_x( 'Subject Country', 'option label', 'wpsso' );
_x( 'Subject Telephone', 'option label', 'wpsso' );
_x( 'Subject Price Range', 'option label', 'wpsso' );
_x( 'Subject Serves Cuisine', 'option label', 'wpsso' );
_x( 'Subject Product Brand', 'option label', 'wpsso' );
_x( 'Subject Product Offers', 'option label', 'wpsso' );
_x( 'Product Offer Name', 'option label', 'wpsso' );
_x( 'Product Offer Price', 'option label', 'wpsso' );
_x( 'Product Offer Currency', 'option label', 'wpsso' );
_x( 'Product Offer Availability', 'option label', 'wpsso' );
_x( 'Subject Product SKU', 'option label', 'wpsso' );
_x( 'Subject Product MPN', 'option label', 'wpsso' );
_x( 'Schema Claim Review Information', 'metabox title', 'wpsso' );
_x( 'Short Summary of Claim', 'option label', 'wpsso' );
_x( 'First Appearance URL', 'option label', 'wpsso' );
_x( 'Schema Software App Information', 'metabox title', 'wpsso' );
_x( 'Operating System', 'option label', 'wpsso' );
_x( 'Application Category', 'option label', 'wpsso' );
_x( 'Schema QA Page Information', 'metabox title', 'wpsso' );
_x( 'QA Heading', 'option label', 'wpsso' );
_x( 'Schema Event Information', 'metabox title', 'wpsso' );
_x( 'Event Language', 'option label', 'wpsso' );
_x( 'Event Attendance', 'option label', 'wpsso' );
_x( 'Event Online URL', 'option label', 'wpsso' );
_x( 'Event Venue', 'option label', 'wpsso' );
_x( 'Organizer Org.', 'option label', 'wpsso' );
_x( 'Organizer Person', 'option label', 'wpsso' );
_x( 'Performer Org.', 'option label', 'wpsso' );
_x( 'Performer Person', 'option label', 'wpsso' );
_x( 'Event Status', 'option label', 'wpsso' );
_x( 'Event Start', 'option label', 'wpsso' );
_x( 'Event End', 'option label', 'wpsso' );
_x( 'Event Previous Start', 'option label', 'wpsso' );
_x( 'Event Offers Start', 'option label', 'wpsso' );
_x( 'Event Offers End', 'option label', 'wpsso' );
_x( 'Event Offers', 'option label', 'wpsso' );
_x( 'Event Offer Name', 'option label', 'wpsso' );
_x( 'Event Offer Price', 'option label', 'wpsso' );
_x( 'Event Offer Currency', 'option label', 'wpsso' );
_x( 'Event Offer Availability', 'option label', 'wpsso' );
_x( 'Schema Job Posting Information', 'metabox title', 'wpsso' );
_x( 'Job Title', 'option label', 'wpsso' );
_x( 'Hiring Organization', 'option label', 'wpsso' );
_x( 'Job Location', 'option label', 'wpsso' );
_x( 'Job Location Type', 'option label', 'wpsso' );
_x( 'Base Salary', 'option label', 'wpsso' );
_x( 'per', 'option comment', 'wpsso' );
_x( 'Employment Type', 'option label', 'wpsso' );
_x( 'Job Posting Expires', 'option label', 'wpsso' );
_x( 'Schema Organization Information', 'metabox title', 'wpsso' );
_x( 'Select an Organization', 'option label', 'wpsso' );
_x( 'Schema Person Information', 'metabox title', 'wpsso' );
_x( 'Select a Person', 'option label', 'wpsso' );
_x( 'Schema Place Information', 'metabox title', 'wpsso' );
_x( 'Select a Place', 'option label', 'wpsso' );
_x( 'Schema Product Information (Main Product)', 'metabox title', 'wpsso' );
_x( 'Product Return Policy', 'option label', 'wpsso' );
_x( 'Product Google Category', 'option label', 'wpsso' );
_x( 'Product Brand', 'option label', 'wpsso' );
_x( 'Product Price', 'option label', 'wpsso' );
_x( 'Product Price Type', 'option label', 'wpsso' );
_x( 'Product Min Advert Price', 'option label', 'wpsso' );
_x( 'Product Availability', 'option label', 'wpsso' );
_x( 'Product Condition', 'option label', 'wpsso' );
_x( 'Product Energy Rating', 'option label', 'wpsso' );
_x( 'from', 'option comment', 'wpsso' );
_x( 'to', 'option comment', 'wpsso' );
_x( 'Product Material', 'option label', 'wpsso' );
_x( 'Product Pattern', 'option label', 'wpsso' );
_x( 'Product Color', 'option label', 'wpsso' );
_x( 'Product Target Gender', 'option label', 'wpsso' );
_x( 'Product Size', 'option label', 'wpsso' );
_x( 'Product Size Group', 'option label', 'wpsso' );
_x( 'Product Size System', 'option label', 'wpsso' );
_x( 'Product Age Group', 'option label', 'wpsso' );
_x( 'Product Adult Type', 'option label', 'wpsso' );
_x( 'Product Net Len. / Depth', 'option label', 'wpsso' );
_x( 'Product Net Width', 'option label', 'wpsso' );
_x( 'Product Net Height', 'option label', 'wpsso' );
_x( 'Product Net Weight', 'option label', 'wpsso' );
_x( 'Product Fluid Volume', 'option label', 'wpsso' );
_x( 'Product Shipping Length', 'option label', 'wpsso' );
_x( 'Product Shipping Width', 'option label', 'wpsso' );
_x( 'Product Shipping Height', 'option label', 'wpsso' );
_x( 'Product Shipping Weight', 'option label', 'wpsso' );
_x( 'Product SKU', 'option label', 'wpsso' );
_x( 'Product MPN', 'option label', 'wpsso' );
_x( 'Product GTIN-14', 'option label', 'wpsso' );
_x( 'Product GTIN-13 (EAN)', 'option label', 'wpsso' );
_x( 'Product GTIN-12 (UPC)', 'option label', 'wpsso' );
_x( 'Product GTIN-8', 'option label', 'wpsso' );
_x( 'Product GTIN', 'option label', 'wpsso' );
_x( 'Product ISBN', 'option label', 'wpsso' );
__( 'https://secure.php.net/manual/en/function.simplexml-load-string.php', 'wpsso' );
__( 'The <a href="%1$s">PHP %2$s function</a> is not available.', 'wpsso' );
__( 'Please contact your hosting provider to have the missing PHP function installed.', 'wpsso' );
__( 'https://secure.php.net/manual/en/function.simplexml-load-string.php', 'wpsso' );
__( 'The <a href="%1$s">PHP %2$s function</a> is not available.', 'wpsso' );
__( 'Please contact your hosting provider to have the missing PHP function installed.', 'wpsso' );
__( 'https://secure.php.net/manual/en/function.simplexml-load-string.php', 'wpsso' );
__( 'The <a href="%1$s">PHP %2$s function</a> is not available.', 'wpsso' );
__( 'Please contact your hosting provider to have the missing PHP function installed.', 'wpsso' );
__( 'Failed to upscale image ID %1$s of %2$s by %3$s from %4$s to %5$s for the %6$s image size (exceeds %7$s maximum upscale setting).', 'wpsso' );
__( 'Image ID %1$s of %2$s has been upscaled by %3$s from %4$s to %5$s for the %6$s image size.', 'wpsso' );
__( '%s error:', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'Bitly Generic Access Token', 'option label', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'DLMY.App API Key', 'option label', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'Ow.ly API Key', 'option label', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'YOURLS API URL', 'option label', 'wpsso' );
__( 'Loop detected: YOURLS API URL matches current URL (%s)', 'wpsso' );
__( 'Unable to instantiate the "%s" shortening service.', 'wpsso' );
__( '%s error:', 'wpsso' );
__( 'URL shortening library file for "%s" is missing and required.', 'wpsso' );
__( 'getting shopper approved ratings and reviews', 'wpsso' );
__( 'There has been a previous error connecting to %s for caching.', 'wpsso' );
__( 'Requests to retrieve and cache this URL are ignored for another %d second(s)', 'wpsso' );
__( 'getting stamp.io ratings and reviews', 'wpsso' );
__( 'There has been a previous error connecting to %s for caching.', 'wpsso' );
__( 'Requests to retrieve and cache this URL are ignored for another %d second(s)', 'wpsso' );
