<?php die( 'These aren\'t the droids you\'re looking for.' );
// 
// Extract of translatable strings from lib/com/education-levels.php.
// 
_x( '[generic]', 'option value', 'wpsso' );
_x( 'generic', 'option value', 'wpsso' );
_x( 'Beginner', 'option value', 'wpsso' );
_x( 'Intermediate', 'option value', 'wpsso' );
_x( 'Advanced', 'option value', 'wpsso' );
_x( 'Algeria', 'option value', 'wpsso' );
_x( 'Lower Secondary School (DZ)', 'option value', 'wpsso' );
_x( 'Lower Secondary School', 'option value', 'wpsso' );
_x( 'Grade 8 (DZ)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (DZ)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Upper Secondary School (DZ)', 'option value', 'wpsso' );
_x( 'Upper Secondary School', 'option value', 'wpsso' );
_x( 'Grade 10 (DZ)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (DZ)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (DZ)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (DZ)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Argentina', 'option value', 'wpsso' );
_x( 'Secondary (AR)', 'option value', 'wpsso' );
_x( 'Secondary', 'option value', 'wpsso' );
_x( '8th Grade (AR)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (AR)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade (AR)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (AR)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (AR)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (AR)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Australia', 'option value', 'wpsso' );
_x( 'Secondary School (AU)', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( 'Year 8 (AU)', 'option value', 'wpsso' );
_x( 'Year 8', 'option value', 'wpsso' );
_x( 'Year 9 (AU)', 'option value', 'wpsso' );
_x( 'Year 9', 'option value', 'wpsso' );
_x( 'Year 10 (AU)', 'option value', 'wpsso' );
_x( 'Year 10', 'option value', 'wpsso' );
_x( 'Senior Secondary School (AU)', 'option value', 'wpsso' );
_x( 'Senior Secondary School', 'option value', 'wpsso' );
_x( 'Year 11 (AU)', 'option value', 'wpsso' );
_x( 'Year 11', 'option value', 'wpsso' );
_x( 'Year 12 (AU)', 'option value', 'wpsso' );
_x( 'Year 12', 'option value', 'wpsso' );
_x( 'University (AU)', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Austria', 'option value', 'wpsso' );
_x( 'Upper Secondary Level (AT)', 'option value', 'wpsso' );
_x( 'Upper Secondary Level', 'option value', 'wpsso' );
_x( '9th Grade (AT)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade (AT)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (AT)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (AT)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Tertiary Level (AT)', 'option value', 'wpsso' );
_x( 'Tertiary Level', 'option value', 'wpsso' );
_x( 'Azerbaijan', 'option value', 'wpsso' );
_x( 'General Secondary Education (AZ)', 'option value', 'wpsso' );
_x( 'General Secondary Education', 'option value', 'wpsso' );
_x( '8th Grade (AZ)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (AZ)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Full Secondary Education (AZ)', 'option value', 'wpsso' );
_x( 'Full Secondary Education', 'option value', 'wpsso' );
_x( '10th Grade (AZ)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (AZ)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (AZ)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Bahrain', 'option value', 'wpsso' );
_x( 'Intermediate Stage (BH)', 'option value', 'wpsso' );
_x( 'Intermediate Stage', 'option value', 'wpsso' );
_x( 'Grade 8 (BH)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (BH)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Stage (BH)', 'option value', 'wpsso' );
_x( 'Secondary Stage', 'option value', 'wpsso' );
_x( 'Grade 10 (BH)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (BH)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (BH)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (BH)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Bangladesh', 'option value', 'wpsso' );
_x( 'Junior Secondary Education (BD)', 'option value', 'wpsso' );
_x( 'Junior Secondary Education', 'option value', 'wpsso' );
_x( 'Grade VIII (BD)', 'option value', 'wpsso' );
_x( 'Grade VIII', 'option value', 'wpsso' );
_x( 'Secondary Education (BD)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade IX (BD)', 'option value', 'wpsso' );
_x( 'Grade IX', 'option value', 'wpsso' );
_x( 'Grade X (BD)', 'option value', 'wpsso' );
_x( 'Grade X', 'option value', 'wpsso' );
_x( 'Higher Secondary Education (BD)', 'option value', 'wpsso' );
_x( 'Higher Secondary Education', 'option value', 'wpsso' );
_x( 'Grade XI (BD)', 'option value', 'wpsso' );
_x( 'Grade XI', 'option value', 'wpsso' );
_x( 'Grade XII (BD)', 'option value', 'wpsso' );
_x( 'Grade XII', 'option value', 'wpsso' );
_x( 'Tertiary Education (BD)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Belarus', 'option value', 'wpsso' );
_x( 'Compulsory Basic Education (BY)', 'option value', 'wpsso' );
_x( 'Compulsory Basic Education', 'option value', 'wpsso' );
_x( 'Grade 8 (BY)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (BY)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'General Upper Secondary Education (BY)', 'option value', 'wpsso' );
_x( 'General Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (BY)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (BY)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (BY)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (BY)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Belgium', 'option value', 'wpsso' );
_x( 'Secondary Education (BE)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '2nd Secondary (BE)', 'option value', 'wpsso' );
_x( '2nd Secondary', 'option value', 'wpsso' );
_x( '3rd Secondary (BE)', 'option value', 'wpsso' );
_x( '3rd Secondary', 'option value', 'wpsso' );
_x( '4th Secondary (BE)', 'option value', 'wpsso' );
_x( '4th Secondary', 'option value', 'wpsso' );
_x( '5th Secondary (BE)', 'option value', 'wpsso' );
_x( '5th Secondary', 'option value', 'wpsso' );
_x( '6th Secondary (BE)', 'option value', 'wpsso' );
_x( '6th Secondary', 'option value', 'wpsso' );
_x( 'Higher Education (BE)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Bolivia', 'option value', 'wpsso' );
_x( 'Lower Secondary Education (BO)', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( '8th Grade (BO)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (BO)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '9th Grade (BO)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade (BO)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (BO)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (BO)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (BO)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Bosnia and Herzegovina', 'option value', 'wpsso' );
_x( 'Primary Education (BA)', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 8 (BA)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (BA)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education (BA)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (BA)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (BA)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (BA)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Grade 13 (BA)', 'option value', 'wpsso' );
_x( 'Grade 13', 'option value', 'wpsso' );
_x( 'Tertiary Education (BA)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Brazil', 'option value', 'wpsso' );
_x( 'Elementary School (BR)', 'option value', 'wpsso' );
_x( 'Elementary School', 'option value', 'wpsso' );
_x( '8th Grade (BR)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( 'High School (BR)', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( '1st grade (High School) (BR)', 'option value', 'wpsso' );
_x( '1st grade', 'option value', 'wpsso' );
_x( '2nd grade (High School) (BR)', 'option value', 'wpsso' );
_x( '2nd grade', 'option value', 'wpsso' );
_x( '3rd grade (High School) (BR)', 'option value', 'wpsso' );
_x( '3rd grade', 'option value', 'wpsso' );
_x( 'Higher Education (BR)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Bulgaria', 'option value', 'wpsso' );
_x( 'Secondary Education (BG)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '10th Grade (BG)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (BG)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (BG)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (BG)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Canada', 'option value', 'wpsso' );
_x( 'Intermediate Education (CA)', 'option value', 'wpsso' );
_x( 'Intermediate Education', 'option value', 'wpsso' );
_x( 'Grade 8 (CA)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (CA)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education (CA)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (CA)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (CA)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (CA)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education (CA)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Chile', 'option value', 'wpsso' );
_x( 'Secondary Education (CL)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '9th Grade (CL)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade (CL)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (CL)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (CL)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (CL)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Colombia', 'option value', 'wpsso' );
_x( 'Basic Secondary (CO)', 'option value', 'wpsso' );
_x( 'Basic Secondary', 'option value', 'wpsso' );
_x( '9th Grade (CO)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'High School Education (CO)', 'option value', 'wpsso' );
_x( 'High School Education', 'option value', 'wpsso' );
_x( '10th Grade (CO)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (CO)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( 'Tertiary (CO)', 'option value', 'wpsso' );
_x( 'Tertiary', 'option value', 'wpsso' );
_x( 'Costa Rica', 'option value', 'wpsso' );
_x( 'Secondary Education (CR)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Eighth Grade (CR)', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade (CR)', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Tenth Grade (CR)', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade (CR)', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade (CR)', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Higher Education (CR)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Croatia', 'option value', 'wpsso' );
_x( 'Secondary education (HR)', 'option value', 'wpsso' );
_x( 'Secondary education', 'option value', 'wpsso' );
_x( '10th Grade (HR)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (HR)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (HR)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (HR)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Cyprus', 'option value', 'wpsso' );
_x( 'Secondary Education (CY)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 9 (CY)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (CY)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (CY)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (CY)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (CY)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Czechia', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (CZ)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (CZ)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (CZ)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (CZ)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (CZ)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Denmark', 'option value', 'wpsso' );
_x( 'Secondary Education (DK)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '8th Grade (DK)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (DK)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade (DK)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (DK)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '11th Grade (DK)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (DK)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (DK)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Dominican Republic', 'option value', 'wpsso' );
_x( 'Primary School (DO)', 'option value', 'wpsso' );
_x( 'Primary School', 'option value', 'wpsso' );
_x( 'Grade 8 (DO)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Secondary School (DO)', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( 'Grade 1 (Secondary School) (DO)', 'option value', 'wpsso' );
_x( 'Grade 1', 'option value', 'wpsso' );
_x( 'Grade 2 (Secondary School) (DO)', 'option value', 'wpsso' );
_x( 'Grade 2', 'option value', 'wpsso' );
_x( 'Grade 3 (Secondary School) (DO)', 'option value', 'wpsso' );
_x( 'Grade 3', 'option value', 'wpsso' );
_x( 'Grade 4 (Secondary School) (DO)', 'option value', 'wpsso' );
_x( 'Grade 4', 'option value', 'wpsso' );
_x( 'Higher Education (DO)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Doctorate (DO)', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Ecuador', 'option value', 'wpsso' );
_x( 'Secondary (EC)', 'option value', 'wpsso' );
_x( 'Secondary', 'option value', 'wpsso' );
_x( 'Eighth Grade (EC)', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade (EC)', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Tenth Grade (EC)', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade (EC)', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade (EC)', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education (EC)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Egypt', 'option value', 'wpsso' );
_x( 'Preparatory Stage (EG)', 'option value', 'wpsso' );
_x( 'Preparatory Stage', 'option value', 'wpsso' );
_x( 'Grade 8 (EG)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (EG)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education (EG)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (EG)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (EG)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (EG)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (EG)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'El Salvador', 'option value', 'wpsso' );
_x( '3rd Cycle (SV)', 'option value', 'wpsso' );
_x( '3rd Cycle', 'option value', 'wpsso' );
_x( '7th Grade (SV)', 'option value', 'wpsso' );
_x( '7th Grade', 'option value', 'wpsso' );
_x( '8th Grade (SV)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (SV)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Middle Education (SV)', 'option value', 'wpsso' );
_x( 'Middle Education', 'option value', 'wpsso' );
_x( '10th Grade (SV)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (SV)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (SV)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'England', 'option value', 'wpsso' );
_x( 'Key Stage 3 (GB-ENG)', 'option value', 'wpsso' );
_x( 'Key Stage 3', 'option value', 'wpsso' );
_x( 'Year 9 (GB-ENG)', 'option value', 'wpsso' );
_x( 'Year 9', 'option value', 'wpsso' );
_x( 'Key Stage 4 (GB-ENG)', 'option value', 'wpsso' );
_x( 'Key Stage 4', 'option value', 'wpsso' );
_x( 'Year 10 (GB-ENG)', 'option value', 'wpsso' );
_x( 'Year 10', 'option value', 'wpsso' );
_x( 'Year 11 (GB-ENG)', 'option value', 'wpsso' );
_x( 'Year 11', 'option value', 'wpsso' );
_x( 'Key Stage 5 (GB-ENG)', 'option value', 'wpsso' );
_x( 'Key Stage 5', 'option value', 'wpsso' );
_x( 'Year 12 (GB-ENG)', 'option value', 'wpsso' );
_x( 'Year 12', 'option value', 'wpsso' );
_x( 'Year 13 (GB-ENG)', 'option value', 'wpsso' );
_x( 'Year 13', 'option value', 'wpsso' );
_x( 'Higher Education (GB-ENG)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Estonia', 'option value', 'wpsso' );
_x( 'Basic Education (EE)', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( '7th Grade (EE)', 'option value', 'wpsso' );
_x( '7th Grade', 'option value', 'wpsso' );
_x( '8th Grade (EE)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (EE)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Secondary Education (EE)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '10th Grade (EE)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (EE)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (EE)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (EE)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Finland', 'option value', 'wpsso' );
_x( 'Basic Education (FI)', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( '7th Grade (FI)', 'option value', 'wpsso' );
_x( '7th Grade', 'option value', 'wpsso' );
_x( '8th Grade (FI)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (FI)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (FI)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '10th Grade (FI)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (FI)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (FI)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (FI)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'France', 'option value', 'wpsso' );
_x( 'Lycée (FR)', 'option value', 'wpsso' );
_x( 'Lycée', 'option value', 'wpsso' );
_x( 'Seconde (FR)', 'option value', 'wpsso' );
_x( 'Seconde', 'option value', 'wpsso' );
_x( 'Première (FR)', 'option value', 'wpsso' );
_x( 'Première', 'option value', 'wpsso' );
_x( 'Terminale (FR)', 'option value', 'wpsso' );
_x( 'Terminale', 'option value', 'wpsso' );
_x( 'Georgia', 'option value', 'wpsso' );
_x( 'Basic Education (GE)', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( 'Grade 8 (GE)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (GE)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education (GE)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (GE)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (GE)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (GE)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education (GE)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Germany', 'option value', 'wpsso' );
_x( 'Gymnasium (DE)', 'option value', 'wpsso' );
_x( 'Gymnasium', 'option value', 'wpsso' );
_x( '11th Grade (Gymnasium) (DE)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (Gymnasium) (DE)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( '13th Grade (Gymnasium) (DE)', 'option value', 'wpsso' );
_x( '13th Grade', 'option value', 'wpsso' );
_x( 'University (DE)', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Ghana', 'option value', 'wpsso' );
_x( 'Junior Secodary School (GH)', 'option value', 'wpsso' );
_x( 'Junior Secodary School', 'option value', 'wpsso' );
_x( 'Grade 8 (GH)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (GH)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Senior Secondary School (GH)', 'option value', 'wpsso' );
_x( 'Senior Secondary School', 'option value', 'wpsso' );
_x( 'Grade 10 (GH)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (GH)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (GH)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (GH)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Greece', 'option value', 'wpsso' );
_x( 'Upper Secondary School (GR)', 'option value', 'wpsso' );
_x( 'Upper Secondary School', 'option value', 'wpsso' );
_x( '1st Grade (Lyceum) (GR)', 'option value', 'wpsso' );
_x( '1st Grade', 'option value', 'wpsso' );
_x( '2nd Grade (Lyceum) (GR)', 'option value', 'wpsso' );
_x( '2nd Grade', 'option value', 'wpsso' );
_x( '3rd Grade (Lyceum) (GR)', 'option value', 'wpsso' );
_x( '3rd Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education (GR)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Guatemala', 'option value', 'wpsso' );
_x( 'Lower Secondary (GT)', 'option value', 'wpsso' );
_x( 'Lower Secondary', 'option value', 'wpsso' );
_x( 'Grade 7 (GT)', 'option value', 'wpsso' );
_x( 'Grade 7', 'option value', 'wpsso' );
_x( 'Grade 8 (GT)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (GT)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Upper Secondary (GT)', 'option value', 'wpsso' );
_x( 'Upper Secondary', 'option value', 'wpsso' );
_x( 'Grade 10 (GT)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (GT)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (GT)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (GT)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Honduras', 'option value', 'wpsso' );
_x( 'Lower Secondary Education (HN)', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( '8th Grade (HN)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (HN)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (HN)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '10th Grade (HN)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (HN)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (HN)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education (HN)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Hong Kong', 'option value', 'wpsso' );
_x( 'Junior Secondary (HK)', 'option value', 'wpsso' );
_x( 'Junior Secondary', 'option value', 'wpsso' );
_x( 'Secondary 2 (HK)', 'option value', 'wpsso' );
_x( 'Secondary 2', 'option value', 'wpsso' );
_x( 'Secondary 3 (HK)', 'option value', 'wpsso' );
_x( 'Secondary 3', 'option value', 'wpsso' );
_x( 'Senior Secondary (HK)', 'option value', 'wpsso' );
_x( 'Senior Secondary', 'option value', 'wpsso' );
_x( 'Secondary 4 (HK)', 'option value', 'wpsso' );
_x( 'Secondary 4', 'option value', 'wpsso' );
_x( 'Secondary 5 (HK)', 'option value', 'wpsso' );
_x( 'Secondary 5', 'option value', 'wpsso' );
_x( 'Secondary 6 (HK)', 'option value', 'wpsso' );
_x( 'Secondary 6', 'option value', 'wpsso' );
_x( 'University (HK)', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Hungary', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (HU)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '11th Grade (HU)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (HU)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( '13th Grade (HU)', 'option value', 'wpsso' );
_x( '13th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (HU)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Iceland', 'option value', 'wpsso' );
_x( 'Primary Education (IS)', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 8 (IS)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (IS)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (IS)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (IS)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '11th Grade (IS)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (IS)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( '13th Grade (IS)', 'option value', 'wpsso' );
_x( '13th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (IS)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'India', 'option value', 'wpsso' );
_x( 'Middle Stage (IN)', 'option value', 'wpsso' );
_x( 'Middle Stage', 'option value', 'wpsso' );
_x( 'Class 8 (IN)', 'option value', 'wpsso' );
_x( 'Class 8', 'option value', 'wpsso' );
_x( 'Secondary School (IN)', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( 'Class 9 (IN)', 'option value', 'wpsso' );
_x( 'Class 9', 'option value', 'wpsso' );
_x( 'Class 10 (IN)', 'option value', 'wpsso' );
_x( 'Class 10', 'option value', 'wpsso' );
_x( 'Senior Secondary School (IN)', 'option value', 'wpsso' );
_x( 'Senior Secondary School', 'option value', 'wpsso' );
_x( 'Class 11 (IN)', 'option value', 'wpsso' );
_x( 'Class 11', 'option value', 'wpsso' );
_x( 'Class 12 (IN)', 'option value', 'wpsso' );
_x( 'Class 12', 'option value', 'wpsso' );
_x( 'Undergraduate college (IN)', 'option value', 'wpsso' );
_x( 'Undergraduate college', 'option value', 'wpsso' );
_x( 'Post-graduate college (IN)', 'option value', 'wpsso' );
_x( 'Post-graduate college', 'option value', 'wpsso' );
_x( 'Indonesia', 'option value', 'wpsso' );
_x( 'Middle School (ID)', 'option value', 'wpsso' );
_x( 'Middle School', 'option value', 'wpsso' );
_x( '8th Grade (ID)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (ID)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'High School (ID)', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( '10th Grade (ID)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (ID)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (ID)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education (ID)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Iraq', 'option value', 'wpsso' );
_x( 'Intermediate Education (IQ)', 'option value', 'wpsso' );
_x( 'Intermediate Education', 'option value', 'wpsso' );
_x( 'Eighth Grade (IQ)', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade (IQ)', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Preparatory Education (IQ)', 'option value', 'wpsso' );
_x( 'Preparatory Education', 'option value', 'wpsso' );
_x( 'Tenth Grade (IQ)', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade (IQ)', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade (IQ)', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Higher Education (IQ)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Ireland', 'option value', 'wpsso' );
_x( 'Senior Cycle (IE)', 'option value', 'wpsso' );
_x( 'Senior Cycle', 'option value', 'wpsso' );
_x( 'Transition Year (IE)', 'option value', 'wpsso' );
_x( 'Transition Year', 'option value', 'wpsso' );
_x( 'Fifth Year (IE)', 'option value', 'wpsso' );
_x( 'Fifth Year', 'option value', 'wpsso' );
_x( 'Sixth Year (IE)', 'option value', 'wpsso' );
_x( 'Sixth Year', 'option value', 'wpsso' );
_x( 'University (IE)', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Israel', 'option value', 'wpsso' );
_x( 'Intermediate School (IL)', 'option value', 'wpsso' );
_x( 'Intermediate School', 'option value', 'wpsso' );
_x( 'Grade 8 (IL)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (IL)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary School (IL)', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( 'Grade 10 (IL)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (IL)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (IL)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'University (IL)', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Doctorate (IL)', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Italy', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (IT)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '2nd upper (IT)', 'option value', 'wpsso' );
_x( '2nd upper', 'option value', 'wpsso' );
_x( '3rd upper (IT)', 'option value', 'wpsso' );
_x( '3rd upper', 'option value', 'wpsso' );
_x( '4th upper (IT)', 'option value', 'wpsso' );
_x( '4th upper', 'option value', 'wpsso' );
_x( '5th upper (IT)', 'option value', 'wpsso' );
_x( '5th upper', 'option value', 'wpsso' );
_x( 'Higher Education (IT)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Jamaica', 'option value', 'wpsso' );
_x( 'Secondary Education (JM)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8 (JM)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (JM)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (JM)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (JM)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (JM)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education (JM)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Japan', 'option value', 'wpsso' );
_x( 'Lower Secondary School (JP)', 'option value', 'wpsso' );
_x( 'Lower Secondary School', 'option value', 'wpsso' );
_x( 'Grade 2 (lower secondary) (JP)', 'option value', 'wpsso' );
_x( 'Grade 2', 'option value', 'wpsso' );
_x( 'Grade 3 (lower secondary) (JP)', 'option value', 'wpsso' );
_x( 'Grade 3', 'option value', 'wpsso' );
_x( 'Upper Secondary School (JP)', 'option value', 'wpsso' );
_x( 'Upper Secondary School', 'option value', 'wpsso' );
_x( 'Grade 1 (upper secondary) (JP)', 'option value', 'wpsso' );
_x( 'Grade 1', 'option value', 'wpsso' );
_x( 'Grade 2 (upper secondary) (JP)', 'option value', 'wpsso' );
_x( 'Grade 2', 'option value', 'wpsso' );
_x( 'Grade 3 (upper secondary) (JP)', 'option value', 'wpsso' );
_x( 'Grade 3', 'option value', 'wpsso' );
_x( 'Higher Education (JP)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Jordan', 'option value', 'wpsso' );
_x( 'Basic Education (JO)', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( 'Grade 8 (JO)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (JO)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (JO)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Secondary Education (JO)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 11 (JO)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (JO)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (JO)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Doctorate (JO)', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Kazakhstan', 'option value', 'wpsso' );
_x( 'Lower Secondary School (KZ)', 'option value', 'wpsso' );
_x( 'Lower Secondary School', 'option value', 'wpsso' );
_x( 'Grade 7 (KZ)', 'option value', 'wpsso' );
_x( 'Grade 7', 'option value', 'wpsso' );
_x( 'Grade 8 (KZ)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (KZ)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Upper Secondary School (KZ)', 'option value', 'wpsso' );
_x( 'Upper Secondary School', 'option value', 'wpsso' );
_x( 'Grade 10 (KZ)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (KZ)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Tertiary Institutions (KZ)', 'option value', 'wpsso' );
_x( 'Tertiary Institutions', 'option value', 'wpsso' );
_x( 'Kenya', 'option value', 'wpsso' );
_x( 'Upper Primary (KE)', 'option value', 'wpsso' );
_x( 'Upper Primary', 'option value', 'wpsso' );
_x( 'Standard 8 (KE)', 'option value', 'wpsso' );
_x( 'Standard 8', 'option value', 'wpsso' );
_x( 'High School (KE)', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( 'Standard 9 (KE)', 'option value', 'wpsso' );
_x( 'Standard 9', 'option value', 'wpsso' );
_x( 'Standard 10 (KE)', 'option value', 'wpsso' );
_x( 'Standard 10', 'option value', 'wpsso' );
_x( 'Standard 11 (KE)', 'option value', 'wpsso' );
_x( 'Standard 11', 'option value', 'wpsso' );
_x( 'Standard 12 (KE)', 'option value', 'wpsso' );
_x( 'Standard 12', 'option value', 'wpsso' );
_x( 'Higher Education (KE)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Kuwait', 'option value', 'wpsso' );
_x( 'Intermediate Education (KW)', 'option value', 'wpsso' );
_x( 'Intermediate Education', 'option value', 'wpsso' );
_x( 'Grade 8 (KW)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (KW)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education (KW)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (KW)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (KW)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (KW)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (KW)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Latvia', 'option value', 'wpsso' );
_x( 'Primary Education (LV)', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 7 (LV)', 'option value', 'wpsso' );
_x( 'Grade 7', 'option value', 'wpsso' );
_x( 'Grade 8 (LV)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Senior Secondary Education (LV)', 'option value', 'wpsso' );
_x( 'Senior Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (LV)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (LV)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (LV)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (LV)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Lebanon', 'option value', 'wpsso' );
_x( 'Intermediate Level (LB)', 'option value', 'wpsso' );
_x( 'Intermediate Level', 'option value', 'wpsso' );
_x( 'Grade 8 (LB)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (LB)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education (LB)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (LB)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (LB)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (LB)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education (LB)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Libya', 'option value', 'wpsso' );
_x( 'Primary Education (LY)', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 8 (LY)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (LY)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education (LY)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (LY)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (LY)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (LY)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education (LY)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Liechtenstein', 'option value', 'wpsso' );
_x( 'Middle School (LI)', 'option value', 'wpsso' );
_x( 'Middle School', 'option value', 'wpsso' );
_x( '7th Grade (LI)', 'option value', 'wpsso' );
_x( '7th Grade', 'option value', 'wpsso' );
_x( '8th Grade (LI)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (LI)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'High School (LI)', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( '10th Grade (LI)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (LI)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (LI)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education (LI)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Lithuania', 'option value', 'wpsso' );
_x( 'Lower Secondary Education (LT)', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8 (LT)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (LT)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (LT)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (LT)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 11 (LT)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (LT)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (LT)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Luxembourg', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (LU)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '3 G (LU)', 'option value', 'wpsso' );
_x( '3 G', 'option value', 'wpsso' );
_x( '2 G (LU)', 'option value', 'wpsso' );
_x( '2 G', 'option value', 'wpsso' );
_x( '1 G (LU)', 'option value', 'wpsso' );
_x( '1 G', 'option value', 'wpsso' );
_x( 'Higher Education (LU)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Malaysia', 'option value', 'wpsso' );
_x( 'Secondary (MY)', 'option value', 'wpsso' );
_x( 'Secondary', 'option value', 'wpsso' );
_x( 'Form 2 (MY)', 'option value', 'wpsso' );
_x( 'Form 2', 'option value', 'wpsso' );
_x( 'Form 3 (MY)', 'option value', 'wpsso' );
_x( 'Form 3', 'option value', 'wpsso' );
_x( 'Form 4 (MY)', 'option value', 'wpsso' );
_x( 'Form 4', 'option value', 'wpsso' );
_x( 'Form 5 (MY)', 'option value', 'wpsso' );
_x( 'Form 5', 'option value', 'wpsso' );
_x( 'Pre-university (MY)', 'option value', 'wpsso' );
_x( 'Pre-university', 'option value', 'wpsso' );
_x( 'Lower Form 6 (MY)', 'option value', 'wpsso' );
_x( 'Lower Form 6', 'option value', 'wpsso' );
_x( 'Upper Form 6 (MY)', 'option value', 'wpsso' );
_x( 'Upper Form 6', 'option value', 'wpsso' );
_x( 'Post-secondary Education (MY)', 'option value', 'wpsso' );
_x( 'Post-secondary Education', 'option value', 'wpsso' );
_x( 'Malta', 'option value', 'wpsso' );
_x( 'Secondary Education (MT)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 9 (MT)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (MT)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (MT)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Post-Secondary Education (MT)', 'option value', 'wpsso' );
_x( 'Post-Secondary Education', 'option value', 'wpsso' );
_x( 'Tertiary Education (MT)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Postgraduate Education (MT)', 'option value', 'wpsso' );
_x( 'Postgraduate Education', 'option value', 'wpsso' );
_x( 'Mexico', 'option value', 'wpsso' );
_x( 'Lower Secondary Education (MX)', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8 (MX)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (MX)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (MX)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (MX)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (MX)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (MX)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education (MX)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Montenegro', 'option value', 'wpsso' );
_x( 'Primary Education (ME)', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 8 (ME)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (ME)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education (ME)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (ME)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (ME)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (ME)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Grade 13 (ME)', 'option value', 'wpsso' );
_x( 'Grade 13', 'option value', 'wpsso' );
_x( 'Higher Education (ME)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Morocco', 'option value', 'wpsso' );
_x( 'Lower Secondary (MA)', 'option value', 'wpsso' );
_x( 'Lower Secondary', 'option value', 'wpsso' );
_x( 'Grade 8 (MA)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (MA)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Upper Secondary (MA)', 'option value', 'wpsso' );
_x( 'Upper Secondary', 'option value', 'wpsso' );
_x( 'Grade 10 (MA)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (MA)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (MA)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary (MA)', 'option value', 'wpsso' );
_x( 'Tertiary', 'option value', 'wpsso' );
_x( 'Nepal', 'option value', 'wpsso' );
_x( 'Secondary (NP)', 'option value', 'wpsso' );
_x( 'Secondary', 'option value', 'wpsso' );
_x( 'Year 9 (NP)', 'option value', 'wpsso' );
_x( 'Year 9', 'option value', 'wpsso' );
_x( 'Year 10 (NP)', 'option value', 'wpsso' );
_x( 'Year 10', 'option value', 'wpsso' );
_x( 'Senior Higher Secondary (NP)', 'option value', 'wpsso' );
_x( 'Senior Higher Secondary', 'option value', 'wpsso' );
_x( 'Year 11 (NP)', 'option value', 'wpsso' );
_x( 'Year 11', 'option value', 'wpsso' );
_x( 'Year 12 (NP)', 'option value', 'wpsso' );
_x( 'Year 12', 'option value', 'wpsso' );
_x( 'Netherlands', 'option value', 'wpsso' );
_x( 'Secondary Education (NL)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '5th Year (HAVO) (NL)', 'option value', 'wpsso' );
_x( '5th Year', 'option value', 'wpsso' );
_x( 'Higher Education (NL)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'New Zealand', 'option value', 'wpsso' );
_x( 'Year 9-13 Secondary School (NZ)', 'option value', 'wpsso' );
_x( 'Year 9-13 Secondary School', 'option value', 'wpsso' );
_x( 'Year 9 (NZ)', 'option value', 'wpsso' );
_x( 'Year 9', 'option value', 'wpsso' );
_x( 'Year 10 (NZ)', 'option value', 'wpsso' );
_x( 'Year 10', 'option value', 'wpsso' );
_x( 'Year 11 (NZ)', 'option value', 'wpsso' );
_x( 'Year 11', 'option value', 'wpsso' );
_x( 'Year 12 (NZ)', 'option value', 'wpsso' );
_x( 'Year 12', 'option value', 'wpsso' );
_x( 'Year 13 (NZ)', 'option value', 'wpsso' );
_x( 'Year 13', 'option value', 'wpsso' );
_x( 'University (NZ)', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Doctorate (NZ)', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Nicaragua', 'option value', 'wpsso' );
_x( 'Lower Secondary Education (NI)', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8 (NI)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (NI)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Higher Secondary Education (NI)', 'option value', 'wpsso' );
_x( 'Higher Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (NI)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (NI)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Tertiary Education (NI)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Nigeria', 'option value', 'wpsso' );
_x( 'Junior Secondary Education (NG)', 'option value', 'wpsso' );
_x( 'Junior Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8 (NG)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (NG)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Senior Secondary Education (NG)', 'option value', 'wpsso' );
_x( 'Senior Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (NG)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (NG)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (NG)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'University (NG)', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Doctorate (NG)', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'North Macedonia', 'option value', 'wpsso' );
_x( 'Primary Education (MK)', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 7 (MK)', 'option value', 'wpsso' );
_x( 'Grade 7', 'option value', 'wpsso' );
_x( 'Grade 8 (MK)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Secondary Education (MK)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 9 (MK)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (MK)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (MK)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (MK)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (MK)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Northern Ireland', 'option value', 'wpsso' );
_x( 'Key Stage 3 (GB-NIR)', 'option value', 'wpsso' );
_x( 'Key Stage 3', 'option value', 'wpsso' );
_x( 'Year 10 (GB-NIR)', 'option value', 'wpsso' );
_x( 'Year 10', 'option value', 'wpsso' );
_x( 'Key Stage 4 (GB-NIR)', 'option value', 'wpsso' );
_x( 'Key Stage 4', 'option value', 'wpsso' );
_x( 'Year 11 (GB-NIR)', 'option value', 'wpsso' );
_x( 'Year 11', 'option value', 'wpsso' );
_x( 'Year 12 (GB-NIR)', 'option value', 'wpsso' );
_x( 'Year 12', 'option value', 'wpsso' );
_x( 'Key Stage 5 (GB-NIR)', 'option value', 'wpsso' );
_x( 'Key Stage 5', 'option value', 'wpsso' );
_x( 'Higher Education (GB-NIR)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Norway', 'option value', 'wpsso' );
_x( 'Lower Secondary School (NO)', 'option value', 'wpsso' );
_x( 'Lower Secondary School', 'option value', 'wpsso' );
_x( '8th Grade (NO)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (NO)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade (NO)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary School (NO)', 'option value', 'wpsso' );
_x( 'Upper Secondary School', 'option value', 'wpsso' );
_x( 'VG1 (NO)', 'option value', 'wpsso' );
_x( 'VG1', 'option value', 'wpsso' );
_x( 'VG2 (NO)', 'option value', 'wpsso' );
_x( 'VG2', 'option value', 'wpsso' );
_x( 'VG3 (NO)', 'option value', 'wpsso' );
_x( 'VG3', 'option value', 'wpsso' );
_x( 'Higher Education (NO)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Oman', 'option value', 'wpsso' );
_x( 'Basic Education (OM)', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( 'Grade 8 (OM)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (OM)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (OM)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Secondary Education (OM)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 11 (OM)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (OM)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (OM)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Doctorate (OM)', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Pakistan', 'option value', 'wpsso' );
_x( 'Middle School (PK)', 'option value', 'wpsso' );
_x( 'Middle School', 'option value', 'wpsso' );
_x( 'Class 8 (PK)', 'option value', 'wpsso' );
_x( 'Class 8', 'option value', 'wpsso' );
_x( 'High School (PK)', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( 'Class 9 (PK)', 'option value', 'wpsso' );
_x( 'Class 9', 'option value', 'wpsso' );
_x( 'Class 10 (PK)', 'option value', 'wpsso' );
_x( 'Class 10', 'option value', 'wpsso' );
_x( 'Higher Secondary School (PK)', 'option value', 'wpsso' );
_x( 'Higher Secondary School', 'option value', 'wpsso' );
_x( 'Class 11 (PK)', 'option value', 'wpsso' );
_x( 'Class 11', 'option value', 'wpsso' );
_x( 'Class 12 (PK)', 'option value', 'wpsso' );
_x( 'Class 12', 'option value', 'wpsso' );
_x( 'University (PK)', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Panama', 'option value', 'wpsso' );
_x( 'First Step of Secondary Level (PA)', 'option value', 'wpsso' );
_x( 'First Step of Secondary Level', 'option value', 'wpsso' );
_x( 'Grade Eight (PA)', 'option value', 'wpsso' );
_x( 'Grade Eight', 'option value', 'wpsso' );
_x( 'Grade Nine (PA)', 'option value', 'wpsso' );
_x( 'Grade Nine', 'option value', 'wpsso' );
_x( 'Second Step of Secondary Level (PA)', 'option value', 'wpsso' );
_x( 'Second Step of Secondary Level', 'option value', 'wpsso' );
_x( 'Grade Ten (PA)', 'option value', 'wpsso' );
_x( 'Grade Ten', 'option value', 'wpsso' );
_x( 'Grade Eleven (PA)', 'option value', 'wpsso' );
_x( 'Grade Eleven', 'option value', 'wpsso' );
_x( 'Grade Twelve (PA)', 'option value', 'wpsso' );
_x( 'Grade Twelve', 'option value', 'wpsso' );
_x( 'Higher Education (PA)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Papua New Guinea', 'option value', 'wpsso' );
_x( 'Middle (PG)', 'option value', 'wpsso' );
_x( 'Middle', 'option value', 'wpsso' );
_x( 'Grade 7 (PG)', 'option value', 'wpsso' );
_x( 'Grade 7', 'option value', 'wpsso' );
_x( 'Grade 8 (PG)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (PG)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (PG)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Secondary (PG)', 'option value', 'wpsso' );
_x( 'Secondary', 'option value', 'wpsso' );
_x( 'Grade 11 (PG)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (PG)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary (PG)', 'option value', 'wpsso' );
_x( 'Tertiary', 'option value', 'wpsso' );
_x( 'Paraguay', 'option value', 'wpsso' );
_x( 'Primary Education (PY)', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( '8th Grade (PY)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (PY)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (PY)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '10th Grade (PY)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (PY)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (PY)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education (PY)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Peru', 'option value', 'wpsso' );
_x( 'Secondary School (PE)', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( '9th Grade (PE)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade (PE)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (PE)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (PE)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Philippines', 'option value', 'wpsso' );
_x( 'Junior High School (PH)', 'option value', 'wpsso' );
_x( 'Junior High School', 'option value', 'wpsso' );
_x( 'Grade 8 (PH)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (PH)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (PH)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Senior High School (PH)', 'option value', 'wpsso' );
_x( 'Senior High School', 'option value', 'wpsso' );
_x( 'Grade 11 (PH)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (PH)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education (PH)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Poland', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (PL)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 2 (high school) (PL)', 'option value', 'wpsso' );
_x( 'Grade 2', 'option value', 'wpsso' );
_x( 'Grade 3 (high school) (PL)', 'option value', 'wpsso' );
_x( 'Grade 3', 'option value', 'wpsso' );
_x( 'Grade 4 (high school) (PL)', 'option value', 'wpsso' );
_x( 'Grade 4', 'option value', 'wpsso' );
_x( 'Higher Education (PL)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Portugal', 'option value', 'wpsso' );
_x( 'Basic Education (PT)', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( '8th Year (PT)', 'option value', 'wpsso' );
_x( '8th Year', 'option value', 'wpsso' );
_x( '9th Year (PT)', 'option value', 'wpsso' );
_x( '9th Year', 'option value', 'wpsso' );
_x( 'Secondary Education (PT)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '10th Year (PT)', 'option value', 'wpsso' );
_x( '10th Year', 'option value', 'wpsso' );
_x( '11th Year (PT)', 'option value', 'wpsso' );
_x( '11th Year', 'option value', 'wpsso' );
_x( '12th Year (PT)', 'option value', 'wpsso' );
_x( '12th Year', 'option value', 'wpsso' );
_x( 'Tertiary Education (PT)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Puerto Rico', 'option value', 'wpsso' );
_x( 'Junior High School (PR)', 'option value', 'wpsso' );
_x( 'Junior High School', 'option value', 'wpsso' );
_x( 'Eighth Grade (PR)', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade (PR)', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'High School (PR)', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( 'Tenth Grade (PR)', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade (PR)', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade (PR)', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Higher Education (PR)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Qatar', 'option value', 'wpsso' );
_x( 'Preparatory Education (QA)', 'option value', 'wpsso' );
_x( 'Preparatory Education', 'option value', 'wpsso' );
_x( 'Grade 8 (QA)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (QA)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education (QA)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (QA)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (QA)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (QA)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'University (QA)', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Doctorate (QA)', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Romania', 'option value', 'wpsso' );
_x( 'Secondary School (RO)', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( 'Class X (RO)', 'option value', 'wpsso' );
_x( 'Class X', 'option value', 'wpsso' );
_x( 'Class XI (RO)', 'option value', 'wpsso' );
_x( 'Class XI', 'option value', 'wpsso' );
_x( 'Class XII (RO)', 'option value', 'wpsso' );
_x( 'Class XII', 'option value', 'wpsso' );
_x( 'Higher Education (RO)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Russia', 'option value', 'wpsso' );
_x( 'Basic General Education (RU)', 'option value', 'wpsso' );
_x( 'Basic General Education', 'option value', 'wpsso' );
_x( 'Eighth Grade (RU)', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade (RU)', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Secondary General Education (RU)', 'option value', 'wpsso' );
_x( 'Secondary General Education', 'option value', 'wpsso' );
_x( 'Tenth Grade (RU)', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade (RU)', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Postsecondary and Tertiary Education (RU)', 'option value', 'wpsso' );
_x( 'Postsecondary and Tertiary Education', 'option value', 'wpsso' );
_x( 'Saudi Arabia', 'option value', 'wpsso' );
_x( 'Intermediate Education (SA)', 'option value', 'wpsso' );
_x( 'Intermediate Education', 'option value', 'wpsso' );
_x( 'Grade 8 (SA)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (SA)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education (SA)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (SA)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (SA)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (SA)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education (SA)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Scotland', 'option value', 'wpsso' );
_x( 'Secondary School (GB-SCT)', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( 'Second Year (S2) (GB-SCT)', 'option value', 'wpsso' );
_x( 'Second Year', 'option value', 'wpsso' );
_x( 'Third Year (S3) (GB-SCT)', 'option value', 'wpsso' );
_x( 'Third Year', 'option value', 'wpsso' );
_x( 'Fourth Year (S4) (GB-SCT)', 'option value', 'wpsso' );
_x( 'Fourth Year', 'option value', 'wpsso' );
_x( 'Fifth Year (S5) (GB-SCT)', 'option value', 'wpsso' );
_x( 'Fifth Year', 'option value', 'wpsso' );
_x( 'Higher Education (GB-SCT)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Doctorate (GB-SCT)', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Senegal', 'option value', 'wpsso' );
_x( 'Lower Secondary Education (SN)', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8 (SN)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (SN)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (SN)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (SN)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 11 (SN)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (SN)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Grade 13 (SN)', 'option value', 'wpsso' );
_x( 'Grade 13', 'option value', 'wpsso' );
_x( 'Tertiary Education (SN)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Serbia', 'option value', 'wpsso' );
_x( 'Secondary-High School (RS)', 'option value', 'wpsso' );
_x( 'Secondary-High School', 'option value', 'wpsso' );
_x( 'Year 2 (RS)', 'option value', 'wpsso' );
_x( 'Year 2', 'option value', 'wpsso' );
_x( 'Year 3 (RS)', 'option value', 'wpsso' );
_x( 'Year 3', 'option value', 'wpsso' );
_x( 'Year 4 (RS)', 'option value', 'wpsso' );
_x( 'Year 4', 'option value', 'wpsso' );
_x( 'Higher Education (RS)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Singapore', 'option value', 'wpsso' );
_x( 'Secondary Education (SG)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Secondary 1 (SG)', 'option value', 'wpsso' );
_x( 'Secondary 1', 'option value', 'wpsso' );
_x( 'Secondary 2 (SG)', 'option value', 'wpsso' );
_x( 'Secondary 2', 'option value', 'wpsso' );
_x( 'Secondary 3 (SG)', 'option value', 'wpsso' );
_x( 'Secondary 3', 'option value', 'wpsso' );
_x( 'Secondary 4 (SG)', 'option value', 'wpsso' );
_x( 'Secondary 4', 'option value', 'wpsso' );
_x( 'Secondary 5 (SG)', 'option value', 'wpsso' );
_x( 'Secondary 5', 'option value', 'wpsso' );
_x( 'Post-secondary Education (SG)', 'option value', 'wpsso' );
_x( 'Post-secondary Education', 'option value', 'wpsso' );
_x( 'Slovakia', 'option value', 'wpsso' );
_x( 'High School (SK)', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( '2nd Grade (High School) (SK)', 'option value', 'wpsso' );
_x( '2nd Grade', 'option value', 'wpsso' );
_x( '3rd Grade (High School) (SK)', 'option value', 'wpsso' );
_x( '3rd Grade', 'option value', 'wpsso' );
_x( '4th Grade (High School) (SK)', 'option value', 'wpsso' );
_x( '4th Grade', 'option value', 'wpsso' );
_x( 'Post-Secondary Education (SK)', 'option value', 'wpsso' );
_x( 'Post-Secondary Education', 'option value', 'wpsso' );
_x( 'Slovenia', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (SI)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 11 (SI)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (SI)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Grade 13 (SI)', 'option value', 'wpsso' );
_x( 'Grade 13', 'option value', 'wpsso' );
_x( 'Tertiary Education (SI)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'South Africa', 'option value', 'wpsso' );
_x( 'Senior Phase (ZA)', 'option value', 'wpsso' );
_x( 'Senior Phase', 'option value', 'wpsso' );
_x( 'Grade 8 (ZA)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (ZA)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Further Education and Training (ZA)', 'option value', 'wpsso' );
_x( 'Further Education and Training', 'option value', 'wpsso' );
_x( 'Grade 10 (ZA)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (ZA)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (ZA)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education and Training (ZA)', 'option value', 'wpsso' );
_x( 'Higher Education and Training', 'option value', 'wpsso' );
_x( 'South Korea', 'option value', 'wpsso' );
_x( 'Middle School (KR)', 'option value', 'wpsso' );
_x( 'Middle School', 'option value', 'wpsso' );
_x( '3rd Grade (KR)', 'option value', 'wpsso' );
_x( '3rd Grade', 'option value', 'wpsso' );
_x( 'High School (KR)', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( '1st Grade (KR)', 'option value', 'wpsso' );
_x( '1st Grade', 'option value', 'wpsso' );
_x( '2nd Grade (KR)', 'option value', 'wpsso' );
_x( '2nd Grade', 'option value', 'wpsso' );
_x( '3rd Grade (KR)', 'option value', 'wpsso' );
_x( '3rd Grade', 'option value', 'wpsso' );
_x( 'Higher Education (KR)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Spain', 'option value', 'wpsso' );
_x( 'Lower Secondary Education (ES)', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 9 (ES)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (ES)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (ES)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 11 (ES)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (ES)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary education (ES)', 'option value', 'wpsso' );
_x( 'Tertiary education', 'option value', 'wpsso' );
_x( 'Sri Lanka', 'option value', 'wpsso' );
_x( 'Junior Secondary (LK)', 'option value', 'wpsso' );
_x( 'Junior Secondary', 'option value', 'wpsso' );
_x( 'Grade 9 (LK)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Senior Secondary (LK)', 'option value', 'wpsso' );
_x( 'Senior Secondary', 'option value', 'wpsso' );
_x( 'Grade 10 (LK)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (LK)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Collegiate (LK)', 'option value', 'wpsso' );
_x( 'Collegiate', 'option value', 'wpsso' );
_x( 'Grade 12 (LK)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Grade 13 (LK)', 'option value', 'wpsso' );
_x( 'Grade 13', 'option value', 'wpsso' );
_x( 'Tertiary Education (LK)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Sweden', 'option value', 'wpsso' );
_x( 'Comprehensive School (SE)', 'option value', 'wpsso' );
_x( 'Comprehensive School', 'option value', 'wpsso' );
_x( '7th Grade (SE)', 'option value', 'wpsso' );
_x( '7th Grade', 'option value', 'wpsso' );
_x( '8th Grade (SE)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (SE)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (SE)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '1st Grade (SE)', 'option value', 'wpsso' );
_x( '1st Grade', 'option value', 'wpsso' );
_x( '2nd Grade (SE)', 'option value', 'wpsso' );
_x( '2nd Grade', 'option value', 'wpsso' );
_x( '3rd Grade (SE)', 'option value', 'wpsso' );
_x( '3rd Grade', 'option value', 'wpsso' );
_x( 'University (SE)', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Switzerland', 'option value', 'wpsso' );
_x( 'Lower Secondary Level (CH)', 'option value', 'wpsso' );
_x( 'Lower Secondary Level', 'option value', 'wpsso' );
_x( 'Grade 8 (CH)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (CH)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Upper Secondary Level (CH)', 'option value', 'wpsso' );
_x( 'Upper Secondary Level', 'option value', 'wpsso' );
_x( 'Grade-1 (CH)', 'option value', 'wpsso' );
_x( 'Grade-1', 'option value', 'wpsso' );
_x( 'Grade-2 (CH)', 'option value', 'wpsso' );
_x( 'Grade-2', 'option value', 'wpsso' );
_x( 'Grade-3 (CH)', 'option value', 'wpsso' );
_x( 'Grade-3', 'option value', 'wpsso' );
_x( 'Tertiary Level (CH)', 'option value', 'wpsso' );
_x( 'Tertiary Level', 'option value', 'wpsso' );
_x( 'Taiwan', 'option value', 'wpsso' );
_x( 'Junior High School (TW)', 'option value', 'wpsso' );
_x( 'Junior High School', 'option value', 'wpsso' );
_x( '8th Grade (TW)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (TW)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Senior High School (TW)', 'option value', 'wpsso' );
_x( 'Senior High School', 'option value', 'wpsso' );
_x( '10th Grade (TW)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (TW)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (TW)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education (TW)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Tanzania', 'option value', 'wpsso' );
_x( 'Primary Education (TZ)', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 7 (TZ)', 'option value', 'wpsso' );
_x( 'Grade 7', 'option value', 'wpsso' );
_x( 'Lower Secondary (TZ)', 'option value', 'wpsso' );
_x( 'Lower Secondary', 'option value', 'wpsso' );
_x( 'Grade 8 (TZ)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (TZ)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (TZ)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (TZ)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (TZ)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Upper Secondary (TZ)', 'option value', 'wpsso' );
_x( 'Upper Secondary', 'option value', 'wpsso' );
_x( 'University (TZ)', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Doctorate (TZ)', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Thailand', 'option value', 'wpsso' );
_x( 'Lower Secondary (TH)', 'option value', 'wpsso' );
_x( 'Lower Secondary', 'option value', 'wpsso' );
_x( 'Eighth Grade (TH)', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade (TH)', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary (TH)', 'option value', 'wpsso' );
_x( 'Upper Secondary', 'option value', 'wpsso' );
_x( 'Tenth Grade (TH)', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade (TH)', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade (TH)', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Higher Education (TH)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Tunisia', 'option value', 'wpsso' );
_x( 'Basic Education (TN)', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( 'Eighth Grade (TN)', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade (TN)', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Secondary Education (TN)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Tenth Grade (TN)', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade (TN)', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade (TN)', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education (TN)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Türkiye', 'option value', 'wpsso' );
_x( 'Primary Education (TR)', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( '8th Grade (TR)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( 'High School (TR)', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( '9th Grade (TR)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade (TR)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (TR)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (TR)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (TR)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Uganda', 'option value', 'wpsso' );
_x( 'Lower Secondary Education (UG)', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( 'Eighth Grade (UG)', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade (UG)', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Tenth Grade (UG)', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade (UG)', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (UG)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Twelfth Grade (UG)', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Thirteenth Grade (UG)', 'option value', 'wpsso' );
_x( 'Thirteenth Grade', 'option value', 'wpsso' );
_x( 'Post-Secondary Education (UG)', 'option value', 'wpsso' );
_x( 'Post-Secondary Education', 'option value', 'wpsso' );
_x( 'Ukraine', 'option value', 'wpsso' );
_x( 'Secondary Base School (UA)', 'option value', 'wpsso' );
_x( 'Secondary Base School', 'option value', 'wpsso' );
_x( '8th Grade (UA)', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade (UA)', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Secondary Last School (UA)', 'option value', 'wpsso' );
_x( 'Secondary Last School', 'option value', 'wpsso' );
_x( '10th Grade (UA)', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade (UA)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (UA)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education (UA)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'United Arab Emirates', 'option value', 'wpsso' );
_x( 'Intermediate Level (AE)', 'option value', 'wpsso' );
_x( 'Intermediate Level', 'option value', 'wpsso' );
_x( 'Grade 8 (AE)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Secondary Level (AE)', 'option value', 'wpsso' );
_x( 'Secondary Level', 'option value', 'wpsso' );
_x( 'Grade 9 (AE)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (AE)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (AE)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (AE)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education (AE)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'United States', 'option value', 'wpsso' );
_x( 'Middle School (US)', 'option value', 'wpsso' );
_x( 'Middle School', 'option value', 'wpsso' );
_x( 'Eighth Grade (US)', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'High School (US)', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( 'Ninth Grade (US)', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Tenth Grade (US)', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade (US)', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade (US)', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'College (US)', 'option value', 'wpsso' );
_x( 'College', 'option value', 'wpsso' );
_x( 'Graduate School (US)', 'option value', 'wpsso' );
_x( 'Graduate School', 'option value', 'wpsso' );
_x( 'Venezuela', 'option value', 'wpsso' );
_x( 'Middle Education (VE)', 'option value', 'wpsso' );
_x( 'Middle Education', 'option value', 'wpsso' );
_x( 'Grade 9 (VE)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Diversified Education (VE)', 'option value', 'wpsso' );
_x( 'Diversified Education', 'option value', 'wpsso' );
_x( 'Grade 10 (VE)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (VE)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (VE)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education School (VE)', 'option value', 'wpsso' );
_x( 'Higher Education School', 'option value', 'wpsso' );
_x( 'Vietnam', 'option value', 'wpsso' );
_x( 'Upper Secondary Education (VN)', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Tenth Grade (VN)', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade (VN)', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade (VN)', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Higher Education (VN)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Wales', 'option value', 'wpsso' );
_x( 'Key Stage 4 (GB-WLS)', 'option value', 'wpsso' );
_x( 'Key Stage 4', 'option value', 'wpsso' );
_x( 'Year 10 (GB-WLS)', 'option value', 'wpsso' );
_x( 'Year 10', 'option value', 'wpsso' );
_x( 'Year 11 (GB-WLS)', 'option value', 'wpsso' );
_x( 'Year 11', 'option value', 'wpsso' );
_x( 'Key Stage 5 (GB-WLS)', 'option value', 'wpsso' );
_x( 'Key Stage 5', 'option value', 'wpsso' );
_x( 'Year 12 (GB-WLS)', 'option value', 'wpsso' );
_x( 'Year 12', 'option value', 'wpsso' );
_x( 'Year 13 (GB-WLS)', 'option value', 'wpsso' );
_x( 'Year 13', 'option value', 'wpsso' );
_x( 'Higher Education (GB-WLS)', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Yemen', 'option value', 'wpsso' );
_x( 'Basic Education (YE)', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( 'Grade 8 (YE)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (YE)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education (YE)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10 (YE)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (YE)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (YE)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'University Education (YE)', 'option value', 'wpsso' );
_x( 'University Education', 'option value', 'wpsso' );
_x( 'Zimbabwe', 'option value', 'wpsso' );
_x( 'Secondary Education (ZW)', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8 (ZW)', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9 (ZW)', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10 (ZW)', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11 (ZW)', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12 (ZW)', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Grade 13 (ZW)', 'option value', 'wpsso' );
_x( 'Grade 13', 'option value', 'wpsso' );
_x( 'Tertiary Education (ZW)', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
