<?php die( 'These aren\'t the droids you\'re looking for.' );
// 
// Extract of translatable strings from lib/config.php.
// 
_x( 'Premium', 'package name', 'wpsso' );
_x( 'Standard', 'package name', 'wpsso' );
_x( 'WPSSO Schema Shortcode', 'plugin name', 'wpsso' );
_x( 'Schema shortcode to define and customize additional properties and types for sections of the content.', 'plugin description', 'wpsso' );
_x( 'Update Manager', 'lib file description', 'wpsso' );
_x( 'Update Manager', 'lib file description', 'wpsso' );
_x( 'WPSSO Update Manager', 'plugin name', 'wpsso' );
_x( 'Update Manager for the WPSSO Core Premium plugin.', 'plugin description', 'wpsso' );
_x( 'WPSSO Core', 'plugin name', 'wpsso' );
_x( '(feature) Import All in One SEO Pack Metadata', 'lib file description', 'wpsso' );
_x( '(feature) Import Rank Math SEO Metadata', 'lib file description', 'wpsso' );
_x( '(feature) Import The SEO Framework Metadata', 'lib file description', 'wpsso' );
_x( '(feature) Import WP Meta SEO Metadata', 'lib file description', 'wpsso' );
_x( '(feature) Import Yoast SEO Block Attrs', 'lib file description', 'wpsso' );
_x( '(feature) Import Yoast SEO Metadata', 'lib file description', 'wpsso' );
_x( '(plugin) Perfect Brands for WooCommerce', 'lib file description', 'wpsso' );
_x( '(plugin) WooCommerce', 'lib file description', 'wpsso' );
_x( '(plugin) WooCommerce Brands', 'lib file description', 'wpsso' );
_x( '(plugin) WooCommerce Currency Switcher', 'lib file description', 'wpsso' );
_x( '(plugin) WooCommerce UPC, EAN, and ISBN', 'lib file description', 'wpsso' );
_x( '(plugin) Product GTIN for WooCommerce', 'lib file description', 'wpsso' );
_x( '(plugin) YITH WooCommerce Brands Add-on', 'lib file description', 'wpsso' );
_x( '(plugin) The Events Calendar', 'lib file description', 'wpsso' );
_x( '(plugin) Gravity Forms', 'lib file description', 'wpsso' );
_x( '(plugin) Gravity View', 'lib file description', 'wpsso' );
_x( '(plugin) Simple Job Board', 'lib file description', 'wpsso' );
_x( '(plugin) WP Job Manager', 'lib file description', 'wpsso' );
_x( '(plugin) Polylang', 'lib file description', 'wpsso' );
_x( '(plugin) qTranslate-XT', 'lib file description', 'wpsso' );
_x( '(plugin) WPML', 'lib file description', 'wpsso' );
_x( '(plugin) Perfect Images', 'lib file description', 'wpsso' );
_x( '(plugin) Rate my Post', 'lib file description', 'wpsso' );
_x( '(plugin) WP-PostRatings', 'lib file description', 'wpsso' );
_x( '(plugin) WP Recipe Maker', 'lib file description', 'wpsso' );
_x( '(plugin) Judge.me Product Reviews for WooCommerce', 'lib file description', 'wpsso' );
_x( '(plugin) WP Product Review', 'lib file description', 'wpsso' );
_x( '(plugin) Yotpo Social Reviews for WooCommerce', 'lib file description', 'wpsso' );
_x( '(plugin) All in One SEO Pack', 'lib file description', 'wpsso' );
_x( '(plugin) Rank Math SEO', 'lib file description', 'wpsso' );
_x( '(plugin) The SEO Framework', 'lib file description', 'wpsso' );
_x( '(plugin) SEOPress', 'lib file description', 'wpsso' );
_x( '(plugin) WP Meta SEO', 'lib file description', 'wpsso' );
_x( '(plugin) Yoast SEO', 'lib file description', 'wpsso' );
_x( '(plugin) Co-Authors Plus', 'lib file description', 'wpsso' );
_x( '(plugin) Ultimate Member', 'lib file description', 'wpsso' );
_x( '(plugin) Elementor Website Builder', 'lib file description', 'wpsso' );
_x( '(plugin) Jetpack', 'lib file description', 'wpsso' );
_x( '(plugin) Jetpack Boost', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Article [schema_type:article]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Audiobook [schema_type:book.audio]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Blog [schema_type:blog]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Book [schema_type:book]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Brand [schema_type:brand]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Claim Review [schema_type:review.claim]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Collection Page [schema_type:webpage.collection]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Course [schema_type:course]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type CreativeWork [schema_type:creative.work]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Event [schema_type:event]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type FAQPage [schema_type:webpage.faq]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Food Establishment [schema_type:food.establishment]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type How-To [schema_type:howto]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type ItemList [schema_type:item.list]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Job Posting [schema_type:job.posting]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Learning Resource [schema_type:learning.resource]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Local Business [schema_type:local.business]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Movie [schema_type:movie]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Organization [schema_type:organization]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Person [schema_type:person]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Place [schema_type:place]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Product [schema_type:product]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Product Group [schema_type:product.group]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Profile Page [schema_type:webpage.profile]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type QAPage [schema_type:webpage.qa]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Question and Answer [schema_type:question]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Recipe [schema_type:recipe]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Review [schema_type:review]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Search Results Page [schema_type:webpage.search.results]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Software Application [schema_type:software.application]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type Thing [schema_type:thing]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type WebPage [schema_type:webpage]', 'lib file description', 'wpsso' );
_x( '(code) Schema Type WebSite [schema_type:website]', 'lib file description', 'wpsso' );
_x( '(code-plus) Schema Property aggregateRating', 'lib file description', 'wpsso' );
_x( '(code-plus) Schema Property hasPart', 'lib file description', 'wpsso' );
_x( '(code-plus) Schema Property review', 'lib file description', 'wpsso' );
_x( '(api) Get Facebook Video Data', 'lib file description', 'wpsso' );
_x( '(api) Get Gravatar Image Data', 'lib file description', 'wpsso' );
_x( '(api) Get Slideshare Presentation Data', 'lib file description', 'wpsso' );
_x( '(api) Get Soundcloud Track Data', 'lib file description', 'wpsso' );
_x( '(api) Get Vimeo Video Data', 'lib file description', 'wpsso' );
_x( '(api) Get Wistia Video Data', 'lib file description', 'wpsso' );
_x( '(api) Get WP Media Library Video Block Data', 'lib file description', 'wpsso' );
_x( '(api) Get WP Media Library Video Shortcode Data', 'lib file description', 'wpsso' );
_x( '(api) Get YouTube Video and Playlist Data', 'lib file description', 'wpsso' );
_x( '(feature) Upscale Media Library Images', 'lib file description', 'wpsso' );
_x( '(api) Get Judge.me Review Data', 'lib file description', 'wpsso' );
_x( '(api) Get Shopper Approved Review Data', 'lib file description', 'wpsso' );
_x( '(api) Get Stamped.io Review Data', 'lib file description', 'wpsso' );
_x( '(feature) URL Shortening Services', 'lib file description', 'wpsso' );
_x( 'Profile SSO - Social and Search Optimization', 'lib file description', 'wpsso' );
_x( 'Advanced Settings', 'lib file description', 'wpsso' );
_x( 'Premium Licenses', 'lib file description', 'wpsso' );
_x( 'Plugin Add-ons', 'lib file description', 'wpsso' );
_x( 'Setup Guide', 'lib file description', 'wpsso' );
_x( '(api) Get Facebook Video Data', 'lib file description', 'wpsso' );
_x( '(api) Get Slideshare Presentation Data', 'lib file description', 'wpsso' );
_x( '(api) Get Soundcloud Track Data', 'lib file description', 'wpsso' );
_x( '(api) Get Vimeo Video Data', 'lib file description', 'wpsso' );
_x( '(api) Get Wistia Video Data', 'lib file description', 'wpsso' );
_x( '(api) Get WP Media Library Video Block Data', 'lib file description', 'wpsso' );
_x( '(api) Get WP Media Library Video Shortcode Data', 'lib file description', 'wpsso' );
_x( '(api) Get YouTube Video and Playlist Data', 'lib file description', 'wpsso' );
_x( '(api) Get Judge.me Review Data', 'lib file description', 'wpsso' );
_x( 'Dashboard', 'lib file description', 'wpsso' );
_x( 'Essential Settings', 'lib file description', 'wpsso' );
_x( 'General Settings', 'lib file description', 'wpsso' );
_x( 'Advanced Settings', 'lib file description', 'wpsso' );
_x( 'Premium Licenses', 'lib file description', 'wpsso' );
_x( 'Plugin Add-ons', 'lib file description', 'wpsso' );
_x( 'Tools and Actions', 'lib file description', 'wpsso' );
_x( 'Setup Guide', 'lib file description', 'wpsso' );
_x( 'Add Person', 'lib file description', 'wpsso' );
_x( 'WPSSO Core', 'plugin name', 'wpsso' );
_x( 'Present your content at its best for social sites and search results, no matter how URLs are shared, reshared, messaged, posted, embedded, or crawled.', 'plugin description', 'wpsso' );
_x( 'WPSSO Add Five Stars', 'plugin name', 'wpsso' );
_x( 'Add a 5 star rating and review from the site organization if the Schema markup does not already have an \'aggregateRating\' property.', 'plugin description', 'wpsso' );
_x( 'WPSSO Mobile App Meta Tags', 'plugin name', 'wpsso' );
_x( 'Apple Store and Google Play App meta tags for Apple\'s mobile Safari banner and X\'s (Twitter) App Card.', 'plugin description', 'wpsso' );
_x( 'WPSSO Schema Breadcrumbs Markup', 'plugin name', 'wpsso' );
_x( 'Schema BreadcrumbList markup in JSON-LD format for Google Rich Results.', 'plugin description', 'wpsso' );
_x( 'WPSSO Commerce Manager Catalog Feed XML', 'plugin name', 'wpsso' );
_x( 'Facebook and Instagram Commerce Manager Catalog Feed XMLs for WooCommerce and custom product pages.', 'plugin description', 'wpsso' );
_x( 'WPSSO FAQ Manager', 'plugin name', 'wpsso' );
_x( 'Create FAQ and Question / Answer Pages with optional shortcodes to include FAQs and Questions / Answers in your content.', 'plugin description', 'wpsso' );
_x( 'WPSSO Google Merchant Feed XML', 'plugin name', 'wpsso' );
_x( 'Google Merchant product and inventory feed XML for WooCommerce and custom product pages, including multilingual support.', 'plugin description', 'wpsso' );
_x( 'WPSSO Merchant Return Policy Manager', 'plugin name', 'wpsso' );
_x( 'Manage any number of Merchant Return Policies for Google Merchant listings.', 'plugin description', 'wpsso' );
_x( 'WPSSO Organization and Place Manager', 'plugin name', 'wpsso' );
_x( 'Manage Organizations (publisher, organizer, etc.) and Places for Facebook, Pinterest, and Google local business markup.', 'plugin description', 'wpsso' );
_x( 'WPSSO Ratings and Reviews', 'plugin name', 'wpsso' );
_x( 'Adds Ratings and Reviews Features to the WordPress Comments System.', 'plugin description', 'wpsso' );
_x( 'WPSSO REST API', 'plugin name', 'wpsso' );
_x( 'Extends the WordPress REST API post, term, and user query results with an array of meta tags and Schema JSON-LD markup.', 'plugin description', 'wpsso' );
_x( 'WPSSO Ridiculously Responsive Social Sharing Buttons', 'plugin name', 'wpsso' );
_x( 'Ridiculously Responsive (SVG) Social Sharing Buttons for your content, excerpts, CSS sidebar, widget, shortcode, templates, and editor.', 'plugin description', 'wpsso' );
_x( 'WPSSO Strip Schema Microdata', 'plugin name', 'wpsso' );
_x( 'Remove Schema Microdata and RDFa from the webpage for better Google Rich Results using Schema JSON-LD markup.', 'plugin description', 'wpsso' );
_x( 'WPSSO Tune WP Image Editors', 'plugin name', 'wpsso' );
_x( 'Improves the appearance of WordPress images for better click through rates from social and search sites.', 'plugin description', 'wpsso' );
_x( 'WPSSO User Locale Selector', 'plugin name', 'wpsso' );
_x( 'Quick and easy locale / language / region selector for the WordPress admin toolbar.', 'plugin description', 'wpsso' );
_x( 'WPSSO Product Metadata for WooCommerce SEO', 'plugin name', 'wpsso' );
_x( 'MPN, ISBN, GTIN, GTIN-8, UPC, EAN, GTIN-14, net dimensions, and fluid volume for WooCommerce products and variations.', 'plugin description', 'wpsso' );
_x( 'WPSSO Shipping Delivery Time for WooCommerce SEO', 'plugin name', 'wpsso' );
_x( 'Shipping delivery time estimates for WooCommerce shipping zones, methods, and classes.', 'plugin description', 'wpsso' );
_x( 'WPSSO WP Sitemaps XML', 'plugin name', 'wpsso' );
_x( 'Improves the WordPress sitemaps XML with article modification times, alternate language URLs, images sitemaps, news sitemaps and more.', 'plugin description', 'wpsso' );
_x( 'SSO - Social and Search Optimization', 'menu title', 'wpsso' );
_x( 'SSO', 'notice title', 'wpsso' );
_x( 'Document SSO', 'metabox title', 'wpsso' );
_x( 'Job Title', 'option label', 'wpsso' );
_x( 'Honorific Prefix', 'option label', 'wpsso' );
_x( 'Honorific Suffix', 'option label', 'wpsso' );
_x( 'Middle or Additional Name', 'option label', 'wpsso' );
_x( 'Awards', 'option label', 'wpsso' );
_x( 'Behance Profile URL', 'option value', 'wpsso' );
_x( 'Facebook User URL', 'option value', 'wpsso' );
_x( 'Instagram URL', 'option value', 'wpsso' );
_x( 'LinkedIn URL', 'option value', 'wpsso' );
_x( 'Medium URL', 'option value', 'wpsso' );
_x( 'Myspace URL', 'option value', 'wpsso' );
_x( 'Pinterest URL', 'option value', 'wpsso' );
_x( 'Soundcloud URL', 'option value', 'wpsso' );
_x( 'Skype Username', 'option value', 'wpsso' );
_x( 'TikTok URL', 'option value', 'wpsso' );
_x( 'Tumblr URL', 'option value', 'wpsso' );
_x( 'Wikipedia Page URL', 'option value', 'wpsso' );
_x( 'X (Twitter) @username', 'option value', 'wpsso' );
_x( 'X', 'option value', 'wpsso' );
_x( 'YouTube Channel URL', 'option value', 'wpsso' );
_x( 'SSO Schema', 'column header', 'wpsso' );
_x( 'SSO Lang', 'column header', 'wpsso' );
_x( 'SSO Image', 'column header', 'wpsso' );
_x( 'SSO Desc', 'column header', 'wpsso' );
_x( 'File Content', 'option label', 'wpsso' );
_x( 'Readme Info', 'option label', 'wpsso' );
_x( 'YouTube Video Details', 'option label', 'wpsso' );
_x( 'All Files', 'option label', 'wpsso' );
_x( 'Document Markup', 'option label', 'wpsso' );
_x( 'Image URL Info', 'option label', 'wpsso' );
_x( 'API Response', 'option label', 'wpsso' );
_x( 'Short URLs', 'option label', 'wpsso' );
_x( 'Schema Types', 'option label', 'wpsso' );
_x( 'All Transients', 'option label', 'wpsso' );
_x( 'Filtered Content', 'option label', 'wpsso' );
_x( 'All WP Objects', 'option label', 'wpsso' );
_x( 'Yes', 'option value', 'wpsso' );
_x( 'No', 'option value', 'wpsso' );
_x( 'True', 'option value', 'wpsso' );
_x( 'False', 'option value', 'wpsso' );
_x( 'On', 'option value', 'wpsso' );
_x( 'Off', 'option value', 'wpsso' );
_x( 'Sunday', 'option value', 'wpsso' );
_x( 'Monday', 'option value', 'wpsso' );
_x( 'Tuesday', 'option value', 'wpsso' );
_x( 'Wednesday', 'option value', 'wpsso' );
_x( 'Thursday', 'option value', 'wpsso' );
_x( 'Friday', 'option value', 'wpsso' );
_x( 'Saturday', 'option value', 'wpsso' );
_x( 'Public Holidays', 'option value', 'wpsso' );
_x( 'Hour', 'option value', 'wpsso' );
_x( 'Day', 'option value', 'wpsso' );
_x( 'Week', 'option value', 'wpsso' );
_x( 'Month', 'option value', 'wpsso' );
_x( 'Year', 'option value', 'wpsso' );
_x( '(default)', 'option value', 'wpsso' );
_x( '', 'option value', 'wpsso' );
_x( '(no images)', 'option value', 'wpsso' );
_x( '', 'option value', 'wpsso' );
_x( '(no videos)', 'option value', 'wpsso' );
_x( '', 'option value', 'wpsso' );
_x( '(settings value)', 'option value', 'wpsso' );
_x( '', 'option value', 'wpsso' );
_x( '(option disabled)', 'option value', 'wpsso' );
_x( '', 'option value', 'wpsso' );
_x( 'default is %s', 'option value', 'wpsso' );
_x( 'checked', 'option value', 'wpsso' );
_x( 'unchecked', 'option value', 'wpsso' );
_x( 'at', 'option value', 'wpsso' );
_x( 'tz', 'option value', 'wpsso' );
_x( 'Post Type', 'option value', 'wpsso' );
_x( 'Taxonomy', 'option value', 'wpsso' );
_x( 'User Profiles', 'option value', 'wpsso' );
_x( '[WordPress Title]', 'option value', 'wpsso' );
_x( 'WordPress Title', 'option value', 'wpsso' );
_x( 'SEO Title Tag', 'option value', 'wpsso' );
_x( 'Schema Name', 'option value', 'wpsso' );
_x( 'Schema Alternate Name', 'option value', 'wpsso' );
_x( 'Basic Options', 'option value', 'wpsso' );
_x( 'All Options', 'option value', 'wpsso' );
_x( 'First Activation', 'option value', 'wpsso' );
_x( 'If Option Is Empty', 'option value', 'wpsso' );
_x( 'Always Force Value', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Header', 'option value', 'wpsso' );
_x( 'Footer', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Title Only', 'option value', 'wpsso' );
_x( 'Excerpt Only', 'option value', 'wpsso' );
_x( 'Title and Excerpt', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Organization', 'option value', 'wpsso' );
_x( 'Person', 'option value', 'wpsso' );
_x( 'Organization', 'option value', 'wpsso' );
_x( 'Person', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'First and Last Names', 'option value', 'wpsso' );
_x( 'Display Name', 'option value', 'wpsso' );
_x( 'Nickname', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( '[Custom Address]', 'option value', 'wpsso' );
_x( 'Custom Address', 'option value', 'wpsso' );
_x( '[New Address]', 'option value', 'wpsso' );
_x( 'New Address', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( '[New Organization]', 'option value', 'wpsso' );
_x( 'New Organization', 'option value', 'wpsso' );
_x( '[Site Organization]', 'option value', 'wpsso' );
_x( 'Site Organization', 'option value', 'wpsso' );
_x( 'ID', 'option value', 'wpsso' );
_x( 'ID | Host/Name', 'option value', 'wpsso' );
_x( 'ID | Name', 'option value', 'wpsso' );
_x( 'Name [ID]', 'option value', 'wpsso' );
_x( 'Name', 'option value', 'wpsso' );
_x( 'Left', 'option value', 'wpsso' );
_x( 'Center', 'option value', 'wpsso' );
_x( 'Right', 'option value', 'wpsso' );
_x( 'Top', 'option value', 'wpsso' );
_x( 'Center', 'option value', 'wpsso' );
_x( 'Bottom', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Standard', 'option value', 'wpsso' );
_x( 'Large', 'option value', 'wpsso' );
_x( '[No Breadcrumbs]', 'option value', 'wpsso' );
_x( 'No Breadcrumbs', 'option value', 'wpsso' );
_x( 'Home Page(s) and Categories', 'option value', 'wpsso' );
_x( 'Home Page', 'option value', 'wpsso' );
_x( 'Home Page(s) and Parents', 'option value', 'wpsso' );
_x( 'Home Page', 'option value', 'wpsso' );
_x( 'Home Page(s) and Primary Category', 'option value', 'wpsso' );
_x( 'Home Page', 'option value', 'wpsso' );
_x( '[No Breadcrumbs]', 'option value', 'wpsso' );
_x( 'No Breadcrumbs', 'option value', 'wpsso' );
_x( 'Home Page(s) and Parents', 'option value', 'wpsso' );
_x( 'Home Page', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Bitly', 'option value', 'wpsso' );
_x( 'DLMY.App', 'option value', 'wpsso' );
_x( 'Ow.ly', 'option value', 'wpsso' );
_x( 'TinyURL', 'option value', 'wpsso' );
_x( 'YOURLS', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Judge.me', 'option value', 'wpsso' );
_x( 'Shopper Approved', 'option value', 'wpsso' );
_x( 'Stamped.io', 'option value', 'wpsso' );
_x( 'Behance Business Profile URL', 'option value', 'wpsso' );
_x( 'Facebook Business Page URL', 'option value', 'wpsso' );
_x( 'Instagram Business Profile URL', 'option value', 'wpsso' );
_x( 'LinkedIn Business Page URL', 'option value', 'wpsso' );
_x( 'Medium Business Page URL', 'option value', 'wpsso' );
_x( 'Myspace Business Page URL', 'option value', 'wpsso' );
_x( 'Pinterest Business Page URL', 'option value', 'wpsso' );
_x( 'Soundcloud Business Page URL', 'option value', 'wpsso' );
_x( 'TikTok Business Page URL', 'option value', 'wpsso' );
_x( 'Tumblr Business Page URL', 'option value', 'wpsso' );
_x( 'Wikipedia Organization Page URL', 'option value', 'wpsso' );
_x( 'X (Twitter) Business @username', 'option value', 'wpsso' );
_x( 'X', 'option value', 'wpsso' );
_x( 'YouTube Business Channel URL', 'option value', 'wpsso' );
_x( 'Facebook Videos', 'option value', 'wpsso' );
_x( 'Slideshare Presentations', 'option value', 'wpsso' );
_x( 'Soundcloud Tracks', 'option value', 'wpsso' );
_x( 'Vimeo Videos', 'option value', 'wpsso' );
_x( 'Wistia Videos', 'option value', 'wpsso' );
_x( 'WP Media Library Video Blocks', 'option value', 'wpsso' );
_x( 'WP Media Library Video Shortcodes', 'option value', 'wpsso' );
_x( 'YouTube Videos and Playlists', 'option value', 'wpsso' );
_x( 'Adult Type Attribute', 'option label', 'wpsso' );
_x( 'Age Group Attribute', 'option label', 'wpsso' );
_x( 'Brand Attribute', 'option label', 'wpsso' );
_x( 'Color Attribute', 'option label', 'wpsso' );
_x( 'Condition Attribute', 'option label', 'wpsso' );
_x( 'Energy Rating Attribute', 'option label', 'wpsso' );
_x( 'Fluid Volume Attribute', 'option label', 'wpsso' );
_x( 'GTIN-14 Attribute', 'option label', 'wpsso' );
_x( 'GTIN-13 (EAN) Attribute', 'option label', 'wpsso' );
_x( 'GTIN-12 (UPC) Attribute', 'option label', 'wpsso' );
_x( 'GTIN-8 Attribute', 'option label', 'wpsso' );
_x( 'GTIN Attribute', 'option label', 'wpsso' );
_x( 'Net Height Attribute', 'option label', 'wpsso' );
_x( 'ISBN Attribute', 'option label', 'wpsso' );
_x( 'Net Len. / Depth Attribute', 'option label', 'wpsso' );
_x( 'Material Attribute', 'option label', 'wpsso' );
_x( 'MPN Attribute', 'option label', 'wpsso' );
_x( 'Pattern Attribute', 'option label', 'wpsso' );
_x( 'Size Attribute', 'option label', 'wpsso' );
_x( 'Size Group Attribute', 'option label', 'wpsso' );
_x( 'Size System Attribute', 'option label', 'wpsso' );
_x( 'Target Gender Attribute', 'option label', 'wpsso' );
_x( 'Net Weight Attribute', 'option label', 'wpsso' );
_x( 'Net Width Attribute', 'option label', 'wpsso' );
_x( 'Microdata Type URLs Custom Field', 'option label', 'wpsso' );
_x( 'Book ISBN Custom Field', 'option label', 'wpsso' );
_x( 'Image URL Custom Field', 'option label', 'wpsso' );
_x( 'Product Adult Type Custom Field', 'option label', 'wpsso' );
_x( 'Product Age Group Custom Field', 'option label', 'wpsso' );
_x( 'Product Availability Custom Field', 'option label', 'wpsso' );
_x( 'Product Brand Custom Field', 'option label', 'wpsso' );
_x( 'Product Google Cat. ID Custom Field', 'option label', 'wpsso' );
_x( 'Product Color Custom Field', 'option label', 'wpsso' );
_x( 'Product Condition Custom Field', 'option label', 'wpsso' );
_x( 'Product Currency Custom Field', 'option label', 'wpsso' );
_x( 'Product Energy Rating Custom Field', 'option label', 'wpsso' );
_x( 'Product Fluid Volume Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN-14 Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN-13 (EAN) Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN-12 (UPC) Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN-8 Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN Custom Field', 'option label', 'wpsso' );
_x( 'Product ISBN Custom Field', 'option label', 'wpsso' );
_x( 'Product Net Height Custom Field', 'option label', 'wpsso' );
_x( 'Product Net Len. / Depth Custom Field', 'option label', 'wpsso' );
_x( 'Product Material Custom Field', 'option label', 'wpsso' );
_x( 'Product MPN Custom Field', 'option label', 'wpsso' );
_x( 'Product Min Advert Price Custom Field', 'option label', 'wpsso' );
_x( 'Product Pattern Custom Field', 'option label', 'wpsso' );
_x( 'Product Price Custom Field', 'option label', 'wpsso' );
_x( 'Product Price Type Custom Field', 'option label', 'wpsso' );
_x( 'Product SKU Custom Field', 'option label', 'wpsso' );
_x( 'Product Shipping Height Custom Field', 'option label', 'wpsso' );
_x( 'Product Shipping Length Custom Field', 'option label', 'wpsso' );
_x( 'Product Shipping Weight Custom Field', 'option label', 'wpsso' );
_x( 'Product Shipping Width Custom Field', 'option label', 'wpsso' );
_x( 'Product Size Custom Field', 'option label', 'wpsso' );
_x( 'Product Size Group Custom Field', 'option label', 'wpsso' );
_x( 'Product Size System Custom Field', 'option label', 'wpsso' );
_x( 'Product Target Gender Custom Field', 'option label', 'wpsso' );
_x( 'Product Net Weight Custom Field', 'option label', 'wpsso' );
_x( 'Product Net Width Custom Field', 'option label', 'wpsso' );
_x( 'Review Subject Name Custom Field', 'option label', 'wpsso' );
_x( 'Review Subject Desc Custom Field', 'option label', 'wpsso' );
_x( 'Review Rating Custom Field', 'option label', 'wpsso' );
_x( 'Review Rating Alt Name Custom Field', 'option label', 'wpsso' );
_x( 'Same-As URLs Custom Field', 'option label', 'wpsso' );
_x( 'Video URL Custom Field', 'option label', 'wpsso' );
_x( 'Video Embed HTML Custom Field', 'option label', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Alcohol', 'option value', 'wpsso' );
_x( 'Dangerous Good', 'option value', 'wpsso' );
_x( 'Healthcare', 'option value', 'wpsso' );
_x( 'Narcotic', 'option value', 'wpsso' );
_x( 'Reduced Relevance for Children', 'option value', 'wpsso' );
_x( 'Sexual Content', 'option value', 'wpsso' );
_x( 'Tobacco Nicotine', 'option value', 'wpsso' );
_x( 'Unclassified Adult', 'option value', 'wpsso' );
_x( 'Violence', 'option value', 'wpsso' );
_x( 'Weapon', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Adult (13 years old or more)', 'option value', 'wpsso' );
_x( 'Adult', 'option value', 'wpsso' );
_x( 'All Ages (13 years old or more)', 'option value', 'wpsso' );
_x( 'All Ages', 'option value', 'wpsso' );
_x( 'Infant (3–12 months old)', 'option value', 'wpsso' );
_x( 'Infant', 'option value', 'wpsso' );
_x( 'Kids (5–13 years old)', 'option value', 'wpsso' );
_x( 'Kids', 'option value', 'wpsso' );
_x( 'Newborn (0-3 months old)', 'option value', 'wpsso' );
_x( 'Newborn', 'option value', 'wpsso' );
_x( 'Teen (13 years old or more)', 'option value', 'wpsso' );
_x( 'Teen', 'option value', 'wpsso' );
_x( 'Toddler (1–5 years old)', 'option value', 'wpsso' );
_x( 'Toddler', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Audiobook', 'option value', 'wpsso' );
_x( 'eBook', 'option value', 'wpsso' );
_x( 'Graphic Novel', 'option value', 'wpsso' );
_x( 'Hardcover', 'option value', 'wpsso' );
_x( 'Paperback', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Full Time', 'option value', 'wpsso' );
_x( 'Part Time', 'option value', 'wpsso' );
_x( 'Contractor', 'option value', 'wpsso' );
_x( 'Temporary', 'option value', 'wpsso' );
_x( 'Intern', 'option value', 'wpsso' );
_x( 'Volunteer', 'option value', 'wpsso' );
_x( 'Per Diem', 'option value', 'wpsso' );
_x( 'Other', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'A+++', 'option value', 'wpsso' );
_x( 'A++', 'option value', 'wpsso' );
_x( 'A+', 'option value', 'wpsso' );
_x( 'A', 'option value', 'wpsso' );
_x( 'B', 'option value', 'wpsso' );
_x( 'C', 'option value', 'wpsso' );
_x( 'D', 'option value', 'wpsso' );
_x( 'E', 'option value', 'wpsso' );
_x( 'F', 'option value', 'wpsso' );
_x( 'G', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Mixed', 'option value', 'wpsso' );
_x( 'Online', 'option value', 'wpsso' );
_x( 'Physical Location', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Cancelled', 'option value', 'wpsso' );
_x( 'Moved Online', 'option value', 'wpsso' );
_x( 'Postponed', 'option value', 'wpsso' );
_x( 'Rescheduled', 'option value', 'wpsso' );
_x( 'Scheduled', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Back Order', 'option value', 'wpsso' );
_x( 'Discontinued', 'option value', 'wpsso' );
_x( 'In Stock', 'option value', 'wpsso' );
_x( 'In Store Only', 'option value', 'wpsso' );
_x( 'Limited Availability', 'option value', 'wpsso' );
_x( 'Online Only', 'option value', 'wpsso' );
_x( 'Out Of Stock', 'option value', 'wpsso' );
_x( 'Pre-Order', 'option value', 'wpsso' );
_x( 'Pre-Sale', 'option value', 'wpsso' );
_x( 'Sold Out', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Damaged', 'option value', 'wpsso' );
_x( 'New', 'option value', 'wpsso' );
_x( 'Refurbished', 'option value', 'wpsso' );
_x( 'Used', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Telecommute (100% Remote)', 'option value', 'wpsso' );
_x( 'Telecommute', 'option value', 'wpsso' );
_x( 'Limited Return Window', 'option value', 'wpsso' );
_x( 'Not Permitted', 'option value', 'wpsso' );
_x( 'Unlimited Window', 'option value', 'wpsso' );
_x( 'Unspecified', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Invoice Price', 'option value', 'wpsso' );
_x( 'List Price', 'option value', 'wpsso' );
_x( 'Manufacturer Suggested Retail Price', 'option value', 'wpsso' );
_x( 'Minimum Advertised Price', 'option value', 'wpsso' );
_x( 'Sale Price', 'option value', 'wpsso' );
_x( 'Suggested Retail Price', 'option value', 'wpsso' );
_x( 'Free Return', 'option value', 'wpsso' );
_x( 'Customer Pays Shipping', 'option value', 'wpsso' );
_x( 'Return Has Shipping Fees', 'option value', 'wpsso' );
_x( 'At Kiosk', 'option value', 'wpsso' );
_x( 'By Mail', 'option value', 'wpsso' );
_x( 'In Store', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Regular', 'option value', 'wpsso' );
_x( 'Petite', 'option value', 'wpsso' );
_x( 'Plus', 'option value', 'wpsso' );
_x( 'Tall', 'option value', 'wpsso' );
_x( 'Big', 'option value', 'wpsso' );
_x( 'Maternity', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'AU', 'option value', 'wpsso' );
_x( 'BR', 'option value', 'wpsso' );
_x( 'CN', 'option value', 'wpsso' );
_x( 'DE', 'option value', 'wpsso' );
_x( 'EU', 'option value', 'wpsso' );
_x( 'FR', 'option value', 'wpsso' );
_x( 'IT', 'option value', 'wpsso' );
_x( 'JP', 'option value', 'wpsso' );
_x( 'MX', 'option value', 'wpsso' );
_x( 'UK', 'option value', 'wpsso' );
_x( 'US', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'None', 'option value', 'wpsso' );
_x( 'Female', 'option value', 'wpsso' );
_x( 'Male', 'option value', 'wpsso' );
_x( 'Unisex', 'option value', 'wpsso' );
_x( 'Development and Up', 'option value', 'wpsso' );
_x( 'Alpha and Up', 'option value', 'wpsso' );
_x( 'Beta and Up', 'option value', 'wpsso' );
_x( 'Release Candidate and Up', 'option value', 'wpsso' );
_x( 'Stable / Production', 'option value', 'wpsso' );
