<?php die( 'These aren\'t the droids you\'re looking for.' );

// Extract of translatable strings from lib/com/.
__( '%s Notice', 'wpsso' );
__( 'Notice', 'wpsso' );
__( 'Error retrieving %1$s for caching (after %2$.3f seconds).', 'wpsso' );
__( 'Error retrieving %1$s for caching.', 'wpsso' );
__( 'cURL error code %1$d %2$s.', 'wpsso' );
__( 'SSL verification failed with code %1$d.', 'wpsso' );
__( 'HTTP connection returned code %1$d.', 'wpsso' );
__( 'The PHP "%s" setting is enabled - the PHP cURL library cannot follow URL redirects.', 'wpsso' );
__( 'The "%s" setting is deprecated since PHP version 5.3 and removed from PHP since version 5.4.', 'wpsso' );
__( 'Please contact your hosting provider to have this setting disabled or install a newer version of PHP.', 'wpsso' );
__( 'The PHP "%s" setting is enabled - the PHP cURL library cannot follow URL redirects.', 'wpsso' );
__( 'Please contact your hosting provider to have this setting disabled.', 'wpsso' );
__( 'The maximum number of URL redirects (%d) may have been exceeded.', 'wpsso' );
__( 'Additional requests to retrieve this URL will be ignored for another %d second(s).', 'wpsso' );
__( 'Error removing cache file %s.', 'wpsso' );
__( 'PHP cURL library missing - contact your hosting provider to have the cURL library installed.', 'wpsso' );
__( 'Error removing cache file %s.', 'wpsso' );
__( 'Cache file %s is not readable.', 'wpsso' );
__( 'Failed to open the cache file %s for reading.', 'wpsso' );
__( 'Failed to create the %s cache folder.', 'wpsso' );
__( 'Cache folder %s is not writable.', 'wpsso' );
__( 'Failed to open the cache file %s for writing.', 'wpsso' );
__( 'Failed writing data to cache file %s.', 'wpsso' );
_x( 'Post Type', 'option label', 'wpsso' );
_x( 'Post Type', 'option label', 'wpsso' );
_x( 'Taxonomy', 'option label', 'wpsso' );
_x( 'User Profiles', 'option label', 'wpsso' );
_x( 'days', 'option comment', 'wpsso' );
_x( 'hours', 'option comment', 'wpsso' );
_x( 'mins', 'option comment', 'wpsso' );
_x( 'secs', 'option comment', 'wpsso' );
_x( 'crop', 'option comment', 'wpsso' );
_x( 'from', 'option comment', 'wpsso' );
// translators: Please ignore - translation uses a different text domain.
__( 'Media Library' );
// translators: Please ignore - translation uses a different text domain.
__( 'Select Image' );
_x( 'days', 'option comment', 'wpsso' );
_x( 'hours', 'option comment', 'wpsso' );
_x( 'mins', 'option comment', 'wpsso' );
_x( 'secs', 'option comment', 'wpsso' );
__( '%s Notice', 'wpsso' );
__( 'Notice', 'wpsso' );
__( 'Forever', 'wpsso' );
__( 'This notice can be dismissed permanently.', 'wpsso' );
__( 'This notice can be dismissed for %s.', 'wpsso' );
__( 'Edit', 'wpsso' );
__( 'Reference: %s', 'wpsso' );
__( 'The WordPress admin toolbar appears to be disabled (ie. the WordPress <code>%s</code> function returned false).', 'wpsso' );
__( 'As a consequence, showing discreet notices in the admin toolbar is not possible.', 'wpsso' );
__( 'Please diagnose the issue to re-enable the admin toolbar.', 'wpsso' );
__( 'Group name "%s" not found in the Bitly API response data.', 'wpsso' );
__( '%1$s shortener API error: %2$s', 'wpsso' );
__( 'Groups property missing from the Bitly API response data.', 'wpsso' );
__( '%1$s shortener API error: %2$s', 'wpsso' );
__( 'Link property value is empty.', 'wpsso' );
__( '%1$s shortener API error: %2$s', 'wpsso' );
__( '%1$s shortener API error: %2$s', 'wpsso' );
__( '%1$s shortener API error: %2$s', 'wpsso' );
__( 'JSON response decode error code %d.', 'wpsso' );
__( '%1$s shortener API error: %2$s', 'wpsso' );
__( '%s Notice', 'wpsso' );
__( 'Notice', 'wpsso' );
__( 'The "%1$s" hook with priority %2$d in the "%3$s" filter has incorrectly sent output to the webpage.', 'wpsso' );
__( 'Unlike WordPress actions, WordPress filters must always return their text, not echo it to the webpage output.', 'wpsso' );
__( 'Please contact the author of that filter and report this issue as a coding error.', 'wpsso' );
__( 'Incorrect webpage output:', 'wpsso' );
__( 'BEGIN OUTPUT', 'wpsso' );
__( 'END OUTPUT', 'wpsso' );
