<?php die( 'These aren\'t the droids you\'re looking for.' );
// 
// Extract of translatable strings from lib/pro/.
// 
_x( 'Webpage Title Tag', 'option label', 'wpsso' );
_x( 'Use Filtered Content', 'option label', 'wpsso' );
_x( '(recommended - see help text)', 'option comment', 'wpsso' );
_x( 'Use Filtered Excerpt', 'option label', 'wpsso' );
_x( '(recommended - only if using shortcodes in excerpts)', 'option comment', 'wpsso' );
_x( 'Enable Excerpt for Pages', 'option label', 'wpsso' );
_x( 'Enable Tags for Pages', 'option label', 'wpsso' );
_x( 'Add Person Role for New Users', 'option label', 'wpsso' );
_x( 'Inherit Featured Image', 'option label', 'wpsso' );
_x( '(recommended)', 'option comment', 'wpsso' );
_x( 'Inherit Custom Images', 'option label', 'wpsso' );
_x( '(recommended)', 'option comment', 'wpsso' );
_x( 'Image Dimension Checks', 'option label', 'wpsso' );
_x( '(recommended)', 'option comment', 'wpsso' );
_x( 'Prevent Thumbnail Conflicts', 'option label', 'wpsso' );
_x( '(recommended)', 'option comment', 'wpsso' );
_x( 'Upscale Media Library Images', 'option label', 'wpsso' );
_x( 'Maximum Image Upscale Percent', 'option label', 'wpsso' );
_x( 'Plugin and Theme Integration', 'metabox title', 'wpsso' );
_x( 'Speakable CSS Selectors', 'option label', 'wpsso' );
_x( 'Check for Duplicate Meta Tags', 'option label', 'wpsso' );
_x( 'Include VAT in Product Prices', 'option label', 'wpsso' );
_x( 'Import All in One SEO Pack Metadata', 'option label', 'wpsso' );
_x( 'Import Rank Math SEO Metadata', 'option label', 'wpsso' );
_x( 'Import The SEO Framework Metadata', 'option label', 'wpsso' );
_x( 'Import WP Meta SEO Metadata', 'option label', 'wpsso' );
_x( 'Import Yoast SEO Metadata', 'option label', 'wpsso' );
_x( 'Import Yoast SEO Block Attrs', 'option label', 'wpsso' );
_x( 'Title Tag Site Suffix', 'option label', 'wpsso' );
_x( 'Title Tag Tagline Suffix', 'option label', 'wpsso' );
_x( 'Content Image Alt Prefix', 'option label', 'wpsso' );
_x( 'WP Caption Text Prefix', 'option label', 'wpsso' );
_x( 'Comment Title', 'option label', 'wpsso' );
_x( 'Reply Comment Title', 'option label', 'wpsso' );
_x( 'Review Comment Title', 'option label', 'wpsso' );
_x( 'Product Variation Title', 'option label', 'wpsso' );
_x( 'RSS Feed Title', 'option label', 'wpsso' );
_x( '404 Page Title', 'option label', 'wpsso' );
_x( '404 Page Description', 'option label', 'wpsso' );
_x( 'No Title Text', 'option label', 'wpsso' );
_x( 'No Description Text', 'option label', 'wpsso' );
_x( 'Archive Pages', 'metabox title', 'wpsso' );
_x( 'Term Archive Title', 'option label', 'wpsso' );
_x( 'Term Archive Description', 'option label', 'wpsso' );
_x( 'Author Archive Title', 'option label', 'wpsso' );
_x( 'Author Archive Description', 'option label', 'wpsso' );
_x( 'Search Results Title', 'option label', 'wpsso' );
_x( 'Search Results Description', 'option label', 'wpsso' );
_x( 'Year Archive Title', 'option label', 'wpsso' );
_x( 'Year Archive Description', 'option label', 'wpsso' );
_x( 'Month Archive Title', 'option label', 'wpsso' );
_x( 'Month Archive Description', 'option label', 'wpsso' );
_x( 'Day Archive Title', 'option label', 'wpsso' );
_x( 'Day Archive Description', 'option label', 'wpsso' );
_x( 'Post Type Archive Pages', 'metabox title', 'wpsso' );
_x( '%s Archive Page', 'metabox title', 'wpsso' );
_x( 'Archive Page Title', 'option label', 'wpsso' );
_x( 'Archive Page Description', 'option label', 'wpsso' );
_x( 'Open Graph (Facebook and oEmbed)', 'option label', 'wpsso' );
_x( 'Pinterest Pin It', 'option label', 'wpsso' );
_x( 'Schema 1:1 (Google Rich Results)', 'option label', 'wpsso' );
_x( 'Schema 4:3 (Google Rich Results)', 'option label', 'wpsso' );
_x( 'Schema 16:9 (Google Rich Results)', 'option label', 'wpsso' );
_x( 'Schema Thumbnail', 'option label', 'wpsso' );
_x( 'Twitter Summary Card', 'option label', 'wpsso' );
_x( 'Twitter Summary Card Large Image', 'option label', 'wpsso' );
_x( 'Options to Show by Default', 'option label', 'wpsso' );
_x( 'Validators', 'toolbar menu title', 'wpsso' );
_x( 'Show %s Toolbar Menu', 'option label', 'wpsso' );
_x( 'Show %s Menu Items', 'option label', 'wpsso' );
_x( 'Show %s Metabox', 'option label', 'wpsso' );
_x( 'WP List Table Columns', 'option label', 'wpsso' );
_x( 'Open Graph Type Select Format', 'option label', 'wpsso' );
_x( 'Schema Type Select Format', 'option label', 'wpsso' );
_x( 'Gravatar is Default Author Image', 'option label', 'wpsso' );
_x( 'Gravatar Image Size', 'option label', 'wpsso' );
_x( 'Check for Embedded Media', 'option label', 'wpsso' );
_x( 'URL Shortening Service', 'option label', 'wpsso' );
_x( 'Minimum URL Length to Shorten', 'option label', 'wpsso' );
_x( 'characters', 'option comment', 'wpsso' );
_x( 'Use Short URL for WP Shortlink', 'option label', 'wpsso' );
_x( 'Add "%s" HTML Tag', 'option label', 'wpsso' );
_x( 'Bitly (URL Shortener)', 'metabox title', 'wpsso' );
_x( 'Bitly Generic Access Token', 'option label', 'wpsso' );
_x( 'Bitly Short Domain (Optional)', 'option label', 'wpsso' );
_x( 'Bitly Group Name (Optional)', 'option label', 'wpsso' );
_x( 'DLMY.App (URL Shortener)', 'metabox title', 'wpsso' );
_x( 'DLMY.App API Key', 'option label', 'wpsso' );
_x( 'Ow.ly (URL Shortener)', 'metabox title', 'wpsso' );
_x( 'Ow.ly API Key', 'option label', 'wpsso' );
_x( 'YOURLS (URL Shortener)', 'metabox title', 'wpsso' );
_x( 'YOURLS API URL', 'option label', 'wpsso' );
_x( 'YOURLS Username', 'option label', 'wpsso' );
_x( 'YOURLS Password', 'option label', 'wpsso' );
_x( 'YOURLS Token', 'option label', 'wpsso' );
_x( 'Ratings and Reviews Service', 'option label', 'wpsso' );
_x( 'Maximum Number of Reviews', 'option label', 'wpsso' );
_x( 'Maximum Age of Reviews', 'option label', 'wpsso' );
_x( 'months', 'option comment', 'wpsso' );
_x( 'Get Reviews for Post Types', 'option label', 'wpsso' );
_x( 'Shopper Approved (Ratings and Reviews)', 'metabox title', 'wpsso' );
_x( 'Shopper Approved Site ID', 'option label', 'wpsso' );
_x( 'Shopper Approved API Token', 'option label', 'wpsso' );
_x( 'Stamped.io (Ratings and Reviews)', 'metabox title', 'wpsso' );
_x( 'Stamped.io Store Hash', 'option label', 'wpsso' );
_x( 'Stamped.io API Key Public', 'option label', 'wpsso' );
_x( 'Type for Page Homepage', 'option label', 'wpsso' );
_x( 'Type for Posts Homepage', 'option label', 'wpsso' );
_x( 'Type for User Profiles', 'option label', 'wpsso' );
_x( 'Type for Search Results', 'option label', 'wpsso' );
_x( 'Type for Archive Page', 'option label', 'wpsso' );
_x( 'for %s', 'option comment', 'wpsso' );
_x( 'Type by Post Type', 'option label', 'wpsso' );
_x( 'for %s', 'option comment', 'wpsso' );
_x( 'Type by Post Type Archive', 'option label', 'wpsso' );
_x( 'for %s', 'option comment', 'wpsso' );
_x( 'Type by Taxonomy', 'option label', 'wpsso' );
_x( 'Type for Page Homepage', 'option label', 'wpsso' );
_x( 'Type for Posts Homepage', 'option label', 'wpsso' );
_x( 'Type for User Profiles', 'option label', 'wpsso' );
_x( 'Type for Search Results', 'option label', 'wpsso' );
_x( 'Type for Archive Page', 'option label', 'wpsso' );
_x( 'for %s', 'option comment', 'wpsso' );
_x( 'Type by Post Type', 'option label', 'wpsso' );
_x( 'for %s', 'option comment', 'wpsso' );
_x( 'Type by Post Type Archive', 'option label', 'wpsso' );
_x( 'for %s', 'option comment', 'wpsso' );
_x( 'Type by Taxonomy', 'option label', 'wpsso' );
_x( 'Add Article Body Property', 'option label', 'wpsso' );
_x( 'Default Article Section', 'option label', 'wpsso' );
_x( 'Default Book Format', 'option label', 'wpsso' );
_x( 'Add Text Property', 'option label', 'wpsso' );
_x( 'Default Family Friendly', 'option label', 'wpsso' );
_x( 'Default Publisher Org.', 'option label', 'wpsso' );
_x( 'Default Publisher Person', 'option label', 'wpsso' );
_x( 'Default Provider Org.', 'option label', 'wpsso' );
_x( 'Default Provider Person', 'option label', 'wpsso' );
_x( 'Default Funder Org.', 'option label', 'wpsso' );
_x( 'Default Funder Person', 'option label', 'wpsso' );
_x( 'Default Event Attendance', 'option label', 'wpsso' );
_x( 'Default Event Venue', 'option label', 'wpsso' );
_x( 'Default Event Performer Org.', 'option label', 'wpsso' );
_x( 'Default Event Performer Person', 'option label', 'wpsso' );
_x( 'Default Event Organizer Org.', 'option label', 'wpsso' );
_x( 'Default Event Organizer Person', 'option label', 'wpsso' );
_x( 'Default Event Funder Org.', 'option label', 'wpsso' );
_x( 'Default Event Funder Person', 'option label', 'wpsso' );
_x( 'Default Job Hiring Org.', 'option label', 'wpsso' );
_x( 'Default Job Location', 'option label', 'wpsso' );
_x( 'Default Job Location Type', 'option label', 'wpsso' );
_x( 'Default Place Schema Type', 'option label', 'wpsso' );
_x( 'Default Place Country', 'option label', 'wpsso' );
_x( 'Default Place Timezone', 'option label', 'wpsso' );
_x( 'Aggregate Offers by Currency', 'option label', 'wpsso' );
_x( '(not compatible with <a href="%s">price drop appearance</a>)', 'option comment', 'wpsso' );
_x( 'Default Product Return Policy', 'option label', 'wpsso' );
_x( 'Default Product Google Category', 'option label', 'wpsso' );
_x( 'Default Product Price Type', 'option label', 'wpsso' );
_x( 'Default Product Condition', 'option label', 'wpsso' );
_x( 'Default Product Energy Rating Range', 'option label', 'wpsso' );
_x( 'to', 'option comment', 'wpsso' );
_x( 'Default Product Target Gender', 'option label', 'wpsso' );
_x( 'Default Product Size Group', 'option label', 'wpsso' );
_x( 'Default Product Size System', 'option label', 'wpsso' );
_x( 'Default Product Age Group', 'option label', 'wpsso' );
_x( 'Default Product Adult Type', 'option label', 'wpsso' );
_x( 'Default Review Rating Min', 'option label', 'wpsso' );
_x( 'Default Review Rating Max', 'option label', 'wpsso' );
_x( 'Default Subject Schema Type', 'option label', 'wpsso' );
_x( 'Show', 'column title', 'wpsso' );
_x( 'Contact Field ID', 'column title', 'wpsso' );
_x( 'Contact Field Label', 'column title', 'wpsso' );
_x( 'Show', 'column title', 'wpsso' );
_x( 'Contact Field ID', 'column title', 'wpsso' );
_x( 'Contact Field Label', 'column title', 'wpsso' );
_x( 'Show', 'column title', 'wpsso' );
__( 'An SEO plugin has been detected - some basic SEO meta tags have been unchecked and disabled automatically.', 'wpsso' );
_x( 'Maximum Videos to Include', 'option label', 'wpsso' );
_x( 'Include Video Preview Images', 'option label', 'wpsso' );
_x( 'Force Autoplay when Possible', 'option label', 'wpsso' );
_x( 'Check for Embedded Media', 'option label', 'wpsso' );
_x( 'Priority Video Information', 'metabox title', 'wpsso' );
_x( 'Video Embed HTML', 'option label', 'wpsso' );
_x( 'or a Video URL', 'option label', 'wpsso' );
_x( 'Video Information from Video API', 'metabox title', 'wpsso' );
_x( 'Video Name', 'option label', 'wpsso' );
_x( 'Video Description', 'option label', 'wpsso' );
_x( 'Video Stream URL', 'option label', 'wpsso' );
_x( 'Video Dimensions', 'option label', 'wpsso' );
__( 'https://secure.php.net/manual/en/function.simplexml-load-string.php', 'wpsso' );
__( 'The <a href="%1$s">PHP %2$s function</a> is not available.', 'wpsso' );
__( 'Please contact your hosting provider to have the missing PHP function installed.', 'wpsso' );
__( 'https://secure.php.net/manual/en/function.simplexml-load-string.php', 'wpsso' );
__( 'The <a href="%1$s">PHP %2$s function</a> is not available.', 'wpsso' );
__( 'Please contact your hosting provider to have the missing PHP function installed.', 'wpsso' );
__( 'https://secure.php.net/manual/en/function.simplexml-load-string.php', 'wpsso' );
__( 'The <a href="%1$s">PHP %2$s function</a> is not available.', 'wpsso' );
__( 'Please contact your hosting provider to have the missing PHP function installed.', 'wpsso' );
__( 'Failed to upscale image ID %1$s of %2$s by %3$s from %4$s to %5$s for the %6$s image size (exceeds %7$s maximum upscale setting).', 'wpsso' );
__( 'Image ID %1$s of %2$s has been upscaled by %3$s from %4$s to %5$s for the %6$s image size.', 'wpsso' );
__( '%s error:', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'Bitly Generic Access Token', 'option label', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'DLMY.App API Key', 'option label', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'Ow.ly API Key', 'option label', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'YOURLS API URL', 'option label', 'wpsso' );
__( 'Loop detected: YOURLS API URL matches current URL (%s)', 'wpsso' );
__( 'Unable to instantiate the "%s" shortening service.', 'wpsso' );
__( '%s error:', 'wpsso' );
__( 'URL shortening library file for "%s" is missing and required.', 'wpsso' );
_x( 'Shopper Approved (Ratings and Reviews)', 'metabox title', 'wpsso' );
__( 'getting shopper approved ratings and reviews', 'wpsso' );
__( 'There has been a previous error connecting to %s for caching.', 'wpsso' );
__( 'Requests to retrieve and cache this URL are ignored for another %d second(s)', 'wpsso' );
_x( 'Stamped.io (Ratings and Reviews)', 'metabox title', 'wpsso' );
__( 'getting stamp.io ratings and reviews', 'wpsso' );
__( 'There has been a previous error connecting to %s for caching.', 'wpsso' );
__( 'Requests to retrieve and cache this URL are ignored for another %d second(s)', 'wpsso' );
