<?php die( 'These aren\'t the droids you\'re looking for.' );
// 
// Extract of translatable strings from lib/com/education-levels.php.
// 
_x( '[generic]', 'option value', 'wpsso' );
_x( 'generic', 'option value', 'wpsso' );
_x( 'Beginner', 'option value', 'wpsso' );
_x( 'Intermediate', 'option value', 'wpsso' );
_x( 'Advanced', 'option value', 'wpsso' );
_x( 'Algeria', 'option value', 'wpsso' );
_x( 'Lower Secondary School', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Upper Secondary School', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Argentina', 'option value', 'wpsso' );
_x( 'Secondary', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Australia', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( 'Year 8', 'option value', 'wpsso' );
_x( 'Year 9', 'option value', 'wpsso' );
_x( 'Year 10', 'option value', 'wpsso' );
_x( 'Senior Secondary School', 'option value', 'wpsso' );
_x( 'Year 11', 'option value', 'wpsso' );
_x( 'Year 12', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Austria', 'option value', 'wpsso' );
_x( 'Upper Secondary Level', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Tertiary Level', 'option value', 'wpsso' );
_x( 'Azerbaijan', 'option value', 'wpsso' );
_x( 'General Secondary Education', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Full Secondary Education', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Bahrain', 'option value', 'wpsso' );
_x( 'Intermediate Stage', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Stage', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Bangladesh', 'option value', 'wpsso' );
_x( 'Junior Secondary Education', 'option value', 'wpsso' );
_x( 'Grade VIII', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade IX', 'option value', 'wpsso' );
_x( 'Grade X', 'option value', 'wpsso' );
_x( 'Higher Secondary Education', 'option value', 'wpsso' );
_x( 'Grade XI', 'option value', 'wpsso' );
_x( 'Grade XII', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Belarus', 'option value', 'wpsso' );
_x( 'Compulsory Basic Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'General Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Belgium', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '2nd Secondary', 'option value', 'wpsso' );
_x( '3rd Secondary', 'option value', 'wpsso' );
_x( '4th Secondary', 'option value', 'wpsso' );
_x( '5th Secondary', 'option value', 'wpsso' );
_x( '6th Secondary', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Bolivia', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Bosnia and Herzegovina', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Grade 13', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Brazil', 'option value', 'wpsso' );
_x( 'Elementary School', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( '1st Grade (High School)', 'option value', 'wpsso' );
_x( '1st Grade', 'option value', 'wpsso' );
_x( '2nd Grade (High School)', 'option value', 'wpsso' );
_x( '2nd Grade', 'option value', 'wpsso' );
_x( '3rd Grade (High School)', 'option value', 'wpsso' );
_x( '3rd Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Bulgaria', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Canada', 'option value', 'wpsso' );
_x( 'Intermediate Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Chile', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Colombia', 'option value', 'wpsso' );
_x( 'Basic Secondary', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'High School Education', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( 'Tertiary', 'option value', 'wpsso' );
_x( 'Costa Rica', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Croatia', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Cyprus', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Czechia', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Denmark', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Dominican Republic', 'option value', 'wpsso' );
_x( 'Primary School', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( 'Grade 1 (Secondary School)', 'option value', 'wpsso' );
_x( 'Grade 1', 'option value', 'wpsso' );
_x( 'Grade 2 (Secondary School)', 'option value', 'wpsso' );
_x( 'Grade 2', 'option value', 'wpsso' );
_x( 'Grade 3 (Secondary School)', 'option value', 'wpsso' );
_x( 'Grade 3', 'option value', 'wpsso' );
_x( 'Grade 4 (Secondary School)', 'option value', 'wpsso' );
_x( 'Grade 4', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Ecuador', 'option value', 'wpsso' );
_x( 'Secondary', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Egypt', 'option value', 'wpsso' );
_x( 'Preparatory Stage', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'El Salvador', 'option value', 'wpsso' );
_x( '3rd Cycle', 'option value', 'wpsso' );
_x( '7th Grade', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Middle Education', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'England', 'option value', 'wpsso' );
_x( 'Key Stage 3', 'option value', 'wpsso' );
_x( 'Year 9', 'option value', 'wpsso' );
_x( 'Key Stage 4', 'option value', 'wpsso' );
_x( 'Year 10', 'option value', 'wpsso' );
_x( 'Year 11', 'option value', 'wpsso' );
_x( 'Key Stage 5', 'option value', 'wpsso' );
_x( 'Year 12', 'option value', 'wpsso' );
_x( 'Year 13', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Estonia', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( '7th Grade', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Finland', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( '7th Grade', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'France', 'option value', 'wpsso' );
_x( 'Lycée', 'option value', 'wpsso' );
_x( 'Seconde', 'option value', 'wpsso' );
_x( 'Première', 'option value', 'wpsso' );
_x( 'Terminale', 'option value', 'wpsso' );
_x( 'Georgia', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Germany', 'option value', 'wpsso' );
_x( 'Gymnasium', 'option value', 'wpsso' );
_x( '11th Grade (Gymnasium)', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade (Gymnasium)', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( '13th Grade (Gymnasium)', 'option value', 'wpsso' );
_x( '13th Grade', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Ghana', 'option value', 'wpsso' );
_x( 'Junior Secondary School', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Senior Secondary School', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Greece', 'option value', 'wpsso' );
_x( 'Upper Secondary School', 'option value', 'wpsso' );
_x( '1st Grade (Lyceum)', 'option value', 'wpsso' );
_x( '1st Grade', 'option value', 'wpsso' );
_x( '2nd Grade (Lyceum)', 'option value', 'wpsso' );
_x( '2nd Grade', 'option value', 'wpsso' );
_x( '3rd Grade (Lyceum)', 'option value', 'wpsso' );
_x( '3rd Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Guatemala', 'option value', 'wpsso' );
_x( 'Lower Secondary', 'option value', 'wpsso' );
_x( 'Grade 7', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Upper Secondary', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Honduras', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Hong Kong', 'option value', 'wpsso' );
_x( 'Junior Secondary', 'option value', 'wpsso' );
_x( 'Secondary 2', 'option value', 'wpsso' );
_x( 'Secondary 3', 'option value', 'wpsso' );
_x( 'Senior Secondary', 'option value', 'wpsso' );
_x( 'Secondary 4', 'option value', 'wpsso' );
_x( 'Secondary 5', 'option value', 'wpsso' );
_x( 'Secondary 6', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Hungary', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( '13th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Iceland', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( '13th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'India', 'option value', 'wpsso' );
_x( 'Middle Stage', 'option value', 'wpsso' );
_x( 'Class 8', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( 'Class 9', 'option value', 'wpsso' );
_x( 'Class 10', 'option value', 'wpsso' );
_x( 'Senior Secondary School', 'option value', 'wpsso' );
_x( 'Class 11', 'option value', 'wpsso' );
_x( 'Class 12', 'option value', 'wpsso' );
_x( 'Undergraduate College', 'option value', 'wpsso' );
_x( 'Post-Graduate College', 'option value', 'wpsso' );
_x( 'Indonesia', 'option value', 'wpsso' );
_x( 'Middle School', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Iraq', 'option value', 'wpsso' );
_x( 'Intermediate Education', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Preparatory Education', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Ireland', 'option value', 'wpsso' );
_x( 'Senior Cycle', 'option value', 'wpsso' );
_x( 'Transition Year', 'option value', 'wpsso' );
_x( 'Fifth Year', 'option value', 'wpsso' );
_x( 'Sixth Year', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Israel', 'option value', 'wpsso' );
_x( 'Intermediate School', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Italy', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '2nd Upper', 'option value', 'wpsso' );
_x( '3rd Upper', 'option value', 'wpsso' );
_x( '4th Upper', 'option value', 'wpsso' );
_x( '5th Upper', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Jamaica', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Japan', 'option value', 'wpsso' );
_x( 'Lower Secondary School', 'option value', 'wpsso' );
_x( 'Grade 2 (Lower Secondary)', 'option value', 'wpsso' );
_x( 'Grade 2', 'option value', 'wpsso' );
_x( 'Grade 3 (Lower Secondary)', 'option value', 'wpsso' );
_x( 'Grade 3', 'option value', 'wpsso' );
_x( 'Upper Secondary School', 'option value', 'wpsso' );
_x( 'Grade 1 (Upper Secondary)', 'option value', 'wpsso' );
_x( 'Grade 1', 'option value', 'wpsso' );
_x( 'Grade 2 (Upper Secondary)', 'option value', 'wpsso' );
_x( 'Grade 2', 'option value', 'wpsso' );
_x( 'Grade 3 (Upper Secondary)', 'option value', 'wpsso' );
_x( 'Grade 3', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Jordan', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Kazakhstan', 'option value', 'wpsso' );
_x( 'Lower Secondary School', 'option value', 'wpsso' );
_x( 'Grade 7', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Upper Secondary School', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Tertiary Institutions', 'option value', 'wpsso' );
_x( 'Kenya', 'option value', 'wpsso' );
_x( 'Upper Primary', 'option value', 'wpsso' );
_x( 'Standard 8', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( 'Standard 9', 'option value', 'wpsso' );
_x( 'Standard 10', 'option value', 'wpsso' );
_x( 'Standard 11', 'option value', 'wpsso' );
_x( 'Standard 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Kuwait', 'option value', 'wpsso' );
_x( 'Intermediate Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Latvia', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 7', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Senior Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Lebanon', 'option value', 'wpsso' );
_x( 'Intermediate Level', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Libya', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Liechtenstein', 'option value', 'wpsso' );
_x( 'Middle School', 'option value', 'wpsso' );
_x( '7th Grade', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Lithuania', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Luxembourg', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '3 G', 'option value', 'wpsso' );
_x( '2 G', 'option value', 'wpsso' );
_x( '1 G', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Malaysia', 'option value', 'wpsso' );
_x( 'Secondary', 'option value', 'wpsso' );
_x( 'Form 2', 'option value', 'wpsso' );
_x( 'Form 3', 'option value', 'wpsso' );
_x( 'Form 4', 'option value', 'wpsso' );
_x( 'Form 5', 'option value', 'wpsso' );
_x( 'Pre-University', 'option value', 'wpsso' );
_x( 'Lower Form 6', 'option value', 'wpsso' );
_x( 'Upper Form 6', 'option value', 'wpsso' );
_x( 'Post-Secondary Education', 'option value', 'wpsso' );
_x( 'Malta', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Post-Secondary Education', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Postgraduate Education', 'option value', 'wpsso' );
_x( 'Mexico', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Montenegro', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Grade 13', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Morocco', 'option value', 'wpsso' );
_x( 'Lower Secondary', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Upper Secondary', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary', 'option value', 'wpsso' );
_x( 'Nepal', 'option value', 'wpsso' );
_x( 'Secondary', 'option value', 'wpsso' );
_x( 'Year 9', 'option value', 'wpsso' );
_x( 'Year 10', 'option value', 'wpsso' );
_x( 'Senior Higher Secondary', 'option value', 'wpsso' );
_x( 'Year 11', 'option value', 'wpsso' );
_x( 'Year 12', 'option value', 'wpsso' );
_x( 'Netherlands', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '5th Year (HAVO)', 'option value', 'wpsso' );
_x( '5th Year', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'New Zealand', 'option value', 'wpsso' );
_x( 'Year 9-13 Secondary School', 'option value', 'wpsso' );
_x( 'Year 9', 'option value', 'wpsso' );
_x( 'Year 10', 'option value', 'wpsso' );
_x( 'Year 11', 'option value', 'wpsso' );
_x( 'Year 12', 'option value', 'wpsso' );
_x( 'Year 13', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Nicaragua', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Higher Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Nigeria', 'option value', 'wpsso' );
_x( 'Junior Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Senior Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'North Macedonia', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 7', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Northern Ireland', 'option value', 'wpsso' );
_x( 'Key Stage 3', 'option value', 'wpsso' );
_x( 'Year 10', 'option value', 'wpsso' );
_x( 'Key Stage 4', 'option value', 'wpsso' );
_x( 'Year 11', 'option value', 'wpsso' );
_x( 'Year 12', 'option value', 'wpsso' );
_x( 'Key Stage 5', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Norway', 'option value', 'wpsso' );
_x( 'Lower Secondary School', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary School', 'option value', 'wpsso' );
_x( 'VG1', 'option value', 'wpsso' );
_x( 'VG2', 'option value', 'wpsso' );
_x( 'VG3', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Oman', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Pakistan', 'option value', 'wpsso' );
_x( 'Middle School', 'option value', 'wpsso' );
_x( 'Class 8', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( 'Class 9', 'option value', 'wpsso' );
_x( 'Class 10', 'option value', 'wpsso' );
_x( 'Higher Secondary School', 'option value', 'wpsso' );
_x( 'Class 11', 'option value', 'wpsso' );
_x( 'Class 12', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Panama', 'option value', 'wpsso' );
_x( 'First Step of Secondary Level', 'option value', 'wpsso' );
_x( 'Grade Eight', 'option value', 'wpsso' );
_x( 'Grade Nine', 'option value', 'wpsso' );
_x( 'Second Step of Secondary Level', 'option value', 'wpsso' );
_x( 'Grade Ten', 'option value', 'wpsso' );
_x( 'Grade Eleven', 'option value', 'wpsso' );
_x( 'Grade Twelve', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Papua New Guinea', 'option value', 'wpsso' );
_x( 'Middle', 'option value', 'wpsso' );
_x( 'Grade 7', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Secondary', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary', 'option value', 'wpsso' );
_x( 'Paraguay', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Peru', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Philippines', 'option value', 'wpsso' );
_x( 'Junior High School', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Senior High School', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Poland', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 2 (High School)', 'option value', 'wpsso' );
_x( 'Grade 2', 'option value', 'wpsso' );
_x( 'Grade 3 (High School)', 'option value', 'wpsso' );
_x( 'Grade 3', 'option value', 'wpsso' );
_x( 'Grade 4 (High School)', 'option value', 'wpsso' );
_x( 'Grade 4', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Portugal', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( '8th Year', 'option value', 'wpsso' );
_x( '9th Year', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( '10th Year', 'option value', 'wpsso' );
_x( '11th Year', 'option value', 'wpsso' );
_x( '12th Year', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Puerto Rico', 'option value', 'wpsso' );
_x( 'Junior High School', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Qatar', 'option value', 'wpsso' );
_x( 'Preparatory Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Romania', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( 'Class X', 'option value', 'wpsso' );
_x( 'Class XI', 'option value', 'wpsso' );
_x( 'Class XII', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Russia', 'option value', 'wpsso' );
_x( 'Basic General Education', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Secondary General Education', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Postsecondary and Tertiary Education', 'option value', 'wpsso' );
_x( 'Saudi Arabia', 'option value', 'wpsso' );
_x( 'Intermediate Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Scotland', 'option value', 'wpsso' );
_x( 'Secondary School', 'option value', 'wpsso' );
_x( 'Second Year (S2)', 'option value', 'wpsso' );
_x( 'Second Year', 'option value', 'wpsso' );
_x( 'Third Year (S3)', 'option value', 'wpsso' );
_x( 'Third Year', 'option value', 'wpsso' );
_x( 'Fourth Year (S4)', 'option value', 'wpsso' );
_x( 'Fourth Year', 'option value', 'wpsso' );
_x( 'Fifth Year (S5)', 'option value', 'wpsso' );
_x( 'Fifth Year', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Senegal', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Grade 13', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Serbia', 'option value', 'wpsso' );
_x( 'Secondary-High School', 'option value', 'wpsso' );
_x( 'Year 2', 'option value', 'wpsso' );
_x( 'Year 3', 'option value', 'wpsso' );
_x( 'Year 4', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Singapore', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Secondary 1', 'option value', 'wpsso' );
_x( 'Secondary 2', 'option value', 'wpsso' );
_x( 'Secondary 3', 'option value', 'wpsso' );
_x( 'Secondary 4', 'option value', 'wpsso' );
_x( 'Secondary 5', 'option value', 'wpsso' );
_x( 'Post-Secondary Education', 'option value', 'wpsso' );
_x( 'Slovakia', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( '2nd Grade (High School)', 'option value', 'wpsso' );
_x( '2nd Grade', 'option value', 'wpsso' );
_x( '3rd Grade (High School)', 'option value', 'wpsso' );
_x( '3rd Grade', 'option value', 'wpsso' );
_x( '4th Grade (High School)', 'option value', 'wpsso' );
_x( '4th Grade', 'option value', 'wpsso' );
_x( 'Post-Secondary Education', 'option value', 'wpsso' );
_x( 'Slovenia', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Grade 13', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'South Africa', 'option value', 'wpsso' );
_x( 'Senior Phase', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Further Education and Training', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education and Training', 'option value', 'wpsso' );
_x( 'South Korea', 'option value', 'wpsso' );
_x( 'Middle School', 'option value', 'wpsso' );
_x( '3rd Grade', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( '1st Grade', 'option value', 'wpsso' );
_x( '2nd Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Spain', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Tertiary education', 'option value', 'wpsso' );
_x( 'Sri Lanka', 'option value', 'wpsso' );
_x( 'Junior Secondary', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Senior Secondary', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Collegiate', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Grade 13', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Sweden', 'option value', 'wpsso' );
_x( 'Comprehensive School', 'option value', 'wpsso' );
_x( '7th Grade', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( '1st Grade', 'option value', 'wpsso' );
_x( '2nd Grade', 'option value', 'wpsso' );
_x( '3rd Grade', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Switzerland', 'option value', 'wpsso' );
_x( 'Lower Secondary Level', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Upper Secondary Level', 'option value', 'wpsso' );
_x( 'Grade-1', 'option value', 'wpsso' );
_x( 'Grade-2', 'option value', 'wpsso' );
_x( 'Grade-3', 'option value', 'wpsso' );
_x( 'Tertiary Level', 'option value', 'wpsso' );
_x( 'Taiwan', 'option value', 'wpsso' );
_x( 'Junior High School', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Senior High School', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Tanzania', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( 'Grade 7', 'option value', 'wpsso' );
_x( 'Lower Secondary', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Upper Secondary', 'option value', 'wpsso' );
_x( 'University', 'option value', 'wpsso' );
_x( 'Doctorate', 'option value', 'wpsso' );
_x( 'Thailand', 'option value', 'wpsso' );
_x( 'Lower Secondary', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Tunisia', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
_x( 'Türkiye', 'option value', 'wpsso' );
_x( 'Primary Education', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Uganda', 'option value', 'wpsso' );
_x( 'Lower Secondary Education', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Thirteenth Grade', 'option value', 'wpsso' );
_x( 'Post-Secondary Education', 'option value', 'wpsso' );
_x( 'Ukraine', 'option value', 'wpsso' );
_x( 'Secondary Base School', 'option value', 'wpsso' );
_x( '8th Grade', 'option value', 'wpsso' );
_x( '9th Grade', 'option value', 'wpsso' );
_x( 'Secondary Last School', 'option value', 'wpsso' );
_x( '10th Grade', 'option value', 'wpsso' );
_x( '11th Grade', 'option value', 'wpsso' );
_x( '12th Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'United Arab Emirates', 'option value', 'wpsso' );
_x( 'Intermediate Level', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Secondary Level', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'United States', 'option value', 'wpsso' );
_x( 'Middle School', 'option value', 'wpsso' );
_x( 'Eighth Grade', 'option value', 'wpsso' );
_x( 'High School', 'option value', 'wpsso' );
_x( 'Ninth Grade', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'College', 'option value', 'wpsso' );
_x( 'Graduate School', 'option value', 'wpsso' );
_x( 'Venezuela', 'option value', 'wpsso' );
_x( 'Middle Education', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Diversified Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Higher Education School', 'option value', 'wpsso' );
_x( 'Vietnam', 'option value', 'wpsso' );
_x( 'Upper Secondary Education', 'option value', 'wpsso' );
_x( 'Tenth Grade', 'option value', 'wpsso' );
_x( 'Eleventh Grade', 'option value', 'wpsso' );
_x( 'Twelfth Grade', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Wales', 'option value', 'wpsso' );
_x( 'Key Stage 4', 'option value', 'wpsso' );
_x( 'Year 10', 'option value', 'wpsso' );
_x( 'Year 11', 'option value', 'wpsso' );
_x( 'Key Stage 5', 'option value', 'wpsso' );
_x( 'Year 12', 'option value', 'wpsso' );
_x( 'Year 13', 'option value', 'wpsso' );
_x( 'Higher Education', 'option value', 'wpsso' );
_x( 'Yemen', 'option value', 'wpsso' );
_x( 'Basic Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'University Education', 'option value', 'wpsso' );
_x( 'Zimbabwe', 'option value', 'wpsso' );
_x( 'Secondary Education', 'option value', 'wpsso' );
_x( 'Grade 8', 'option value', 'wpsso' );
_x( 'Grade 9', 'option value', 'wpsso' );
_x( 'Grade 10', 'option value', 'wpsso' );
_x( 'Grade 11', 'option value', 'wpsso' );
_x( 'Grade 12', 'option value', 'wpsso' );
_x( 'Grade 13', 'option value', 'wpsso' );
_x( 'Tertiary Education', 'option value', 'wpsso' );
