<?php die( 'These aren\'t the droids you\'re looking for...' );
// extract of translatable text strings from common library classes
__( 'All WordPress filter hooks must return their text, not send it to the webpage output.', 'wpsso' );
__( 'BEGIN OUTPUT', 'wpsso' );
__( 'Cache file %s is not readable.', 'wpsso' );
__( 'Cache folder %s is not writable.', 'wpsso' );
__( 'edit', 'wpsso' );
__( 'END OUTPUT', 'wpsso' );
__( 'Error connecting to %1$s for caching (HTTP code %2$d).', 'wpsso' );
__( 'Error removing cache file %s.', 'wpsso' );
__( 'Failed to create the %s cache folder.', 'wpsso' );
__( 'Failed to open the cache file %s for reading.', 'wpsso' );
__( 'Failed to open the cache file %s for writing.', 'wpsso' );
__( 'Forever', 'wpsso' );
__( 'Incorrect webpage output:', 'wpsso' );
__( 'Notice', 'wpsso' );
__( 'PHP cURL library is missing &mdash; contact your hosting provider to have the cURL library installed.', 'wpsso' );
__( 'Please contact the author of that filter hook and report this issue as a coding error.', 'wpsso' );
__( 'Please contact your hosting provider to have this setting disabled or install a newer version of PHP.', 'wpsso' );
__( 'Please contact your hosting provider to have this setting disabled.', 'wpsso' );
__( 'Reference: %s', 'wpsso' );
__( 'Requests to cache this URL will be ignored for %d second(s).', 'wpsso' );
__( '%s Notice', 'wpsso' );
__( 'The "%1$s" hook with priority %2$d in the "%3$s" filter has incorrectly sent output to the webpage.', 'wpsso' );
__( 'The maximum number of URL redirects (%d) may have been exceeded.', 'wpsso' );
__( 'The PHP "%s" setting is enabled &mdash; the PHP cURL library cannot follow URL redirects.', 'wpsso' );
__( 'The "%s" setting is deprecated since PHP version 5.3 and removed from PHP since version 5.4.', 'wpsso' );
__( 'This notice can be dismissed for %s.', 'wpsso' );
__( 'This notice can be dismissed permanently.', 'wpsso' );
_x( 'error', 'notification type', 'wpsso' );
_x( 'warning', 'notification type', 'wpsso' );
