<?php die( 'These aren\'t the droids you\'re looking for...' );
// extract of translatable text strings from static config array(s)
_x( 'Advanced Settings', 'lib file description', 'wpsso' );
_x( 'All Options', 'option value', 'wpsso' );
_x( 'Alpha and Up', 'option value', 'wpsso' );
_x( 'Automatically generate complete and accurate meta tags + Schema markup from your content for social media optimization (SMO) and SEO.', 'plugin description', 'wpsso' );
_x( 'Basic Options', 'option value', 'wpsso' );
_x( 'Beta and Up', 'option value', 'wpsso' );
_x( 'Bitly (suggested)', 'option value', 'wpsso' );
_x( 'Bottom', 'option value', 'wpsso' );
_x( 'Center', 'option value', 'wpsso' );
_x( '<color>Plugin Setup Guide and Other Notes</color>', 'lib file description', 'wpsso' );
_x( 'Damaged', 'option value', 'wpsso' );
_x( '(default)', 'option value', 'wpsso' );
_x( 'Development and Up', 'option value', 'wpsso' );
_x( 'Discontinued', 'option value', 'wpsso' );
_x( 'Display Name', 'option value', 'wpsso' );
_x( 'Essential Settings', 'lib file description', 'wpsso' );
_x( 'Every day', 'option value', 'wpsso' );
_x( 'Every five days', 'option value', 'wpsso' );
_x( 'Every four days', 'option value', 'wpsso' );
_x( 'Every month', 'option value', 'wpsso' );
_x( 'Every six days', 'option value', 'wpsso' );
_x( 'Every three days', 'option value', 'wpsso' );
_x( 'Every three weeks', 'option value', 'wpsso' );
_x( 'Every two days', 'option value', 'wpsso' );
_x( 'Every two weeks', 'option value', 'wpsso' );
_x( 'Every week', 'option value', 'wpsso' );
_x( 'Excerpt Only', 'option value', 'wpsso' );
_x( 'Extension Plugins and Pro Licenses', 'lib file description', 'wpsso' );
_x( 'Facebook Business Page URL', 'option value', 'wpsso' );
_x( 'First and Last Names', 'option value', 'wpsso' );
_x( 'Footer', 'option value', 'wpsso' );
_x( 'Force this value', 'option value', 'wpsso' );
_x( 'Friday', 'option value', 'wpsso' );
_x( 'General Settings', 'lib file description', 'wpsso' );
_x( 'Google+ Business Page URL', 'option value', 'wpsso' );
_x( 'Google', 'option value', 'wpsso' );
_x( 'Header', 'option value', 'wpsso' );
_x( 'If value is empty', 'option value', 'wpsso' );
_x( 'Image URL Custom Field', 'option label', 'wpsso' );
_x( 'Instagram Business URL', 'option value', 'wpsso' );
_x( 'In Stock', 'option value', 'wpsso' );
_x( 'In Store Only', 'option value', 'wpsso' );
_x( 'Left', 'option value', 'wpsso' );
_x( 'Limited Availability', 'option value', 'wpsso' );
_x( 'LinkedIn Company Page URL', 'option value', 'wpsso' );
_x( 'Monday', 'option value', 'wpsso' );
_x( 'Myspace Business Page URL', 'option value', 'wpsso' );
_x( 'New activation', 'option value', 'wpsso' );
_x( 'New', 'option value', 'wpsso' );
_x( 'Nickname', 'option value', 'wpsso' );
_x( '(no images)', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'No', 'option value', 'wpsso' );
_x( '(no videos)', 'option value', 'wpsso' );
_x( 'Online Only', 'option value', 'wpsso' );
_x( '(option disabled)', 'option value', 'wpsso' );
_x( 'Out of Stock', 'option value', 'wpsso' );
_x( 'Ow.ly', 'option value', 'wpsso' );
_x( 'Pinterest Company Page URL', 'option value', 'wpsso' );
_x( 'Plugin Dashboard and Features Status', 'lib file description', 'wpsso' );
_x( 'Pre-Order', 'option value', 'wpsso' );
_x( 'Product Availability Custom Field', 'option label', 'wpsso' );
_x( 'Product Condition Custom Field', 'option label', 'wpsso' );
_x( 'Product Currency Custom Field', 'option label', 'wpsso' );
_x( 'Product Price Custom Field', 'option label', 'wpsso' );
_x( 'Public Holidays', 'option value', 'wpsso' );
_x( 'Recipe Ingredients Custom Field', 'option label', 'wpsso' );
_x( 'Recipe Instructions Custom Field', 'option label', 'wpsso' );
_x( 'Refurbished', 'option value', 'wpsso' );
_x( 'Release Candidate and Up', 'option value', 'wpsso' );
_x( 'Right', 'option value', 'wpsso' );
_x( 'Saturday', 'option value', 'wpsso' );
_x( '(settings value)', 'option value', 'wpsso' );
_x( 'Social and SEO Image Dimensions', 'lib file description', 'wpsso' );
_x( 'Sold Out', 'option value', 'wpsso' );
_x( 'SoundCloud Business URL', 'option value', 'wpsso' );
_x( 'SSO Desc', 'column header', 'wpsso' );
_x( 'SSO Img', 'column header', 'wpsso' );
_x( 'SSO', 'menu label', 'wpsso' );
_x( 'SSO Schema', 'column header', 'wpsso' );
_x( 'Stable / Production', 'option value', 'wpsso' );
_x( 'Sunday', 'option value', 'wpsso' );
_x( 'Thursday', 'option value', 'wpsso' );
_x( 'TinyURL', 'option value', 'wpsso' );
_x( 'Title and Excerpt', 'option value', 'wpsso' );
_x( 'Title Only', 'option value', 'wpsso' );
_x( 'Top', 'option value', 'wpsso' );
_x( 'Tuesday', 'option value', 'wpsso' );
_x( 'Tumblr Business Page URL', 'option value', 'wpsso' );
_x( 'Twitter Business @username', 'option value', 'wpsso' );
_x( 'Used', 'option value', 'wpsso' );
_x( 'User Profile Contact Methods', 'lib file description', 'wpsso' );
_x( 'Video Embed HTML Custom Field', 'option label', 'wpsso' );
_x( 'Video URL Custom Field', 'option label', 'wpsso' );
_x( 'Website Social Pages and Accounts', 'lib file description', 'wpsso' );
_x( 'Wednesday', 'option value', 'wpsso' );
_x( 'WPSSO extension to add a user locale / language / region selector in the WordPress admin back-end and front-end toolbar menus.', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to add CSS Twitter-style quoted text with a Tweet share link to post and page content (uses easily customized CSS).', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to add ratings and reviews for WordPress comments, with Aggregate Rating meta tags and optional Schema Review markup.', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to add Ridiculously Responsive (SVG) Social Sharing Buttons in your content, excerpts, CSS sidebar, widget, shortcode, etc.', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to add Schema JSON-LD / SEO markup for Articles, Events, Local Business, Products, Recipes, Reviews + many more.', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to add Social Sharing Buttons with support for hashtags, short URLs, bbPress, BuddyPress, WooCommerce, and much more.', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to manage Organizations and additional Schema Article / Event properties (Publisher, Organizer, Performer, etc.).', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to provide Apple Store / iTunes and Google Play App meta tags for Apple\'s mobile Safari and Twitter\'s App Card.', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to provide Pinterest Place, Facebook / Open Graph Location, Schema Local Business, and Local SEO meta tags.', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to provide updates for the WPSSO Pro plugin and its Pro extensions.', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to remove outdated / incomplete Schema Microdata, leaving the Google recommended Schema JSON-LD markup untouched.', 'plugin description', 'wpsso' );
_x( 'Yes', 'option value', 'wpsso' );
_x( 'YOURLS', 'option value', 'wpsso' );
_x( 'Your Social Settings', 'lib file description', 'wpsso' );
_x( 'YouTube Business Channel URL', 'option value', 'wpsso' );
?>
