<?php die( 'These aren\'t the droids you\'re looking for...' );
// an extract of translatable text strings from the static config array
_x( 'Advanced', 'lib file description', 'wpsso' );
_x( 'All Options', 'form option value', 'wpsso' );
_x( 'Basic Options', 'form option value', 'wpsso' );
_x( 'Bit.ly', 'form option value', 'wpsso' );
_x( 'Bottom', 'form option value', 'wpsso' );
_x( 'Center', 'form option value', 'wpsso' );
_x( 'Default value', 'form option value', 'wpsso' );
_x( 'Display Name', 'form option value', 'wpsso' );
_x( 'Excerpt Only', 'form option value', 'wpsso' );
_x( 'First and Last Names', 'form option value', 'wpsso' );
_x( 'Footer', 'form option value', 'wpsso' );
_x( 'Force this value', 'form option value', 'wpsso' );
_x( 'General', 'lib file description', 'wpsso' );
_x( 'Goo.gl', 'form option value', 'wpsso' );
_x( 'Header', 'form option value', 'wpsso' );
_x( 'If value is empty', 'form option value', 'wpsso' );
_x( 'Improve WordPress editing and publishing for a better presentation on all social websites - no matter how your content is shared or re-shared!', 'plugin description', 'wpsso' );
_x( 'Left', 'form option value', 'wpsso' );
_x( 'Nickname', 'form option value', 'wpsso' );
_x( 'No', 'form option value', 'wpsso' );
_x( '[none]', 'form option value', 'wpsso' );
_x( 'Read Me', 'lib file description', 'wpsso' );
_x( 'Right', 'form option value', 'wpsso' );
_x( 'Setup Guide', 'lib file description', 'wpsso' );
_x( 'Social Image Dimensions', 'lib file description', 'wpsso' );
_x( '<span>Extension Plugins</span> and Pro Licenses', 'lib file description', 'wpsso' );
_x( 'Title and Excerpt', 'form option value', 'wpsso' );
_x( 'Title Only', 'form option value', 'wpsso' );
_x( 'Top', 'form option value', 'wpsso' );
_x( 'User Profile Contact Methods', 'lib file description', 'wpsso' );
_x( 'Website / Business Social Accounts', 'lib file description', 'wpsso' );
_x( 'WPSSO extension to add Ridiculously Responsive (SVG) Social Sharing Buttons in your content, excerpts, CSS sidebar, widget, shortcode, etc.', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to provide Apple Store / iTunes and Google Play App meta tags for Apple\'s mobile Safari and Twitter\'s App Card.', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to provide Facebook / Open Graph "Location" and Pinterest "Place" Rich Pin meta tags.', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to provide fast and accurate Social Sharing Buttons, including support for hashtags, short URLs, bbPress, BuddyPress, and WooCommerce.', 'plugin description', 'wpsso' );
_x( 'WPSSO extension to provide updates for the WordPress Social Sharing Optimization (WPSSO) Pro plugin and its Pro extensions.', 'plugin description', 'wpsso' );
_x( 'Yes', 'form option value', 'wpsso' );
?>
