<?php die( 'These aren\'t the droids you\'re looking for.' );

/**
 * Extract of translatable text strings from the static config array.
 */
_x( 'Premium', 'distribution name', 'wpsso' );
_x( 'Standard', 'distribution name', 'wpsso' );
_x( 'Image:', 'option value', 'wpsso' );
_x( 'Caption:', 'option value', 'wpsso' );
_x( 'Facebook User URL', 'option value', 'wpsso' );
_x( 'Instagram URL', 'option value', 'wpsso' );
_x( 'LinkedIn URL', 'option value', 'wpsso' );
_x( 'Myspace URL', 'option value', 'wpsso' );
_x( 'Pinterest URL', 'option value', 'wpsso' );
_x( 'Soundcloud URL', 'option value', 'wpsso' );
_x( 'Skype Username', 'option value', 'wpsso' );
_x( 'Tumblr URL', 'option value', 'wpsso' );
_x( 'Twitter @username', 'option value', 'wpsso' );
_x( 'Wikipedia Page URL', 'option value', 'wpsso' );
_x( 'YouTube Channel URL', 'option value', 'wpsso' );
_x( 'Your SSO', 'lib file description', 'wpsso' );
_x( 'Advanced Settings', 'lib file description', 'wpsso' );
_x( 'Complementary Add-ons', 'lib file description', 'wpsso' );
_x( 'Premium Licenses', 'lib file description', 'wpsso' );
_x( 'Essential Settings', 'lib file description', 'wpsso' );
_x( 'Setup Guide', 'lib file description', 'wpsso' );
_x( 'Dashboard', 'lib file description', 'wpsso' );
_x( 'General Settings', 'lib file description', 'wpsso' );
_x( 'Advanced Settings', 'lib file description', 'wpsso' );
_x( 'Social Pages', 'lib file description', 'wpsso' );
_x( 'Image Sizes', 'lib file description', 'wpsso' );
_x( 'Complementary Add-ons', 'lib file description', 'wpsso' );
_x( 'Premium Licenses', 'lib file description', 'wpsso' );
_x( 'Tools and Actions', 'lib file description', 'wpsso' );
_x( 'Add a Person', 'lib file description', 'wpsso' );
_x( 'Make sure your content looks great on all social and search sites - no matter how your URLs are crawled, shared, re-shared, posted, or embedded.', 'plugin description', 'wpsso' );
_x( 'Apple Store / iTunes and Google Play App Meta Tags for Apple\'s mobile Safari Banner and Twitter\'s App Card.', 'plugin description', 'wpsso' );
_x( 'Schema BreadcrumbList Markup in JSON-LD for Better Google Rich Results with Structured Data.', 'plugin description', 'wpsso' );
_x( 'Create FAQ and Question / Answer Pages with Optional Shortcodes to Include FAQs and Questions in your Content.', 'plugin description', 'wpsso' );
_x( 'Inherit the Featured and Custom Images from Parents for Posts, Pages, Custom Post Types, Categories, Tags, and Custom Taxonomies.', 'plugin description', 'wpsso' );
_x( 'Google Rich Results and Structured Data for Articles, Carousels (aka Item Lists), Claim Reviews, Events, FAQ Pages, How-Tos, Images, Local Business / Local SEO, Organizations, Products, Ratings, Recipes, Restaurants, Reviews, Videos, and More.', 'plugin description', 'wpsso' );
_x( 'Customize the Home Page Schema Organization Markup and Manage Additional Organizations (Publisher, Organizer, etc.).', 'plugin description', 'wpsso' );
_x( 'Manage Places and Local SEO for Facebook / Open Graph, Pinterest, Google Local Business and Schema Place.', 'plugin description', 'wpsso' );
_x( 'Ratings and Reviews for WordPress Comments with Schema Aggregate Rating and Schema Review Markup.', 'plugin description', 'wpsso' );
_x( 'Enhances the WordPress REST API Post, Term and User Queries with an Array of Social Meta Tags, SEO HTML Tags and Schema JSON-LD Markup.', 'plugin description', 'wpsso' );
_x( 'Ridiculously Responsive (SVG) Social Sharing Buttons for your Content, Excerpts, CSS Sidebar, Widget, Shortcode, Templates, and Editor.', 'plugin description', 'wpsso' );
_x( 'Remove Outdated / Incorrect Microdata from Theme Templates for Better Google Rich Results with Schema JSON-LD Markup.', 'plugin description', 'wpsso' );
_x( 'Improves the Look of Thumbnails and Resized Images for Better Click-Through-Rates on Social and Search Sites.', 'plugin description', 'wpsso' );
_x( 'Quick and Easy Locale / Language / Region Selector for the WordPress Admin Toolbar.', 'plugin description', 'wpsso' );
_x( 'Update Manager for the WPSSO Core Premium Plugin and its Premium Complementary Add-ons.', 'plugin description', 'wpsso' );
_x( 'GTIN, GTIN-8, GTIN-12 (UPC), GTIN-13 (EAN), GTIN-14, ISBN, MPN, Depth, and Volume for WooCommerce Products and Variations.', 'plugin description', 'wpsso' );
_x( 'SSO', 'menu title', 'wpsso' );
_x( 'Document SSO', 'metabox title', 'wpsso' );
_x( 'Schema', 'column header', 'wpsso' );
_x( 'OG Type', 'column header', 'wpsso' );
_x( 'SSO Image', 'column header', 'wpsso' );
_x( 'SSO Desc', 'column header', 'wpsso' );
_x( 'Form Selects', 'option label', 'wpsso' );
_x( 'Head Markup', 'option label', 'wpsso' );
_x( 'Image URL Info', 'option label', 'wpsso' );
_x( 'Shortened URLs', 'option label', 'wpsso' );
_x( 'Schema Types', 'option label', 'wpsso' );
_x( 'All Transients', 'option label', 'wpsso' );
_x( 'Filtered Content', 'option label', 'wpsso' );
_x( 'All WP Objects', 'option label', 'wpsso' );
_x( 'Yes', 'option value', 'wpsso' );
_x( 'No', 'option value', 'wpsso' );
_x( 'True', 'option value', 'wpsso' );
_x( 'False', 'option value', 'wpsso' );
_x( 'On', 'option value', 'wpsso' );
_x( 'Off', 'option value', 'wpsso' );
_x( 'Sunday', 'option value', 'wpsso' );
_x( 'Monday', 'option value', 'wpsso' );
_x( 'Tuesday', 'option value', 'wpsso' );
_x( 'Wednesday', 'option value', 'wpsso' );
_x( 'Thursday', 'option value', 'wpsso' );
_x( 'Friday', 'option value', 'wpsso' );
_x( 'Saturday', 'option value', 'wpsso' );
_x( 'Public Holidays', 'option value', 'wpsso' );
_x( 'Hour', 'option value', 'wpsso' );
_x( 'Day', 'option value', 'wpsso' );
_x( 'Week', 'option value', 'wpsso' );
_x( 'Month', 'option value', 'wpsso' );
_x( 'Year', 'option value', 'wpsso' );
_x( '(default)', 'option value', 'wpsso' );
_x( '(no images)', 'option value', 'wpsso' );
_x( '(no videos)', 'option value', 'wpsso' );
_x( '(settings value)', 'option value', 'wpsso' );
_x( '(option disabled)', 'option value', 'wpsso' );
_x( 'default is %s', 'option value', 'wpsso' );
_x( 'checked', 'option value', 'wpsso' );
_x( 'unchecked', 'option value', 'wpsso' );
_x( 'at', 'option value', 'wpsso' );
_x( 'tz', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Header', 'option value', 'wpsso' );
_x( 'Footer', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Title Only', 'option value', 'wpsso' );
_x( 'Excerpt Only', 'option value', 'wpsso' );
_x( 'Title and Excerpt', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Organization', 'option value', 'wpsso' );
_x( 'Person', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'First and Last Names', 'option value', 'wpsso' );
_x( 'Display Name', 'option value', 'wpsso' );
_x( 'Nickname', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( '[Custom Address]', 'option value', 'wpsso' );
_x( '[New Address]', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( '[New Organization]', 'option value', 'wpsso' );
_x( '[WebSite Organization]', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( '[Custom Place]', 'option value', 'wpsso' );
_x( '[New Place]', 'option value', 'wpsso' );
_x( 'Basic Options', 'option value', 'wpsso' );
_x( 'All Options', 'option value', 'wpsso' );
_x( 'SSO Toolbar Notices', 'option value', 'wpsso' );
_x( 'WP Admin Notices', 'option value', 'wpsso' );
_x( 'New activation', 'option value', 'wpsso' );
_x( 'If value is empty', 'option value', 'wpsso' );
_x( 'Force this value', 'option value', 'wpsso' );
_x( 'Left', 'option value', 'wpsso' );
_x( 'Center', 'option value', 'wpsso' );
_x( 'Right', 'option value', 'wpsso' );
_x( 'Top', 'option value', 'wpsso' );
_x( 'Center', 'option value', 'wpsso' );
_x( 'Bottom', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Categories', 'option value', 'wpsso' );
_x( 'Parents', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Parents', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Bitly (suggested)', 'option value', 'wpsso' );
_x( 'DLMY.App', 'option value', 'wpsso' );
_x( 'Ow.ly', 'option value', 'wpsso' );
_x( 'TinyURL', 'option value', 'wpsso' );
_x( 'YOURLS', 'option value', 'wpsso' );
_x( 'Facebook Business Page URL', 'option value', 'wpsso' );
_x( 'Instagram Business Profile URL', 'option value', 'wpsso' );
_x( 'LinkedIn Business Page URL', 'option value', 'wpsso' );
_x( 'Myspace Business Page URL', 'option value', 'wpsso' );
_x( 'Pinterest Business Page URL', 'option value', 'wpsso' );
_x( 'Soundcloud Business Page URL', 'option value', 'wpsso' );
_x( 'Twitter Business @username', 'option value', 'wpsso' );
_x( 'Tumblr Business Page URL', 'option value', 'wpsso' );
_x( 'Wikipedia Organization Page URL', 'option value', 'wpsso' );
_x( 'YouTube Business Channel URL', 'option value', 'wpsso' );
_x( 'Facebook Videos', 'option value', 'wpsso' );
_x( 'Slideshare Presentations', 'option value', 'wpsso' );
_x( 'Soundcloud Tracks', 'option value', 'wpsso' );
_x( 'Vimeo Videos', 'option value', 'wpsso' );
_x( 'Wistia Videos', 'option value', 'wpsso' );
_x( 'WordPress Video Shortcode', 'option value', 'wpsso' );
_x( 'YouTube Videos and Playlists', 'option value', 'wpsso' );
_x( 'Microdata Type URLs Custom Field', 'option label', 'wpsso' );
_x( 'Book ISBN Custom Field', 'option label', 'wpsso' );
_x( 'How-To Steps Custom Field', 'option label', 'wpsso' );
_x( 'How-To Supplies Custom Field', 'option label', 'wpsso' );
_x( 'How-To Tools Custom Field', 'option label', 'wpsso' );
_x( 'Image URL Custom Field', 'option label', 'wpsso' );
_x( 'Product Availability Custom Field', 'option label', 'wpsso' );
_x( 'Product Brand Custom Field', 'option label', 'wpsso' );
_x( 'Product Type ID Custom Field', 'option label', 'wpsso' );
_x( 'Product Color Custom Field', 'option label', 'wpsso' );
_x( 'Product Condition Custom Field', 'option label', 'wpsso' );
_x( 'Product Currency Custom Field', 'option label', 'wpsso' );
_x( 'Product Depth Custom Field', 'option label', 'wpsso' );
_x( 'Product Fluid Volume Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN-14 Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN-13 (EAN) Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN-12 (UPC) Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN-8 Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN Custom Field', 'option label', 'wpsso' );
_x( 'Product Height Custom Field', 'option label', 'wpsso' );
_x( 'Product ISBN Custom Field', 'option label', 'wpsso' );
_x( 'Product Length Custom Field', 'option label', 'wpsso' );
_x( 'Product Material Custom Field', 'option label', 'wpsso' );
_x( 'Product MPN Custom Field', 'option label', 'wpsso' );
_x( 'Product Price Custom Field', 'option label', 'wpsso' );
_x( 'Product Size Custom Field', 'option label', 'wpsso' );
_x( 'Product SKU Custom Field', 'option label', 'wpsso' );
_x( 'Product Target Gender Custom Field', 'option label', 'wpsso' );
_x( 'Product Weight Custom Field', 'option label', 'wpsso' );
_x( 'Product Width Custom Field', 'option label', 'wpsso' );
_x( 'Recipe Ingredients Custom Field', 'option label', 'wpsso' );
_x( 'Recipe Instructions Custom Field', 'option label', 'wpsso' );
_x( 'Same-As URLs Custom Field', 'option label', 'wpsso' );
_x( 'Video URL Custom Field', 'option label', 'wpsso' );
_x( 'Video Embed HTML Custom Field', 'option label', 'wpsso' );
_x( 'Brand Attribute Name', 'option label', 'wpsso' );
_x( 'Color Attribute Name', 'option label', 'wpsso' );
_x( 'Condition Attribute Name', 'option label', 'wpsso' );
_x( 'Depth Attribute Name', 'option label', 'wpsso' );
_x( 'Fluid Volume Attribute Name', 'option label', 'wpsso' );
_x( 'GTIN-14 Attribute Name', 'option label', 'wpsso' );
_x( 'GTIN-13 (EAN) Attribute Name', 'option label', 'wpsso' );
_x( 'GTIN-12 (UPC) Attribute Name', 'option label', 'wpsso' );
_x( 'GTIN-8 Attribute Name', 'option label', 'wpsso' );
_x( 'GTIN Attribute Name', 'option label', 'wpsso' );
_x( 'ISBN Attribute Name', 'option label', 'wpsso' );
_x( 'Material Attribute Name', 'option label', 'wpsso' );
_x( 'MPN Attribute Name', 'option label', 'wpsso' );
_x( 'Size Attribute Name', 'option label', 'wpsso' );
_x( 'Target Gender Attribute Name', 'option label', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Kids', 'option value', 'wpsso' );
_x( 'Adult', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Male', 'option value', 'wpsso' );
_x( 'Female', 'option value', 'wpsso' );
_x( 'Unisex', 'option value', 'wpsso' );
_x( 'Full Time', 'option value', 'wpsso' );
_x( 'Part Time', 'option value', 'wpsso' );
_x( 'Contractor', 'option value', 'wpsso' );
_x( 'Temporary', 'option value', 'wpsso' );
_x( 'Intern', 'option value', 'wpsso' );
_x( 'Volunteer', 'option value', 'wpsso' );
_x( 'Per Diem', 'option value', 'wpsso' );
_x( 'Other', 'option value', 'wpsso' );
_x( 'Physical Location', 'option value', 'wpsso' );
_x( 'Online', 'option value', 'wpsso' );
_x( 'Mixed', 'option value', 'wpsso' );
_x( 'Cancelled', 'option value', 'wpsso' );
_x( 'Moved Online', 'option value', 'wpsso' );
_x( 'Postponed', 'option value', 'wpsso' );
_x( 'Rescheduled', 'option value', 'wpsso' );
_x( 'Scheduled', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Discontinued', 'option value', 'wpsso' );
_x( 'In Stock', 'option value', 'wpsso' );
_x( 'In Store Only', 'option value', 'wpsso' );
_x( 'Limited Availability', 'option value', 'wpsso' );
_x( 'Online Only', 'option value', 'wpsso' );
_x( 'Out of Stock', 'option value', 'wpsso' );
_x( 'Pre-Order', 'option value', 'wpsso' );
_x( 'Sold Out', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Damaged', 'option value', 'wpsso' );
_x( 'New', 'option value', 'wpsso' );
_x( 'Refurbished', 'option value', 'wpsso' );
_x( 'Used', 'option value', 'wpsso' );
_x( 'Every day', 'option value', 'wpsso' );
_x( 'Every two days', 'option value', 'wpsso' );
_x( 'Every three days', 'option value', 'wpsso' );
_x( 'Every four days', 'option value', 'wpsso' );
_x( 'Every five days', 'option value', 'wpsso' );
_x( 'Every six days', 'option value', 'wpsso' );
_x( 'Every week', 'option value', 'wpsso' );
_x( 'Every two weeks', 'option value', 'wpsso' );
_x( 'Development and Up', 'option value', 'wpsso' );
_x( 'Alpha and Up', 'option value', 'wpsso' );
_x( 'Beta and Up', 'option value', 'wpsso' );
_x( 'Release Candidate and Up', 'option value', 'wpsso' );
_x( 'Stable / Production', 'option value', 'wpsso' );
