<?php die( 'These aren\'t the droids you\'re looking for...' );

/**
 * Extract of translatable text strings from the lib/pro classes.
 */
_x( 'Use Filtered (SEO) Title', 'option label', 'wpsso' );
_x( 'Use WordPress Content Filters', 'option label', 'wpsso' );
_x( 'recommended', 'option comment', 'wpsso' );
_x( 'Use WordPress Excerpt Filters', 'option label', 'wpsso' );
_x( 'Content Starts at 1st Paragraph', 'option label', 'wpsso' );
_x( 'Use Image Alt if No Content', 'option label', 'wpsso' );
_x( 'Image Alt Text Prefix', 'option label', 'wpsso' );
_x( 'WP Caption Prefix', 'option label', 'wpsso' );
_x( 'Check for Embedded Media', 'option label', 'wpsso' );
_x( '&lt;html&gt; Attributes Filter Hook', 'option label', 'wpsso' );
_x( '&lt;head&gt; Attributes Filter Hook', 'option label', 'wpsso' );
_x( 'Honor the FORCE_SSL Constant', 'option label', 'wpsso' );
_x( 'Add Person Role for New Users', 'option label', 'wpsso' );
_x( 'Enable WP Excerpt for Pages', 'option label', 'wpsso' );
_x( 'Enable WP Tags for Pages', 'option label', 'wpsso' );
_x( 'Check for Duplicate Meta Tags', 'option label', 'wpsso' );
_x( 'Enforce Image Dimensions Check', 'option label', 'wpsso' );
_x( 'recommended', 'option comment', 'wpsso' );
_x( 'Allow Upscale of WP Media Images', 'option label', 'wpsso' );
_x( 'Maximum Image Upscale Percent', 'option label', 'wpsso' );
_x( 'Add %s Metabox to', 'option label', 'wpsso' );
_x( 'Read Yoast SEO Social Meta', 'option label', 'wpsso' );
_x( 'Default Currency', 'option label', 'wpsso' );
__( 'Posts, Pages, Custom Post Types', 'wpsso' );
__( 'Media Library', 'wpsso' );
__( 'Terms (Categories and Tags)', 'wpsso' );
// translators: please ignore - translation uses a different text domain
__( 'Users' );
_x( 'Additional List Table Columns', 'option label', 'wpsso' );
_x( 'Title / Name Column Width', 'option label', 'wpsso' );
_x( 'and max width', 'option comment', 'wpsso' );
_x( 'Default Width for Posts / Pages', 'option label', 'wpsso' );
_x( 'and max width', 'option comment', 'wpsso' );
_x( 'Head Markup Array Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Filtered Content Text Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Shortened URL Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Image URL Info Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Article Topics Array Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Schema JSON Data Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Schema Types Array Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Clear All Caches on Activate', 'option label', 'wpsso' );
_x( 'Clear All Caches on Deactivate', 'option label', 'wpsso' );
_x( 'Clear All Caches on Save Settings', 'option label', 'wpsso' );
_x( 'Refresh Short URLs on Clear Cache', 'option label', 'wpsso' );
_x( 'Auto-Refresh Cache After Clearing', 'option label', 'wpsso' );
_x( 'Clear Term Cache for Published Post', 'option label', 'wpsso' );
_x( 'Clear Post Cache for New Comment', 'option label', 'wpsso' );
_x( 'Preferred URL Shortening Service', 'option label', 'wpsso' );
_x( 'Minimum URL Length to Shorten', 'option label', 'wpsso' );
_x( 'characters', 'option comment', 'wpsso' );
_x( 'Short Sharing URL for WP Shortlink', 'option label', 'wpsso' );
_x( 'Add "%s" HTML Tag', 'option label', 'wpsso' );
_x( 'Bitly URL Shortener', 'metabox title', 'wpsso' );
_x( 'Bitly Username', 'option label', 'wpsso' );
_x( 'Bitly Generic Access Token', 'option label', 'wpsso' );
_x( 'or Bitly API Key (deprecated)', 'option label', 'wpsso' );
_x( 'api key authentication is deprecated', 'option comment', 'wpsso' );
_x( 'Bitly Custom Short Domain', 'option label', 'wpsso' );
_x( 'DLMY.App URL Shortener', 'metabox title', 'wpsso' );
_x( 'DLMY.App API Key', 'option label', 'wpsso' );
_x( 'Ow.ly URL Shortener', 'metabox title', 'wpsso' );
_x( 'Ow.ly API Key', 'option label', 'wpsso' );
_x( 'Your Own URL Shortener (YOURLS)', 'metabox title', 'wpsso' );
_x( 'YOURLS API URL', 'option label', 'wpsso' );
_x( 'YOURLS Username', 'option label', 'wpsso' );
_x( 'YOURLS Password', 'option label', 'wpsso' );
_x( 'YOURLS Token', 'option label', 'wpsso' );
_x( 'Show', 'column title', 'wpsso' );
_x( 'Contact Field ID', 'column title', 'wpsso' );
_x( 'Contact Field Label', 'column title', 'wpsso' );
_x( 'Show', 'column title', 'wpsso' );
_x( 'Contact Field ID', 'column title', 'wpsso' );
_x( 'Contact Field Label', 'column title', 'wpsso' );
__( 'An SEO plugin has been detected &mdash; some basic SEO meta tags have been unchecked and disabled automatically.', 'wpsso' );
_x( 'Gravatar is Author Default Image', 'option label', 'wpsso' );
_x( 'Enforce Image Dimensions Check', 'option label', 'wpsso' );
_x( 'recommended', 'option comment', 'wpsso' );
_x( 'Allow Upscale of WP Media Images', 'option label', 'wpsso' );
_x( 'Maximum Image Upscale Percent', 'option label', 'wpsso' );
_x( 'Maximum Videos to Include', 'option label', 'wpsso' );
_x( 'Use HTTPS for Video API Requests', 'option label', 'wpsso' );
_x( 'uses %s', 'option comment', 'wpsso' );
_x( 'Include Video Preview Images', 'option label', 'wpsso' );
_x( 'video preview images are included first', 'option comment', 'wpsso' );
_x( 'Include text/html Type Meta Tags', 'option label', 'wpsso' );
_x( 'Force Autoplay when Possible', 'option label', 'wpsso' );
_x( 'Check for Embedded Media', 'option label', 'wpsso' );
__( 'Activate the %s add-on for additional Schema markup features and options.', 'wpsso' );
__( 'This option is disabled (the "%1$s" head tag is disabled or an SEO plugin was detected).', 'wpsso' );
_x( 'Open Graph Type', 'option label', 'wpsso' );
_x( 'Article Topic', 'option label', 'wpsso' );
_x( 'Default Title', 'option label', 'wpsso' );
_x( 'Default Description', 'option label', 'wpsso' );
_x( 'Search Description', 'option label', 'wpsso' );
_x( 'Twitter Card Description', 'option label', 'wpsso' );
_x( 'Sharing URL', 'option label', 'wpsso' );
_x( 'Canonical URL', 'option label', 'wpsso' );
_x( 'Product Availability', 'option label', 'wpsso' );
_x( 'Product Brand', 'option label', 'wpsso' );
_x( 'Product Color', 'option label', 'wpsso' );
_x( 'Product Condition', 'option label', 'wpsso' );
_x( 'Product Material', 'option label', 'wpsso' );
_x( 'Product SKU', 'option label', 'wpsso' );
_x( 'Product EAN', 'option label', 'wpsso' );
_x( 'Product GTIN-8', 'option label', 'wpsso' );
_x( 'Product GTIN-12', 'option label', 'wpsso' );
_x( 'Product GTIN-13', 'option label', 'wpsso' );
_x( 'Product GTIN-14', 'option label', 'wpsso' );
_x( 'Product ISBN', 'option label', 'wpsso' );
_x( 'Product Price', 'option label', 'wpsso' );
_x( 'Product Size', 'option label', 'wpsso' );
_x( 'Product Target Gender', 'option label', 'wpsso' );
_x( 'Structured Data / Schema Markup', 'metabox title', 'wpsso' );
_x( 'Description', 'option label', 'wpsso' );
__( 'Save a draft version or publish the %s to update this value.', 'wpsso' );
__( 'Activate the %s add-on for additional Schema markup features and options.', 'wpsso' );
__( 'This option is disabled (the "%1$s" head tag is disabled or an SEO plugin was detected).', 'wpsso' );
_x( 'Default Title', 'option label', 'wpsso' );
_x( 'Default Description', 'option label', 'wpsso' );
_x( 'Search Description', 'option label', 'wpsso' );
_x( 'Twitter Card Description', 'option label', 'wpsso' );
_x( 'Sharing URL', 'option label', 'wpsso' );
_x( 'Canonical URL', 'option label', 'wpsso' );
_x( 'Structured Data / Schema Markup', 'metabox title', 'wpsso' );
_x( 'Description', 'option label', 'wpsso' );
__( 'Save a draft version or publish the %s to display these options.', 'wpsso' );
_x( 'All Social WebSites / Open Graph', 'metabox title', 'wpsso' );
_x( 'Priority Image Information', 'metabox title', 'wpsso' );
_x( 'Maximum Images', 'option label', 'wpsso' );
_x( 'Image Dimensions', 'option label', 'wpsso' );
_x( 'Image ID', 'option label', 'wpsso' );
_x( 'or an Image URL', 'option label', 'wpsso' );
_x( 'Priority Video Information', 'metabox title', 'wpsso' );
_x( 'Include Preview Images', 'option label', 'wpsso' );
_x( 'Maximum Videos', 'option label', 'wpsso' );
_x( 'Video Dimensions', 'option label', 'wpsso' );
_x( 'Video Embed HTML', 'option label', 'wpsso' );
_x( 'or a Video URL', 'option label', 'wpsso' );
_x( 'Video Name / Title', 'option label', 'wpsso' );
_x( 'Video Description', 'option label', 'wpsso' );
_x( 'Twitter Card', 'metabox title', 'wpsso' );
_x( 'Image Dimensions', 'option label', 'wpsso' );
_x( 'Image ID', 'option label', 'wpsso' );
_x( 'or an Image URL', 'option label', 'wpsso' );
_x( 'Structured Data / Schema Markup / Pinterest', 'metabox title', 'wpsso' );
_x( 'Maximum Images', 'option label', 'wpsso' );
_x( 'Image Dimensions', 'option label', 'wpsso' );
_x( 'Image ID', 'option label', 'wpsso' );
_x( 'or an Image URL', 'option label', 'wpsso' );
__( '"%s" is  an unknown Schema product item condition.', 'wpsso' );
__( 'Valid item condition values are (case is important): %s.', 'wpsso' );
__( 'https://docs.woocommerce.com/wc-apidocs/function-wc_get_price_including_tax.html', 'wpsso' );
__( 'The <a href="%1$s">WooCommerce %2$s function</a> is not available.', 'wpsso' );
__( 'Please update your site to WooCommerce version %s or better.', 'wpsso' );
__( 'https://secure.php.net/manual/en/function.simplexml-load-string.php', 'wpsso' );
__( 'The <a href="%1$s">PHP %2$s function</a> is not available.', 'wpsso' );
__( 'Please contact your hosting provider to have the missing PHP function installed.', 'wpsso' );
__( 'https://secure.php.net/manual/en/function.simplexml-load-string.php', 'wpsso' );
__( 'The <a href="%1$s">PHP %2$s function</a> is not available.', 'wpsso' );
__( 'Please contact your hosting provider to have the missing PHP function installed.', 'wpsso' );
__( 'https://secure.php.net/manual/en/function.simplexml-load-string.php', 'wpsso' );
__( 'The <a href="%1$s">PHP %2$s function</a> is not available.', 'wpsso' );
__( 'Please contact your hosting provider to have the missing PHP function installed.', 'wpsso' );
__( 'Failed to upscale image ID %1$s of %2$s by %3$s from %4$s to %5$s for the %6$s image size (exceeds %7$s maximum upscale setting).', 'wpsso' );
__( 'Image ID %1$s of %2$s has been upscaled by %3$s from %4$s to %5$s for the %6$s image size.', 'wpsso' );
__( 'NextGEN Gallery', 'wpsso' );
__( 'image ID %s', 'wpsso' );
__( 'cropped', 'wpsso' );
__( '%1$s %2$s ignored &mdash; the resulting image of %3$s is too small for the required %4$s image dimensions.', 'wpsso' );
__( 'NextGEN Gallery', 'wpsso' );
_x( 'BuddyPress Member Bio Field Name', 'option label', 'wpsso' );
__( 'The BuddyPress member profile page does not include the <em>Biographical Info</em> text from the WordPress user profile. If you\'ve created an additional BuddyPress Profile Field for members to enter their profile description, enter the field name here (example: Biographical Info, About Me, etc.).', 'wpsso' );
__( 'No Description', 'wpsso' );
__( 'Database meta table row "%2$s" for post ID %1$d was found and converted to "%3$s".', 'wpsso' );
__( 'The URL shortening library file "%s" is missing and required.', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'Bitly Username', 'option label', 'wpsso' );
__( 'The "%1$s" and "%2$s" option values are empty &mdash; at least one option value is required.', 'wpsso' );
_x( 'Bitly Generic Access Token', 'option label', 'wpsso' );
_x( 'Bitly API Key', 'option label', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'DLMY.App API Key', 'option label', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'Ow.ly API Key', 'option label', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'YOURLS API URL', 'option label', 'wpsso' );
__( 'Incomplete and/or missing API credentials for the "%s" URL shortening service.', 'wpsso' );
__( 'Database meta table row "%2$s" for user ID %1$d was found and converted to "%3$s".', 'wpsso' );
__( 'Database meta table row "%2$s" for term ID %1$d was found and converted to "%3$s".', 'wpsso' );
__( 'full size original', 'wpsso' );
__( 'Media Library', 'wpsso' );
__( 'image ID %s', 'wpsso' );
__( 'cropped', 'wpsso' );
__( '%1$s %2$s ignored &mdash; the resulting image of %3$s is too small for the required %4$s image dimensions.', 'wpsso' );
__( 'Image %1$s in content ignored &mdash; the image width / height is too small for the required %2$s image dimensions.', 'wpsso' );
__( '%1$s includes an additional \'data-wp-pid\' attribute for Media Library images &mdash; if this image was selected from the Media Library before %1$s was activated, try removing and adding the image back to your content.', 'wpsso' );
_x( 'Single Entry Integration', 'metabox title', 'wpsso' );
_x( 'Title Field ID', 'option label', 'wpsso' );
_x( 'Description Field ID', 'option label', 'wpsso' );
_x( 'Post Image Field ID', 'option label', 'wpsso' );
__( 'Yotpo for WooCommerce "%s" setting value is empty.', 'wpsso' );
__( 'Yotpo for WooCommerce "%s" setting value is empty.', 'wpsso' );
__( 'Yotpo for WooCommerce %s function returned an error.', 'wpsso' );
__( '"%s" not found in the WPMU_PLUGIN_DIR or WP_PLUGIN_DIR folders.', 'wpsso' );
__( 'Yotpo for WooCommerce API library file "%s" not found.', 'wpsso' );
__( 'Plugin conflict detected', 'wpsso' );
// translators: please ignore - translation uses a different text domain
__( 'Enable Google Rich Snippets?', 'wp-postratings' );
// translators: please ignore - translation uses a different text domain
__( 'Ratings', 'wp-postratings' );
// translators: please ignore - translation uses a different text domain
__( 'Ratings Options', 'wp-postratings' );
__( 'please disable the %1$s option in the %2$s settings page.', 'wpsso' );
