<?php die( 'These aren\'t the droids you\'re looking for.' );

/**
 * Extract of translatable text strings from the lib/pro classes.
 */
_x( 'Use Filtered (aka SEO) Title', 'option label', 'wpsso' );
_x( 'Use WordPress Content Filters', 'option label', 'wpsso' );
_x( 'recommended', 'option comment', 'wpsso' );
_x( 'Use WordPress Excerpt Filters', 'option label', 'wpsso' );
_x( 'Content Starts at 1st Paragraph', 'option label', 'wpsso' );
_x( 'Use Image Alt if No Content', 'option label', 'wpsso' );
_x( 'Content Image Alt Prefix', 'option label', 'wpsso' );
_x( 'WP Caption Text Prefix', 'option label', 'wpsso' );
_x( 'No Title Text', 'option label', 'wpsso' );
_x( 'No Description Text', 'option label', 'wpsso' );
_x( 'Check for Embedded Media', 'option label', 'wpsso' );
_x( 'Add Person Role to New Users', 'option label', 'wpsso' );
_x( 'Enable WP Excerpt for Pages', 'option label', 'wpsso' );
_x( 'Enable WP Tags for Pages', 'option label', 'wpsso' );
_x( 'Check for Duplicate Meta Tags', 'option label', 'wpsso' );
_x( 'Enforce Image Dimension Checks', 'option label', 'wpsso' );
_x( 'recommended', 'option comment', 'wpsso' );
_x( 'Upscale Media Library Images', 'option label', 'wpsso' );
_x( 'Maximum Image Upscale Percent', 'option label', 'wpsso' );
_x( '&lt;html&gt; Attributes Filter Hook', 'option label', 'wpsso' );
_x( '&lt;head&gt; Attributes Filter Hook', 'option label', 'wpsso' );
_x( 'User Profile', 'option label', 'wpsso' );
_x( 'Post Type', 'option label', 'wpsso' );
_x( 'Taxonomy', 'option label', 'wpsso' );
_x( 'Add %s Metabox', 'option label', 'wpsso' );
_x( 'Import Yoast SEO Social Meta', 'option label', 'wpsso' );
_x( 'Show Yoast SEO Import Details', 'option label', 'wpsso' );
_x( 'Default Currency', 'option label', 'wpsso' );
__( 'Posts, Pages, and Custom Post Types', 'wpsso' );
__( 'Media Library', 'wpsso' );
__( 'Categories, Tags, and Custom Taxonomies', 'wpsso' );
// translators: Please ignore - translation uses a different text domain.
__( 'Users' );
_x( 'Additional List Table Columns', 'option label', 'wpsso' );
_x( 'Title / Name Column Width', 'option label', 'wpsso' );
_x( 'and max width', 'option comment', 'wpsso' );
_x( 'Default Width for Posts / Pages', 'option label', 'wpsso' );
_x( 'and max width', 'option comment', 'wpsso' );
_x( 'Head Markup Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Filtered Content Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Image URL Info Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Video API Info Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Shortened URL Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Schema Types Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Form Selects Cache Expiry', 'option label', 'wpsso' );
_x( 'seconds (0 to disable)', 'option comment', 'wpsso' );
_x( 'Clear All Caches on Activate', 'option label', 'wpsso' );
_x( 'Clear All Caches on Deactivate', 'option label', 'wpsso' );
_x( 'Refresh Short URLs on Clear Cache', 'option label', 'wpsso' );
_x( 'Clear Term Cache for Published Post', 'option label', 'wpsso' );
_x( 'Clear Post Cache for New Comment', 'option label', 'wpsso' );
_x( 'Gravatar is Default Author Image', 'option label', 'wpsso' );
_x( 'Gravatar Image Size', 'option label', 'wpsso' );
_x( 'URL Shortening Service', 'option label', 'wpsso' );
_x( 'Minimum URL Length to Shorten', 'option label', 'wpsso' );
_x( 'characters', 'option comment', 'wpsso' );
_x( 'Use Shortened URL for WP Shortlink', 'option label', 'wpsso' );
_x( 'Add "%s" HTML Tag', 'option label', 'wpsso' );
_x( 'Bitly (URL Shortener)', 'metabox title', 'wpsso' );
_x( 'Bitly Generic Access Token', 'option label', 'wpsso' );
_x( 'Bitly Short Domain (Optional)', 'option label', 'wpsso' );
_x( 'Bitly Group Name (Optional)', 'option label', 'wpsso' );
_x( 'DLMY.App (URL Shortener)', 'metabox title', 'wpsso' );
_x( 'DLMY.App API Key', 'option label', 'wpsso' );
_x( 'Ow.ly (URL Shortener)', 'metabox title', 'wpsso' );
_x( 'Ow.ly API Key', 'option label', 'wpsso' );
_x( 'Shopper Approved (Ratings and Reviews)', 'metabox title', 'wpsso' );
_x( 'Shopper Approved Site ID', 'option label', 'wpsso' );
_x( 'Shopper Approved API Token', 'option label', 'wpsso' );
_x( 'Maximum Number of Reviews', 'option label', 'wpsso' );
_x( 'Maximum Age of Reviews', 'option label', 'wpsso' );
_x( 'months', 'option comment', 'wpsso' );
_x( 'Post Type', 'option label', 'wpsso' );
_x( 'Get Reviews for Post Type', 'option label', 'wpsso' );
_x( 'YOURLS (URL Shortener)', 'metabox title', 'wpsso' );
_x( 'YOURLS API URL', 'option label', 'wpsso' );
_x( 'YOURLS Username', 'option label', 'wpsso' );
_x( 'YOURLS Password', 'option label', 'wpsso' );
_x( 'YOURLS Token', 'option label', 'wpsso' );
_x( 'Show', 'column title', 'wpsso' );
_x( 'Contact Field ID', 'column title', 'wpsso' );
_x( 'Contact Field Label', 'column title', 'wpsso' );
_x( 'Show', 'column title', 'wpsso' );
_x( 'Contact Field ID', 'column title', 'wpsso' );
_x( 'Contact Field Label', 'column title', 'wpsso' );
__( 'An SEO plugin has been detected &mdash; some basic SEO meta tags have been unchecked and disabled automatically.', 'wpsso' );
_x( 'Gravatar is Default Author Image', 'option label', 'wpsso' );
_x( 'Gravatar Image Size', 'option label', 'wpsso' );
_x( 'Enforce Image Dimension Checks', 'option label', 'wpsso' );
_x( 'recommended', 'option comment', 'wpsso' );
_x( 'Upscale Media Library Images', 'option label', 'wpsso' );
_x( 'Maximum Videos to Include', 'option label', 'wpsso' );
_x( 'Include Video Preview Images', 'option label', 'wpsso' );
_x( 'Force Autoplay when Possible', 'option label', 'wpsso' );
_x( 'Check for Embedded Media', 'option label', 'wpsso' );
_x( 'Basic Product Information', 'metabox title', 'wpsso' );
_x( 'Product Category', 'option label', 'wpsso' );
_x( 'Product Brand', 'option label', 'wpsso' );
_x( 'Product Price', 'option label', 'wpsso' );
_x( 'Product Availability', 'option label', 'wpsso' );
_x( 'Product Condition', 'option label', 'wpsso' );
_x( 'Product Material', 'option label', 'wpsso' );
_x( 'Product Color', 'option label', 'wpsso' );
_x( 'Product Target Gender', 'option label', 'wpsso' );
_x( 'Product Size', 'option label', 'wpsso' );
_x( 'Product Weight', 'option label', 'wpsso' );
_x( 'Product SKU', 'option label', 'wpsso' );
_x( 'Product MPN', 'option label', 'wpsso' );
_x( 'Product ISBN', 'option label', 'wpsso' );
_x( 'Schema JSON-LD Markup / Google Rich Results', 'metabox title', 'wpsso' );
_x( 'Priority Video Information', 'metabox title', 'wpsso' );
_x( 'Include Preview Images', 'option label', 'wpsso' );
_x( 'Maximum Videos', 'option label', 'wpsso' );
_x( 'Video Dimensions', 'option label', 'wpsso' );
_x( 'Video Embed HTML', 'option label', 'wpsso' );
_x( 'or a Video URL', 'option label', 'wpsso' );
_x( 'Video Name / Title', 'option label', 'wpsso' );
_x( 'Video Description', 'option label', 'wpsso' );
_x( 'Pinterest Pin It', 'metabox title', 'wpsso' );
_x( 'Image ID', 'option label', 'wpsso' );
_x( 'or an Image URL', 'option label', 'wpsso' );
_x( 'Image ID', 'option label', 'wpsso' );
_x( 'or an Image URL', 'option label', 'wpsso' );
_x( 'Schema JSON-LD Markup / Google Rich Results', 'metabox title', 'wpsso' );
__( 'Please select a page in the <a href="%s">WooCommerce Settings &gt; Advanced &gt; Page setup</a> section.', 'wpsso' );
__( 'Please select a page in the <a href="%s">WooCommerce Settings &gt; Products &gt; General</a> section.', 'wpsso' );
// translators: Please ignore - translation uses a different text domain.
__( 'My account page', 'woocommerce' );
// translators: Please ignore - translation uses a different text domain.
__( 'Cart page', 'woocommerce' );
// translators: Please ignore - translation uses a different text domain.
__( 'Checkout page', 'woocommerce' );
// translators: Please ignore - translation uses a different text domain.
__( 'Shop page', 'woocommerce' );
__( 'The WooCommerce "%1$s" option value is empty.', 'wpsso' );
__( 'The WooCommerce %s method is not available - please update to a newer version of WooCommerce.', 'wpsso' );
__( 'https://docs.woocommerce.com/wc-apidocs/function-wc_get_price_including_tax.html', 'wpsso' );
__( 'The <a href="%1$s">WooCommerce %2$s function</a> is not available.', 'wpsso' );
__( 'Please update your site to WooCommerce version %s or newer.', 'wpsso' );
__( 'https://secure.php.net/manual/en/function.simplexml-load-string.php', 'wpsso' );
__( 'The <a href="%1$s">PHP %2$s function</a> is not available.', 'wpsso' );
__( 'Please contact your hosting provider to have the missing PHP function installed.', 'wpsso' );
__( 'https://secure.php.net/manual/en/function.simplexml-load-string.php', 'wpsso' );
__( 'The <a href="%1$s">PHP %2$s function</a> is not available.', 'wpsso' );
__( 'Please contact your hosting provider to have the missing PHP function installed.', 'wpsso' );
__( 'https://secure.php.net/manual/en/function.simplexml-load-string.php', 'wpsso' );
__( 'The <a href="%1$s">PHP %2$s function</a> is not available.', 'wpsso' );
__( 'Please contact your hosting provider to have the missing PHP function installed.', 'wpsso' );
__( 'Error retrieving content from <a href="%1$s">%1$s</a>.', 'wpsso' );
__( 'Failed to upscale image ID %1$s of %2$s by %3$s from %4$s to %5$s for the %6$s image size (exceeds %7$s maximum upscale setting).', 'wpsso' );
__( 'Image ID %1$s of %2$s has been upscaled by %3$s from %4$s to %5$s for the %6$s image size.', 'wpsso' );
__( 'NextGEN Gallery', 'wpsso' );
__( 'image ID %s', 'wpsso' );
__( '%1$s %2$s ignored &mdash; the resulting image of %3$s is too small for the required %4$s image dimensions.', 'wpsso' );
__( 'NextGEN Gallery', 'wpsso' );
_x( 'BuddyPress Member Bio Field Name', 'option label', 'wpsso' );
__( 'The BuddyPress member profile page does not include the <em>Biographical Info</em> text from the WordPress user profile. If you\'ve created an additional BuddyPress Profile Field for members to enter their profile description, enter the field name here (example: Biographical Info, About Me, etc.).', 'wpsso' );
_x( 'No Description.', 'default description', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'Bitly Generic Access Token', 'option label', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'DLMY.App API Key', 'option label', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'Ow.ly API Key', 'option label', 'wpsso' );
__( 'The "%s" option value is empty and required.', 'wpsso' );
_x( 'YOURLS API URL', 'option label', 'wpsso' );
__( '%s error:', 'wpsso' );
__( 'Incomplete API options to instantiate the "%s" shortening service.', 'wpsso' );
__( '%s error:', 'wpsso' );
__( 'The URL shortening library file for "%s" is missing and required.', 'wpsso' );
__( 'Imported Yoast SEO "%1$s" metadata from post ID %2$d.', 'wpsso' );
__( 'Imported Yoast SEO "%1$s" metadata from term ID %2$d.', 'wpsso' );
__( 'Imported Yoast SEO "%1$s" metadata from user ID %2$d.', 'wpsso' );
_x( '[%s Venue]', 'option value', 'wpsso' );
_x( '[%s Organizer]', 'option value', 'wpsso' );
_x( 'Single Entry Integration', 'metabox title', 'wpsso' );
_x( 'Title Field ID', 'option label', 'wpsso' );
_x( 'Description Field ID', 'option label', 'wpsso' );
_x( 'Post Image Field ID', 'option label', 'wpsso' );
__( 'Plugin conflict detected', 'wpsso' );
// translators: Please ignore - translation uses a different text domain.
__( 'Enable Google Rich Snippets?', 'wp-postratings' );
// translators: Please ignore - translation uses a different text domain.
__( 'WP-PostRatings', 'wp-postratings' );
// translators: Please ignore - translation uses a different text domain.
__( 'Ratings', 'wp-postratings' );
// translators: Please ignore - translation uses a different text domain.
__( 'Ratings Options', 'wp-postratings' );
__( 'please disable the %1$s option in the %2$s settings page.', 'wpsso' );
__( 'Plugin conflict detected', 'wpsso' );
// translators: Please ignore - translation uses a different text domain.
__( 'Type of structured data for rich snippets', 'rate-my-post' );
// translators: Please ignore - translation uses a different text domain.
__( 'Rate my Post', 'rate-my-post' );
// translators: Please ignore - translation uses a different text domain.
__( 'Settings', 'rate-my-post' );
// translators: Please ignore - translation uses a different text domain.
__( 'Rating Widget Settings', 'rate-my-post' );
__( 'please disable the %1$s option in the %2$s settings page.', 'wpsso' );
__( '%s error:', 'wpsso' );
__( 'Yotpo for WooCommerce "%s" setting value is empty.', 'wpsso' );
__( 'Yotpo for WooCommerce "%s" setting value is empty.', 'wpsso' );
__( 'Yotpo for WooCommerce %s function is missing.', 'wpsso' );
__( 'Yotpo for WooCommerce %s function returned false.', 'wpsso' );
__( '"%s" plugin not found in the WPMU_PLUGIN_DIR or WP_PLUGIN_DIR folders.', 'wpsso' );
__( 'Yotpo for WooCommerce API library file "%s" not found.', 'wpsso' );
__( 'Yotpo for WooCommerce "%s" class does not exist.', 'wpsso' );
__( 'getting shopper approved ratings and reviews', 'wpsso' );
__( 'There has been a previous error connecting to %s for caching.', 'wpsso' );
__( 'Requests to retrieve and cache this URL are ignored for another %d second(s)', 'wpsso' );
_x( '[%s Company]', 'option value', 'wpsso' );
_x( '[%s Location]', 'option value', 'wpsso' );
