<?php die( 'These aren\'t the droids you\'re looking for.' );

/**
 * Extract of translatable text strings from the static config array.
 */
_x( 'Premium', 'distribution name', 'wpsso' );
_x( 'Standard', 'distribution name', 'wpsso' );
_x( 'Image:', 'option value', 'wpsso' );
_x( 'Caption:', 'option value', 'wpsso' );
_x( 'Facebook User URL', 'option value', 'wpsso' );
_x( 'Instagram URL', 'option value', 'wpsso' );
_x( 'LinkedIn URL', 'option value', 'wpsso' );
_x( 'Myspace URL', 'option value', 'wpsso' );
_x( 'Pinterest URL', 'option value', 'wpsso' );
_x( 'Soundcloud URL', 'option value', 'wpsso' );
_x( 'Skype Username', 'option value', 'wpsso' );
_x( 'Tumblr URL', 'option value', 'wpsso' );
_x( 'Twitter @username', 'option value', 'wpsso' );
_x( 'Wikipedia Page URL', 'option value', 'wpsso' );
_x( 'YouTube Channel URL', 'option value', 'wpsso' );
_x( 'Your SSO', 'lib file description', 'wpsso' );
_x( 'Advanced Settings', 'lib file description', 'wpsso' );
_x( 'Complementary Add-ons', 'lib file description', 'wpsso' );
_x( 'Premium Licenses', 'lib file description', 'wpsso' );
_x( 'Essential Settings', 'lib file description', 'wpsso' );
_x( 'Setup Guide', 'lib file description', 'wpsso' );
_x( 'Dashboard', 'lib file description', 'wpsso' );
_x( 'General Settings', 'lib file description', 'wpsso' );
_x( 'Advanced Settings', 'lib file description', 'wpsso' );
_x( 'Social Pages', 'lib file description', 'wpsso' );
_x( 'Image Sizes', 'lib file description', 'wpsso' );
_x( 'Tools and Actions', 'lib file description', 'wpsso' );
_x( 'Complementary Add-ons', 'lib file description', 'wpsso' );
_x( 'Premium Licenses', 'lib file description', 'wpsso' );
_x( 'Makes sure your content looks great on all social and search sites - no matter how webpage URLs are crawled, shared, re-shared, posted, or embedded.', 'plugin description', 'wpsso' );
_x( 'Apple Store / iTunes and Google Play App meta tags for Apple\'s mobile Safari banner and Twitter\'s App Card.', 'plugin description', 'wpsso' );
_x( 'Schema BreadcrumbList markup in JSON-LD for better Google Rich Results with Structured Data.', 'plugin description', 'wpsso' );
_x( 'Manage FAQ categories with Question and Answer pages.', 'plugin description', 'wpsso' );
_x( 'Inherit featured and custom images from parents for posts, pages, custom post types, categories, tags, and custom taxonomies.', 'plugin description', 'wpsso' );
_x( 'Google Rich Results with Structured Data for Articles, Carousels, Events, FAQPages, HowTos, Images, Local Business, Products, Recipes, Reviews, Videos, and more.', 'plugin description', 'wpsso' );
_x( 'Customize home page Schema Organization markup and manage additional Organizations (publisher, organizer, etc.).', 'plugin description', 'wpsso' );
_x( 'Facebook / Open Graph Location, Pinterest Place, Schema Local Business and Local SEO meta tags.', 'plugin description', 'wpsso' );
_x( 'Ratings and reviews for WordPress comments with Aggregate Rating meta tags and Schema Review markup.', 'plugin description', 'wpsso' );
_x( 'Enhances the WordPress REST API post, term, and user query results with an array of social and SEO meta tags, and Schema JSON-LD markup.', 'plugin description', 'wpsso' );
_x( 'Ridiculously Responsive (SVG) Social Sharing Buttons for your content, excerpts, CSS sidebar, widget, shortcode, editor pages, etc.', 'plugin description', 'wpsso' );
_x( 'Traditional social sharing buttons with support for hashtags, short URLs, bbPress, BuddyPress, WooCommerce, and much more.', 'plugin description', 'wpsso' );
_x( 'Removes outdated Schema microdata from theme templates and leaves Schema JSON-LD untouched for better Google Rich Results.', 'plugin description', 'wpsso' );
_x( 'Twitter-style quoted text for your content with customizable CSS and convenient Tweet share link.', 'plugin description', 'wpsso' );
_x( 'Sharpen and improve WordPress thumbnails and resized images for social sharing and better SEO.', 'plugin description', 'wpsso' );
_x( 'Quick and easy locale / language / region selector for the WordPress admin toolbar.', 'plugin description', 'wpsso' );
_x( 'Update manager for the WPSSO Core Premium plugin and its complementary Premium add-ons.', 'plugin description', 'wpsso' );
_x( 'SSO', 'menu title', 'wpsso' );
_x( 'Document SSO (Social and Search Optimization)', 'metabox title', 'wpsso' );
_x( 'Schema', 'column header', 'wpsso' );
_x( 'OG Type', 'column header', 'wpsso' );
_x( 'SSO Image', 'column header', 'wpsso' );
_x( 'SSO Desc', 'column header', 'wpsso' );
_x( 'List Arrays', 'option label', 'wpsso' );
_x( 'Head Markup', 'option label', 'wpsso' );
_x( 'Image URL Info', 'option label', 'wpsso' );
_x( 'Shortened URLs', 'option label', 'wpsso' );
_x( 'Schema Types', 'option label', 'wpsso' );
_x( 'All Transients', 'option label', 'wpsso' );
_x( 'Filtered Content', 'option label', 'wpsso' );
_x( 'All WP Objects', 'option label', 'wpsso' );
_x( 'Yes', 'option value', 'wpsso' );
_x( 'No', 'option value', 'wpsso' );
_x( 'True', 'option value', 'wpsso' );
_x( 'False', 'option value', 'wpsso' );
_x( 'On', 'option value', 'wpsso' );
_x( 'Off', 'option value', 'wpsso' );
_x( 'Sunday', 'option value', 'wpsso' );
_x( 'Monday', 'option value', 'wpsso' );
_x( 'Tuesday', 'option value', 'wpsso' );
_x( 'Wednesday', 'option value', 'wpsso' );
_x( 'Thursday', 'option value', 'wpsso' );
_x( 'Friday', 'option value', 'wpsso' );
_x( 'Saturday', 'option value', 'wpsso' );
_x( 'Public Holidays', 'option value', 'wpsso' );
_x( 'Hour', 'option value', 'wpsso' );
_x( 'Day', 'option value', 'wpsso' );
_x( 'Week', 'option value', 'wpsso' );
_x( 'Month', 'option value', 'wpsso' );
_x( 'Year', 'option value', 'wpsso' );
_x( '(default)', 'option value', 'wpsso' );
_x( '(no images)', 'option value', 'wpsso' );
_x( '(no videos)', 'option value', 'wpsso' );
_x( '(settings value)', 'option value', 'wpsso' );
_x( '(option disabled)', 'option value', 'wpsso' );
_x( 'default is %s', 'option value', 'wpsso' );
_x( 'checked', 'option value', 'wpsso' );
_x( 'unchecked', 'option value', 'wpsso' );
_x( 'at', 'option value', 'wpsso' );
_x( 'tz', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Header', 'option value', 'wpsso' );
_x( 'Footer', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Title Only', 'option value', 'wpsso' );
_x( 'Excerpt Only', 'option value', 'wpsso' );
_x( 'Title and Excerpt', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Organization', 'option value', 'wpsso' );
_x( 'Person', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'First and Last Names', 'option value', 'wpsso' );
_x( 'Display Name', 'option value', 'wpsso' );
_x( 'Nickname', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( '[Custom Address]', 'option value', 'wpsso' );
_x( '[New Address]', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( '[New Organization]', 'option value', 'wpsso' );
_x( '[WebSite Organization]', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( '[Custom Place]', 'option value', 'wpsso' );
_x( '[New Place]', 'option value', 'wpsso' );
_x( 'Basic Options', 'option value', 'wpsso' );
_x( 'All Options', 'option value', 'wpsso' );
_x( 'SSO Toolbar Notices', 'option value', 'wpsso' );
_x( 'WP Admin Notices', 'option value', 'wpsso' );
_x( 'New activation', 'option value', 'wpsso' );
_x( 'If value is empty', 'option value', 'wpsso' );
_x( 'Force this value', 'option value', 'wpsso' );
_x( 'Left', 'option value', 'wpsso' );
_x( 'Center', 'option value', 'wpsso' );
_x( 'Right', 'option value', 'wpsso' );
_x( 'Top', 'option value', 'wpsso' );
_x( 'Center', 'option value', 'wpsso' );
_x( 'Bottom', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Categories', 'option value', 'wpsso' );
_x( 'Parents', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Parents', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Bitly (suggested)', 'option value', 'wpsso' );
_x( 'DLMY.App', 'option value', 'wpsso' );
_x( 'Ow.ly', 'option value', 'wpsso' );
_x( 'TinyURL', 'option value', 'wpsso' );
_x( 'YOURLS', 'option value', 'wpsso' );
_x( 'Facebook Business Page URL', 'option value', 'wpsso' );
_x( 'Instagram Business Profile URL', 'option value', 'wpsso' );
_x( 'LinkedIn Business Page URL', 'option value', 'wpsso' );
_x( 'Myspace Business Page URL', 'option value', 'wpsso' );
_x( 'Pinterest Business Page URL', 'option value', 'wpsso' );
_x( 'Soundcloud Business Page URL', 'option value', 'wpsso' );
_x( 'Twitter Business @username', 'option value', 'wpsso' );
_x( 'Tumblr Business Page URL', 'option value', 'wpsso' );
_x( 'Wikipedia Organization Page URL', 'option value', 'wpsso' );
_x( 'YouTube Business Channel URL', 'option value', 'wpsso' );
_x( 'Facebook Videos', 'option value', 'wpsso' );
_x( 'Slideshare Presentations', 'option value', 'wpsso' );
_x( 'Soundcloud Tracks', 'option value', 'wpsso' );
_x( 'Vimeo Videos', 'option value', 'wpsso' );
_x( 'Wistia Videos', 'option value', 'wpsso' );
_x( 'WordPress Video Shortcode', 'option value', 'wpsso' );
_x( 'YouTube Videos and Playlists', 'option value', 'wpsso' );
_x( 'Image URL Custom Field', 'option label', 'wpsso' );
_x( 'Microdata Type URLs Custom Field', 'option label', 'wpsso' );
_x( 'How-To Steps Custom Field', 'option label', 'wpsso' );
_x( 'How-To Supplies Custom Field', 'option label', 'wpsso' );
_x( 'How-To Tools Custom Field', 'option label', 'wpsso' );
_x( 'Product Availability Custom Field', 'option label', 'wpsso' );
_x( 'Product Brand Custom Field', 'option label', 'wpsso' );
_x( 'Product Color Custom Field', 'option label', 'wpsso' );
_x( 'Product Condition Custom Field', 'option label', 'wpsso' );
_x( 'Product Currency Custom Field', 'option label', 'wpsso' );
_x( 'Product Depth Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN-14 Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN-13/EAN Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN-12/UPC Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN-8 Custom Field', 'option label', 'wpsso' );
_x( 'Product GTIN Custom Field', 'option label', 'wpsso' );
_x( 'Product Height Custom Field', 'option label', 'wpsso' );
_x( 'Product ISBN Custom Field', 'option label', 'wpsso' );
_x( 'Product Length Custom Field', 'option label', 'wpsso' );
_x( 'Product Material Custom Field', 'option label', 'wpsso' );
_x( 'Product MPN Custom Field', 'option label', 'wpsso' );
_x( 'Product Price Custom Field', 'option label', 'wpsso' );
_x( 'Product Size Custom Field', 'option label', 'wpsso' );
_x( 'Product SKU Custom Field', 'option label', 'wpsso' );
_x( 'Product Target Gender Custom Field', 'option label', 'wpsso' );
_x( 'Product Volume Custom Field', 'option label', 'wpsso' );
_x( 'Product Weight Custom Field', 'option label', 'wpsso' );
_x( 'Product Width Custom Field', 'option label', 'wpsso' );
_x( 'Recipe Ingredients Custom Field', 'option label', 'wpsso' );
_x( 'Recipe Instructions Custom Field', 'option label', 'wpsso' );
_x( 'Same-As URLs Custom Field', 'option label', 'wpsso' );
_x( 'Video URL Custom Field', 'option label', 'wpsso' );
_x( 'Video Embed HTML Custom Field', 'option label', 'wpsso' );
_x( 'Product Brand Attribute Name', 'option value', 'wpsso' );
_x( 'Product Color Attribute Name', 'option value', 'wpsso' );
_x( 'Product Condition Attribute Name', 'option value', 'wpsso' );
_x( 'Product Depth Attribute Name', 'option value', 'wpsso' );
_x( 'Product MPN Attribute Name', 'option value', 'wpsso' );
_x( 'Product GTIN-14 Attribute Name', 'option value', 'wpsso' );
_x( 'Product GTIN-13/EAN Attribute Name', 'option value', 'wpsso' );
_x( 'Product GTIN-12/UPC Attribute Name', 'option value', 'wpsso' );
_x( 'Product GTIN-8 Attribute Name', 'option value', 'wpsso' );
_x( 'Product GTIN Attribute Name', 'option value', 'wpsso' );
_x( 'Product ISBN Attribute Name', 'option value', 'wpsso' );
_x( 'Product Material Attribute Name', 'option value', 'wpsso' );
_x( 'Product Size Attribute Name', 'option value', 'wpsso' );
_x( 'Product Target Gender Attr. Name', 'option value', 'wpsso' );
_x( 'Product Volume Attribute Name', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Kids', 'option value', 'wpsso' );
_x( 'Adult', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Male', 'option value', 'wpsso' );
_x( 'Female', 'option value', 'wpsso' );
_x( 'Unisex', 'option value', 'wpsso' );
_x( 'Full Time', 'option value', 'wpsso' );
_x( 'Part Time', 'option value', 'wpsso' );
_x( 'Contractor', 'option value', 'wpsso' );
_x( 'Temporary', 'option value', 'wpsso' );
_x( 'Intern', 'option value', 'wpsso' );
_x( 'Volunteer', 'option value', 'wpsso' );
_x( 'Per Diem', 'option value', 'wpsso' );
_x( 'Other', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Discontinued', 'option value', 'wpsso' );
_x( 'In Stock', 'option value', 'wpsso' );
_x( 'In Store Only', 'option value', 'wpsso' );
_x( 'Limited Availability', 'option value', 'wpsso' );
_x( 'Online Only', 'option value', 'wpsso' );
_x( 'Out of Stock', 'option value', 'wpsso' );
_x( 'Pre-Order', 'option value', 'wpsso' );
_x( 'Sold Out', 'option value', 'wpsso' );
_x( '[None]', 'option value', 'wpsso' );
_x( 'Damaged', 'option value', 'wpsso' );
_x( 'New', 'option value', 'wpsso' );
_x( 'Refurbished', 'option value', 'wpsso' );
_x( 'Used', 'option value', 'wpsso' );
_x( 'Every day', 'option value', 'wpsso' );
_x( 'Every two days', 'option value', 'wpsso' );
_x( 'Every three days', 'option value', 'wpsso' );
_x( 'Every four days', 'option value', 'wpsso' );
_x( 'Every five days', 'option value', 'wpsso' );
_x( 'Every six days', 'option value', 'wpsso' );
_x( 'Every week', 'option value', 'wpsso' );
_x( 'Development and Up', 'option value', 'wpsso' );
_x( 'Alpha and Up', 'option value', 'wpsso' );
_x( 'Beta and Up', 'option value', 'wpsso' );
_x( 'Release Candidate and Up', 'option value', 'wpsso' );
_x( 'Stable / Production', 'option value', 'wpsso' );
